import type { PartyOfficialItem } from "#/lib/server/parties";

export const MOCK_PARTY_OFFICIALS: PartyOfficialItem[] = [
  {
    assignment_id: 1,
    party_id: 1,
    chapter_id: 1,
    position_id: 1,
    user_id: 101,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-01-15",
    position_name: "National Chairman",
    position_type: "default",
    rank_order: 1,
    max_occupants: 1,
    first_name: "Adebayo",
    last_name: "Ogundipe",
    middle_name: "B.",
    username: "adebayo_ogundipe",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    email: "adebayo@free9ja.org",
    phone: "+234 802 345 6789",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Chairman",
  },
  {
    assignment_id: 2,
    party_id: 1,
    chapter_id: 2,
    position_id: 2,
    user_id: 102,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-01-15",
    position_name: "Deputy National Chairman (North)",
    position_type: "default",
    rank_order: 2,
    max_occupants: 1,
    first_name: "Amina",
    last_name: "Bello",
    middle_name: "H.",
    username: "amina_bello",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    email: "amina@free9ja.org",
    chapter_type: "zonal",
    geo_name: "North West",
    display_title: "Deputy National Chairman (North)",
  },
  {
    assignment_id: 3,
    party_id: 1,
    chapter_id: 1,
    position_id: 3,
    user_id: 103,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-02-01",
    position_name: "National Secretary",
    position_type: "default",
    rank_order: 3,
    max_occupants: 1,
    first_name: "Chukwuma",
    last_name: "Obi",
    username: "dr_obi",
    email: "obi.chukwuma@free9ja.org",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Secretary",
  },
  {
    assignment_id: 4,
    party_id: 1,
    chapter_id: 1,
    position_id: 4,
    user_id: 104,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-02-01",
    position_name: "National Legal Adviser",
    position_type: "default",
    rank_order: 4,
    max_occupants: 1,
    first_name: "Fatima",
    last_name: "Ibrahim",
    username: "barr_fatima",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    email: "fatima.ibrahim@free9ja.org",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Legal Adviser",
  },
  {
    assignment_id: 5,
    party_id: 1,
    chapter_id: 1,
    position_id: 5,
    user_id: 105,
    appointment_type: "acting",
    assignment_status: "active",
    tenure_start: "2024-03-10",
    position_name: "National Publicity Secretary",
    position_type: "default",
    rank_order: 5,
    max_occupants: 1,
    first_name: "Segun",
    last_name: "Alabi",
    username: "segun_alabi",
    email: "segun.alabi@free9ja.org",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Publicity Secretary",
  },
  {
    assignment_id: 6,
    party_id: 1,
    chapter_id: 1,
    position_id: 6,
    user_id: 106,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-01-20",
    position_name: "National Treasurer",
    position_type: "default",
    rank_order: 6,
    max_occupants: 1,
    first_name: "Kabir",
    last_name: "Mohammed",
    username: "kabir_m",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Treasurer",
  },
  {
    assignment_id: 7,
    party_id: 1,
    chapter_id: 1,
    position_id: 7,
    user_id: 107,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-02-15",
    position_name: "National Women Leader",
    position_type: "default",
    rank_order: 7,
    max_occupants: 1,
    first_name: "Nkechi",
    last_name: "Eze",
    username: "nkechi_eze",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Women Leader",
  },
  {
    assignment_id: 8,
    party_id: 1,
    chapter_id: 1,
    position_id: 8,
    user_id: 108,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-02-15",
    position_name: "National Youth Leader",
    position_type: "default",
    rank_order: 8,
    max_occupants: 1,
    first_name: "Usman",
    last_name: "Danladi",
    username: "usman_danladi",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Youth Leader",
  },
  {
    assignment_id: 9,
    party_id: 1,
    chapter_id: 1,
    position_id: 9,
    user_id: 109,
    appointment_type: "caretaker",
    assignment_status: "active",
    tenure_start: "2024-04-01",
    position_name: "National Organizing Secretary",
    position_type: "default",
    rank_order: 9,
    max_occupants: 1,
    first_name: "Olumide",
    last_name: "Williams",
    username: "prince_olumide",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Organizing Secretary",
  },
  {
    assignment_id: 10,
    party_id: 1,
    chapter_id: 1,
    position_id: 10,
    user_id: 110,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-01-25",
    position_name: "National Financial Secretary",
    position_type: "default",
    rank_order: 10,
    max_occupants: 1,
    first_name: "Aisha",
    last_name: "Garba",
    username: "aisha_garba",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Financial Secretary",
  },
  {
    assignment_id: 11,
    party_id: 1,
    chapter_id: 1,
    position_id: 11,
    user_id: 111,
    appointment_type: "interim",
    assignment_status: "active",
    tenure_start: "2024-05-01",
    position_name: "Director of Mobilization & Diaspora",
    position_type: "custom",
    rank_order: 11,
    max_occupants: 2,
    first_name: "Kingsley",
    last_name: "Agwu",
    username: "kingsley_agwu",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "Director of Mobilization & Diaspora",
  },
  {
    assignment_id: 12,
    party_id: 1,
    chapter_id: 1,
    position_id: 12,
    user_id: 112,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-01-18",
    position_name: "National Auditor",
    position_type: "default",
    rank_order: 12,
    max_occupants: 1,
    first_name: "Bashir",
    last_name: "Sanusi",
    username: "bashir_sanusi",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Auditor",
  },
  {
    assignment_id: 13,
    party_id: 1,
    chapter_id: 1,
    position_id: 13,
    user_id: 113,
    appointment_type: "acting",
    assignment_status: "active",
    tenure_start: "2024-03-22",
    position_name: "National Welfare Secretary",
    position_type: "default",
    rank_order: 13,
    max_occupants: 1,
    first_name: "Samuel",
    last_name: "Okoro",
    username: "elder_samuel",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "National Welfare Secretary",
  },
  {
    assignment_id: 14,
    party_id: 1,
    chapter_id: 20,
    position_id: 1,
    user_id: 114,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-02-10",
    position_name: "Chairman",
    position_type: "default",
    rank_order: 1,
    max_occupants: 1,
    first_name: "Babatunde",
    last_name: "Gbadamosi",
    username: "b_gbadamosi",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    chapter_type: "state",
    geo_name: "Lagos",
    display_title: "Lagos State Chairman",
  },
  {
    assignment_id: 15,
    party_id: 1,
    chapter_id: 19,
    position_id: 1,
    user_id: 115,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-02-12",
    position_name: "Chairman",
    position_type: "default",
    rank_order: 1,
    max_occupants: 1,
    first_name: "Ibrahim",
    last_name: "Shehu",
    username: "alhaji_shehu",
    chapter_type: "state",
    geo_name: "Kano",
    display_title: "Kano State Chairman",
  },
  {
    assignment_id: 16,
    party_id: 1,
    chapter_id: 32,
    position_id: 3,
    user_id: 116,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-03-01",
    position_name: "Secretary",
    position_type: "default",
    rank_order: 3,
    max_occupants: 1,
    first_name: "Ngozi",
    last_name: "Okonkwo",
    username: "ngozi_okonkwo",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    chapter_type: "state",
    geo_name: "Rivers",
    display_title: "Rivers State Secretary",
  },
  {
    assignment_id: 17,
    party_id: 1,
    chapter_id: 540,
    position_id: 1,
    user_id: 117,
    appointment_type: "acting",
    assignment_status: "active",
    tenure_start: "2024-04-15",
    position_name: "Chairman",
    position_type: "default",
    rank_order: 1,
    max_occupants: 1,
    first_name: "Tunde",
    last_name: "Bakare",
    username: "tunde_ikeja",
    chapter_type: "lga",
    geo_name: "Ikeja",
    display_title: "Ikeja LGA Chairman",
  },
  {
    assignment_id: 18,
    party_id: 1,
    chapter_id: 480,
    position_id: 1,
    user_id: 118,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-03-18",
    position_name: "Chairman",
    position_type: "default",
    rank_order: 1,
    max_occupants: 1,
    first_name: "Yakubu",
    last_name: "Sadiq",
    username: "yakubu_kano",
    chapter_type: "lga",
    geo_name: "Kano Municipal",
    display_title: "Kano Municipal LGA Chairman",
  },
  {
    assignment_id: 19,
    party_id: 1,
    chapter_id: 7200,
    position_id: 1,
    user_id: 119,
    appointment_type: "substantive",
    assignment_status: "active",
    tenure_start: "2024-04-20",
    position_name: "Chairman",
    position_type: "default",
    rank_order: 1,
    max_occupants: 1,
    first_name: "Chinedu",
    last_name: "Anya",
    username: "chinedu_anya",
    chapter_type: "ward",
    geo_name: "Owerri Urban I",
    display_title: "Owerri Urban Ward 1 Chairman",
  },
  {
    assignment_id: 20,
    party_id: 1,
    chapter_id: 1,
    position_id: 20,
    user_id: 120,
    appointment_type: "interim",
    assignment_status: "active",
    tenure_start: "2024-05-15",
    position_name: "Special Envoy on Civic Tech & Youth Strategy",
    position_type: "custom",
    rank_order: 15,
    max_occupants: 1,
    first_name: "Bola",
    last_name: "Aremu",
    username: "bola_aremu",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80",
    chapter_type: "national",
    geo_name: "Nigeria",
    display_title: "Special Envoy on Civic Tech & Youth Strategy",
  },
];
