basePath: /api/v1
definitions:
  countrieshandler.CityResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  countrieshandler.CountryResponse:
    description: for GetCountries
    properties:
      id:
        type: integer
      iso2:
        type: string
      name:
        type: string
      phone_code:
        type: string
    type: object
  countrieshandler.GetCitiesResponse:
    properties:
      cities:
        items:
          $ref: '#/definitions/countrieshandler.CityResponse'
        type: array
    type: object
  countrieshandler.GetCountriesResponse:
    properties:
      countries:
        items:
          $ref: '#/definitions/countrieshandler.CountryResponse'
        type: array
    type: object
  countrieshandler.GetStatesResponse:
    properties:
      states:
        items:
          $ref: '#/definitions/countrieshandler.StateResponse'
        type: array
    type: object
  countrieshandler.StateResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:4000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for the Free9ja platform.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Free9ja API
  version: "1.0"
paths:
  /:
    get:
      description: get the API root message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: API Root
      tags:
      - root
  /countries:
    get:
      consumes:
      - application/json
      description: Fetches a list of all countries with their ISO2 codes, phone codes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/countrieshandler.GetCountriesResponse'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get all countries
      tags:
      - Countries
  /countries/{countryID}/states:
    get:
      consumes:
      - application/json
      description: Fetches all states for a specific country by its ID
      parameters:
      - description: Country ID
        in: path
        name: countryID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/countrieshandler.GetStatesResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get states by country ID
      tags:
      - Countries
  /health:
    get:
      description: get the status of the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
  /states/{stateID}/cities:
    get:
      consumes:
      - application/json
      description: Fetches all cities for a specific state by its ID
      parameters:
      - description: State ID
        in: path
        name: stateID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/countrieshandler.GetCitiesResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get cities by state ID
      tags:
      - Countries
swagger: "2.0"
