// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	queries "free9ja/api/internal/db/queries"

	mock "github.com/stretchr/testify/mock"
)

// BodiesService is an autogenerated mock type for the BodiesService type
type BodiesService struct {
	mock.Mock
}

// CreateLGA provides a mock function with given fields: ctx, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName
func (_m *BodiesService) CreateLGA(ctx context.Context, name string, abbreviation string, stateID int32, stateName string, senatorialDistrictID int32, senatorialDistrictName string, federalConstituencyID int32, federalConstituencyName string) (queries.Lga, error) {
	ret := _m.Called(ctx, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)

	if len(ret) == 0 {
		panic("no return value specified for CreateLGA")
	}

	var r0 queries.Lga
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int32, string, int32, string, int32, string) (queries.Lga, error)); ok {
		return rf(ctx, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int32, string, int32, string, int32, string) queries.Lga); ok {
		r0 = rf(ctx, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	} else {
		r0 = ret.Get(0).(queries.Lga)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int32, string, int32, string, int32, string) error); ok {
		r1 = rf(ctx, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLGA provides a mock function with given fields: ctx, id
func (_m *BodiesService) DeleteLGA(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLGA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCountries provides a mock function with given fields: ctx
func (_m *BodiesService) GetAllCountries(ctx context.Context) ([]queries.ListCountriesRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCountries")
	}

	var r0 []queries.ListCountriesRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]queries.ListCountriesRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []queries.ListCountriesRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.ListCountriesRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCitiesByStateID provides a mock function with given fields: ctx, stateID
func (_m *BodiesService) GetCitiesByStateID(ctx context.Context, stateID int16) ([]queries.GetCitiesByStateIDRow, error) {
	ret := _m.Called(ctx, stateID)

	if len(ret) == 0 {
		panic("no return value specified for GetCitiesByStateID")
	}

	var r0 []queries.GetCitiesByStateIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int16) ([]queries.GetCitiesByStateIDRow, error)); ok {
		return rf(ctx, stateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int16) []queries.GetCitiesByStateIDRow); ok {
		r0 = rf(ctx, stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.GetCitiesByStateIDRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int16) error); ok {
		r1 = rf(ctx, stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLGAByID provides a mock function with given fields: ctx, id
func (_m *BodiesService) GetLGAByID(ctx context.Context, id int32) (queries.Lga, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLGAByID")
	}

	var r0 queries.Lga
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (queries.Lga, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) queries.Lga); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(queries.Lga)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLGAs provides a mock function with given fields: ctx, stateID
func (_m *BodiesService) GetLGAs(ctx context.Context, stateID int32) ([]queries.Lga, error) {
	ret := _m.Called(ctx, stateID)

	if len(ret) == 0 {
		panic("no return value specified for GetLGAs")
	}

	var r0 []queries.Lga
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]queries.Lga, error)); ok {
		return rf(ctx, stateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []queries.Lga); ok {
		r0 = rf(ctx, stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.Lga)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLGA provides a mock function with given fields: ctx, id, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName
func (_m *BodiesService) UpdateLGA(ctx context.Context, id int32, name string, abbreviation string, stateID int32, stateName string, senatorialDistrictID int32, senatorialDistrictName string, federalConstituencyID int32, federalConstituencyName string) (queries.Lga, error) {
	ret := _m.Called(ctx, id, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLGA")
	}

	var r0 queries.Lga
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, string, int32, string, int32, string, int32, string) (queries.Lga, error)); ok {
		return rf(ctx, id, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, string, int32, string, int32, string, int32, string) queries.Lga); ok {
		r0 = rf(ctx, id, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	} else {
		r0 = ret.Get(0).(queries.Lga)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string, string, int32, string, int32, string, int32, string) error); ok {
		r1 = rf(ctx, id, name, abbreviation, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBodiesService creates a new instance of BodiesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBodiesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BodiesService {
	mock := &BodiesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
