// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	queries "free9ja/api/internal/db/queries"
)

// ElectionStatsService is an autogenerated mock type for the ElectionStatsService type
type ElectionStatsService struct {
	mock.Mock
}

// ListElectionGroupFederalConstituencyStatsByGroup provides a mock function with given fields: ctx, arg
func (_m *ElectionStatsService) ListElectionGroupFederalConstituencyStatsByGroup(ctx context.Context, arg queries.ListElectionGroupFederalConstituencyStatsByGroupParams) ([]queries.ElectionGroupFederalConstituency, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListElectionGroupFederalConstituencyStatsByGroup")
	}

	var r0 []queries.ElectionGroupFederalConstituency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupFederalConstituencyStatsByGroupParams) ([]queries.ElectionGroupFederalConstituency, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupFederalConstituencyStatsByGroupParams) []queries.ElectionGroupFederalConstituency); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.ElectionGroupFederalConstituency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ListElectionGroupFederalConstituencyStatsByGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListElectionGroupLGAStatsByGroup provides a mock function with given fields: ctx, arg
func (_m *ElectionStatsService) ListElectionGroupLGAStatsByGroup(ctx context.Context, arg queries.ListElectionGroupLGAStatsByGroupParams) ([]queries.ElectionGroupLga, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListElectionGroupLGAStatsByGroup")
	}

	var r0 []queries.ElectionGroupLga
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupLGAStatsByGroupParams) ([]queries.ElectionGroupLga, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupLGAStatsByGroupParams) []queries.ElectionGroupLga); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.ElectionGroupLga)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ListElectionGroupLGAStatsByGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListElectionGroupPollingUnitStatsByGroup provides a mock function with given fields: ctx, arg
func (_m *ElectionStatsService) ListElectionGroupPollingUnitStatsByGroup(ctx context.Context, arg queries.ListElectionGroupPollingUnitStatsByGroupParams) ([]queries.ElectionGroupPollingUnit, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListElectionGroupPollingUnitStatsByGroup")
	}

	var r0 []queries.ElectionGroupPollingUnit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupPollingUnitStatsByGroupParams) ([]queries.ElectionGroupPollingUnit, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupPollingUnitStatsByGroupParams) []queries.ElectionGroupPollingUnit); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.ElectionGroupPollingUnit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ListElectionGroupPollingUnitStatsByGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListElectionGroupSenatorialDistrictStatsByGroup provides a mock function with given fields: ctx, arg
func (_m *ElectionStatsService) ListElectionGroupSenatorialDistrictStatsByGroup(ctx context.Context, arg queries.ListElectionGroupSenatorialDistrictStatsByGroupParams) ([]queries.ElectionGroupSenatorialDistrict, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListElectionGroupSenatorialDistrictStatsByGroup")
	}

	var r0 []queries.ElectionGroupSenatorialDistrict
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupSenatorialDistrictStatsByGroupParams) ([]queries.ElectionGroupSenatorialDistrict, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupSenatorialDistrictStatsByGroupParams) []queries.ElectionGroupSenatorialDistrict); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.ElectionGroupSenatorialDistrict)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ListElectionGroupSenatorialDistrictStatsByGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListElectionGroupStateConstituencyStatsByGroup provides a mock function with given fields: ctx, arg
func (_m *ElectionStatsService) ListElectionGroupStateConstituencyStatsByGroup(ctx context.Context, arg queries.ListElectionGroupStateConstituencyStatsByGroupParams) ([]queries.ElectionGroupStateConstituency, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListElectionGroupStateConstituencyStatsByGroup")
	}

	var r0 []queries.ElectionGroupStateConstituency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupStateConstituencyStatsByGroupParams) ([]queries.ElectionGroupStateConstituency, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupStateConstituencyStatsByGroupParams) []queries.ElectionGroupStateConstituency); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.ElectionGroupStateConstituency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ListElectionGroupStateConstituencyStatsByGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListElectionGroupStateStatsByGroup provides a mock function with given fields: ctx, electionGroupID
func (_m *ElectionStatsService) ListElectionGroupStateStatsByGroup(ctx context.Context, electionGroupID int64) ([]queries.ElectionGroupState, error) {
	ret := _m.Called(ctx, electionGroupID)

	if len(ret) == 0 {
		panic("no return value specified for ListElectionGroupStateStatsByGroup")
	}

	var r0 []queries.ElectionGroupState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]queries.ElectionGroupState, error)); ok {
		return rf(ctx, electionGroupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []queries.ElectionGroupState); ok {
		r0 = rf(ctx, electionGroupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.ElectionGroupState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, electionGroupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListElectionGroupWardStatsByGroup provides a mock function with given fields: ctx, arg
func (_m *ElectionStatsService) ListElectionGroupWardStatsByGroup(ctx context.Context, arg queries.ListElectionGroupWardStatsByGroupParams) ([]queries.ElectionGroupWard, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListElectionGroupWardStatsByGroup")
	}

	var r0 []queries.ElectionGroupWard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupWardStatsByGroupParams) ([]queries.ElectionGroupWard, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListElectionGroupWardStatsByGroupParams) []queries.ElectionGroupWard); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.ElectionGroupWard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ListElectionGroupWardStatsByGroupParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewElectionStatsService creates a new instance of ElectionStatsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElectionStatsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElectionStatsService {
	mock := &ElectionStatsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
