// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"

	queries "free9ja/api/internal/db/queries"
)

// FilesDB is an autogenerated mock type for the FilesDB type
type FilesDB struct {
	mock.Mock
}

// ConfirmUpload provides a mock function with given fields: ctx, arg
func (_m *FilesDB) ConfirmUpload(ctx context.Context, arg queries.ConfirmUploadParams) (queries.File, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUpload")
	}

	var r0 queries.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ConfirmUploadParams) (queries.File, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ConfirmUploadParams) queries.File); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(queries.File)
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ConfirmUploadParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateFile provides a mock function with given fields: ctx, arg
func (_m *FilesDB) CreateFile(ctx context.Context, arg queries.CreateFileParams) (queries.File, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateFile")
	}

	var r0 queries.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.CreateFileParams) (queries.File, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.CreateFileParams) queries.File); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(queries.File)
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.CreateFileParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFileByID provides a mock function with given fields: ctx, id
func (_m *FilesDB) GetFileByID(ctx context.Context, id int64) (queries.File, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByID")
	}

	var r0 queries.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (queries.File, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) queries.File); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(queries.File)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFileByKey provides a mock function with given fields: ctx, fileKey
func (_m *FilesDB) GetFileByKey(ctx context.Context, fileKey string) (queries.File, error) {
	ret := _m.Called(ctx, fileKey)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByKey")
	}

	var r0 queries.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (queries.File, error)); ok {
		return rf(ctx, fileKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) queries.File); ok {
		r0 = rf(ctx, fileKey)
	} else {
		r0 = ret.Get(0).(queries.File)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fileKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByFakeID provides a mock function with given fields: ctx, fakeID
func (_m *FilesDB) GetUserByFakeID(ctx context.Context, fakeID pgtype.Int8) (queries.User, error) {
	ret := _m.Called(ctx, fakeID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByFakeID")
	}

	var r0 queries.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Int8) (queries.User, error)); ok {
		return rf(ctx, fakeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Int8) queries.User); ok {
		r0 = rf(ctx, fakeID)
	} else {
		r0 = ret.Get(0).(queries.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.Int8) error); ok {
		r1 = rf(ctx, fakeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDeleteFile provides a mock function with given fields: ctx, id
func (_m *FilesDB) HardDeleteFile(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListFiles provides a mock function with given fields: ctx, arg
func (_m *FilesDB) ListFiles(ctx context.Context, arg queries.ListFilesParams) ([]queries.File, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []queries.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListFilesParams) ([]queries.File, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.ListFilesParams) []queries.File); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.ListFilesParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkFileDeleted provides a mock function with given fields: ctx, id
func (_m *FilesDB) MarkFileDeleted(ctx context.Context, id int64) (queries.File, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkFileDeleted")
	}

	var r0 queries.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (queries.File, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) queries.File); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(queries.File)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFilesDB creates a new instance of FilesDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilesDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *FilesDB {
	mock := &FilesDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
