// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	queries "free9ja/api/internal/db/queries"
)

// OfficesService is an autogenerated mock type for the OfficesService type
type OfficesService struct {
	mock.Mock
}

// CreateOffice provides a mock function with given fields: ctx, name, election, scope, rank
func (_m *OfficesService) CreateOffice(ctx context.Context, name string, election string, scope string, rank int32) (queries.Office, error) {
	ret := _m.Called(ctx, name, election, scope, rank)

	if len(ret) == 0 {
		panic("no return value specified for CreateOffice")
	}

	var r0 queries.Office
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int32) (queries.Office, error)); ok {
		return rf(ctx, name, election, scope, rank)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int32) queries.Office); ok {
		r0 = rf(ctx, name, election, scope, rank)
	} else {
		r0 = ret.Get(0).(queries.Office)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int32) error); ok {
		r1 = rf(ctx, name, election, scope, rank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOffice provides a mock function with given fields: ctx, id
func (_m *OfficesService) DeleteOffice(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOffice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOfficeByID provides a mock function with given fields: ctx, id
func (_m *OfficesService) GetOfficeByID(ctx context.Context, id int64) (queries.Office, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOfficeByID")
	}

	var r0 queries.Office
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (queries.Office, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) queries.Office); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(queries.Office)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOfficeByName provides a mock function with given fields: ctx, name
func (_m *OfficesService) GetOfficeByName(ctx context.Context, name string) (queries.Office, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOfficeByName")
	}

	var r0 queries.Office
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (queries.Office, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) queries.Office); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(queries.Office)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOffices provides a mock function with given fields: ctx
func (_m *OfficesService) ListOffices(ctx context.Context) ([]queries.Office, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListOffices")
	}

	var r0 []queries.Office
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]queries.Office, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []queries.Office); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.Office)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOffice provides a mock function with given fields: ctx, id, name, election, scope, rank
func (_m *OfficesService) UpdateOffice(ctx context.Context, id int64, name string, election string, scope string, rank int32) (queries.Office, error) {
	ret := _m.Called(ctx, id, name, election, scope, rank)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOffice")
	}

	var r0 queries.Office
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, int32) (queries.Office, error)); ok {
		return rf(ctx, id, name, election, scope, rank)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, int32) queries.Office); ok {
		r0 = rf(ctx, id, name, election, scope, rank)
	} else {
		r0 = ret.Get(0).(queries.Office)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, string, int32) error); ok {
		r1 = rf(ctx, id, name, election, scope, rank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOfficesService creates a new instance of OfficesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOfficesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OfficesService {
	mock := &OfficesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
