// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	queries "free9ja/api/internal/db/queries"
)

// PartiesService is an autogenerated mock type for the PartiesService type
type PartiesService struct {
	mock.Mock
}

// BuySlots provides a mock function with given fields: ctx, partyID, quantity
func (_m *PartiesService) BuySlots(ctx context.Context, partyID int64, quantity int32) (queries.Party, error) {
	ret := _m.Called(ctx, partyID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for BuySlots")
	}

	var r0 queries.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int32) (queries.Party, error)); ok {
		return rf(ctx, partyID, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int32) queries.Party); ok {
		r0 = rf(ctx, partyID, quantity)
	} else {
		r0 = ret.Get(0).(queries.Party)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int32) error); ok {
		r1 = rf(ctx, partyID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateParty provides a mock function with given fields: ctx, shortName, name, logo, displayOrder
func (_m *PartiesService) CreateParty(ctx context.Context, shortName string, name string, logo string, displayOrder int32) (queries.Party, error) {
	ret := _m.Called(ctx, shortName, name, logo, displayOrder)

	if len(ret) == 0 {
		panic("no return value specified for CreateParty")
	}

	var r0 queries.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int32) (queries.Party, error)); ok {
		return rf(ctx, shortName, name, logo, displayOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int32) queries.Party); ok {
		r0 = rf(ctx, shortName, name, logo, displayOrder)
	} else {
		r0 = ret.Get(0).(queries.Party)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int32) error); ok {
		r1 = rf(ctx, shortName, name, logo, displayOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePartyWallet provides a mock function with given fields: ctx, party
func (_m *PartiesService) CreatePartyWallet(ctx context.Context, party queries.Party) (queries.PartyWallet, error) {
	ret := _m.Called(ctx, party)

	if len(ret) == 0 {
		panic("no return value specified for CreatePartyWallet")
	}

	var r0 queries.PartyWallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.Party) (queries.PartyWallet, error)); ok {
		return rf(ctx, party)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.Party) queries.PartyWallet); ok {
		r0 = rf(ctx, party)
	} else {
		r0 = ret.Get(0).(queries.PartyWallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.Party) error); ok {
		r1 = rf(ctx, party)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreditWallet provides a mock function with given fields: ctx, walletID, amountKobo, transactionReference, payerName, payerAccountNumber, payerBankCode, narration, rawPayload
func (_m *PartiesService) CreditWallet(ctx context.Context, walletID int64, amountKobo int64, transactionReference string, payerName string, payerAccountNumber string, payerBankCode string, narration string, rawPayload []byte) (queries.PartyWalletTransaction, error) {
	ret := _m.Called(ctx, walletID, amountKobo, transactionReference, payerName, payerAccountNumber, payerBankCode, narration, rawPayload)

	if len(ret) == 0 {
		panic("no return value specified for CreditWallet")
	}

	var r0 queries.PartyWalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string, string, string, []byte) (queries.PartyWalletTransaction, error)); ok {
		return rf(ctx, walletID, amountKobo, transactionReference, payerName, payerAccountNumber, payerBankCode, narration, rawPayload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string, string, string, []byte) queries.PartyWalletTransaction); ok {
		r0 = rf(ctx, walletID, amountKobo, transactionReference, payerName, payerAccountNumber, payerBankCode, narration, rawPayload)
	} else {
		r0 = ret.Get(0).(queries.PartyWalletTransaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, string, string, string, string, []byte) error); ok {
		r1 = rf(ctx, walletID, amountKobo, transactionReference, payerName, payerAccountNumber, payerBankCode, narration, rawPayload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteParty provides a mock function with given fields: ctx, id
func (_m *PartiesService) DeleteParty(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DepositAllowance provides a mock function with given fields: ctx, partyID, amountKobo
func (_m *PartiesService) DepositAllowance(ctx context.Context, partyID int64, amountKobo int64) (queries.Party, error) {
	ret := _m.Called(ctx, partyID, amountKobo)

	if len(ret) == 0 {
		panic("no return value specified for DepositAllowance")
	}

	var r0 queries.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (queries.Party, error)); ok {
		return rf(ctx, partyID, amountKobo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) queries.Party); ok {
		r0 = rf(ctx, partyID, amountKobo)
	} else {
		r0 = ret.Get(0).(queries.Party)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, partyID, amountKobo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGlobalSlotPrice provides a mock function with given fields: ctx
func (_m *PartiesService) GetGlobalSlotPrice(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalSlotPrice")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartyByID provides a mock function with given fields: ctx, id
func (_m *PartiesService) GetPartyByID(ctx context.Context, id int64) (queries.Party, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyByID")
	}

	var r0 queries.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (queries.Party, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) queries.Party); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(queries.Party)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartyByShortName provides a mock function with given fields: ctx, shortName
func (_m *PartiesService) GetPartyByShortName(ctx context.Context, shortName string) (queries.Party, error) {
	ret := _m.Called(ctx, shortName)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyByShortName")
	}

	var r0 queries.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (queries.Party, error)); ok {
		return rf(ctx, shortName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) queries.Party); ok {
		r0 = rf(ctx, shortName)
	} else {
		r0 = ret.Get(0).(queries.Party)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartySlotPrice provides a mock function with given fields: ctx, partyID
func (_m *PartiesService) GetPartySlotPrice(ctx context.Context, partyID int64) (int64, error) {
	ret := _m.Called(ctx, partyID)

	if len(ret) == 0 {
		panic("no return value specified for GetPartySlotPrice")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, partyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, partyID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, partyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartyWallet provides a mock function with given fields: ctx, partyID
func (_m *PartiesService) GetPartyWallet(ctx context.Context, partyID int64) (queries.PartyWallet, error) {
	ret := _m.Called(ctx, partyID)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyWallet")
	}

	var r0 queries.PartyWallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (queries.PartyWallet, error)); ok {
		return rf(ctx, partyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) queries.PartyWallet); ok {
		r0 = rf(ctx, partyID)
	} else {
		r0 = ret.Get(0).(queries.PartyWallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, partyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartyWalletTransactions provides a mock function with given fields: ctx, partyID, limit, offset
func (_m *PartiesService) GetPartyWalletTransactions(ctx context.Context, partyID int64, limit int32, offset int32) ([]queries.PartyWalletTransaction, error) {
	ret := _m.Called(ctx, partyID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyWalletTransactions")
	}

	var r0 []queries.PartyWalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int32, int32) ([]queries.PartyWalletTransaction, error)); ok {
		return rf(ctx, partyID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int32, int32) []queries.PartyWalletTransaction); ok {
		r0 = rf(ctx, partyID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.PartyWalletTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int32, int32) error); ok {
		r1 = rf(ctx, partyID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletByAccountReference provides a mock function with given fields: ctx, accountReference
func (_m *PartiesService) GetWalletByAccountReference(ctx context.Context, accountReference string) (queries.PartyWallet, error) {
	ret := _m.Called(ctx, accountReference)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletByAccountReference")
	}

	var r0 queries.PartyWallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (queries.PartyWallet, error)); ok {
		return rf(ctx, accountReference)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) queries.PartyWallet); ok {
		r0 = rf(ctx, accountReference)
	} else {
		r0 = ret.Get(0).(queries.PartyWallet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountReference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListParties provides a mock function with given fields: ctx
func (_m *PartiesService) ListParties(ctx context.Context) ([]queries.Party, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListParties")
	}

	var r0 []queries.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]queries.Party, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []queries.Party); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProvisionMissingWallets provides a mock function with given fields: ctx
func (_m *PartiesService) ProvisionMissingWallets(ctx context.Context) (int, int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProvisionMissingWallets")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateGlobalSlotPrice provides a mock function with given fields: ctx, priceKobo
func (_m *PartiesService) UpdateGlobalSlotPrice(ctx context.Context, priceKobo int64) (int64, error) {
	ret := _m.Called(ctx, priceKobo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGlobalSlotPrice")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, priceKobo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, priceKobo)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, priceKobo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateParty provides a mock function with given fields: ctx, id, shortName, name, logo, displayOrder
func (_m *PartiesService) UpdateParty(ctx context.Context, id int64, shortName string, name string, logo string, displayOrder int32) (queries.Party, error) {
	ret := _m.Called(ctx, id, shortName, name, logo, displayOrder)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParty")
	}

	var r0 queries.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, int32) (queries.Party, error)); ok {
		return rf(ctx, id, shortName, name, logo, displayOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, int32) queries.Party); ok {
		r0 = rf(ctx, id, shortName, name, logo, displayOrder)
	} else {
		r0 = ret.Get(0).(queries.Party)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, string, string, int32) error); ok {
		r1 = rf(ctx, id, shortName, name, logo, displayOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePartyDiscount provides a mock function with given fields: ctx, partyID, discountPercentage
func (_m *PartiesService) UpdatePartyDiscount(ctx context.Context, partyID int64, discountPercentage float64) (queries.Party, error) {
	ret := _m.Called(ctx, partyID, discountPercentage)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePartyDiscount")
	}

	var r0 queries.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64) (queries.Party, error)); ok {
		return rf(ctx, partyID, discountPercentage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64) queries.Party); ok {
		r0 = rf(ctx, partyID, discountPercentage)
	} else {
		r0 = ret.Get(0).(queries.Party)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, float64) error); ok {
		r1 = rf(ctx, partyID, discountPercentage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAgentPaymentAllocation provides a mock function with given fields: ctx, partyID, allowancesJSON
func (_m *PartiesService) UpdateAgentPaymentAllocation(ctx context.Context, partyID int64, allowancesJSON []byte) (queries.Party, error) {
	ret := _m.Called(ctx, partyID, allowancesJSON)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAgentPaymentAllocation")
	}

	var r0 queries.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []byte) (queries.Party, error)); ok {
		return rf(ctx, partyID, allowancesJSON)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []byte) queries.Party); ok {
		r0 = rf(ctx, partyID, allowancesJSON)
	} else {
		r0 = ret.Get(0).(queries.Party)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []byte) error); ok {
		r1 = rf(ctx, partyID, allowancesJSON)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawFromWallet provides a mock function with given fields: ctx, partyID, amountKobo, transactionReference, bankAccountNumber, bankCode, narration
func (_m *PartiesService) WithdrawFromWallet(ctx context.Context, partyID int64, amountKobo int64, transactionReference string, bankAccountNumber string, bankCode string, narration string) (queries.PartyWalletTransaction, error) {
	ret := _m.Called(ctx, partyID, amountKobo, transactionReference, bankAccountNumber, bankCode, narration)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawFromWallet")
	}

	var r0 queries.PartyWalletTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string, string) (queries.PartyWalletTransaction, error)); ok {
		return rf(ctx, partyID, amountKobo, transactionReference, bankAccountNumber, bankCode, narration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string, string, string) queries.PartyWalletTransaction); ok {
		r0 = rf(ctx, partyID, amountKobo, transactionReference, bankAccountNumber, bankCode, narration)
	} else {
		r0 = ret.Get(0).(queries.PartyWalletTransaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, string, string, string) error); ok {
		r1 = rf(ctx, partyID, amountKobo, transactionReference, bankAccountNumber, bankCode, narration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPartiesService creates a new instance of PartiesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartiesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartiesService {
	mock := &PartiesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
