// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	queries "free9ja/api/internal/db/queries"

	mock "github.com/stretchr/testify/mock"
)

// StateAssemblyConstituenciesService is an autogenerated mock type for the StateAssemblyConstituenciesService type
type StateAssemblyConstituenciesService struct {
	mock.Mock
}

// CreateStateAssemblyConstituency provides a mock function with given fields: ctx, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName
func (_m *StateAssemblyConstituenciesService) CreateStateAssemblyConstituency(ctx context.Context, name string, lgaID int32, lgaName string, stateID int32, stateName string, senatorialDistrictID int32, senatorialDistrictName string, federalConstituencyID int32, federalConstituencyName string) (queries.StateAssemblyConstituency, error) {
	ret := _m.Called(ctx, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)

	if len(ret) == 0 {
		panic("no return value specified for CreateStateAssemblyConstituency")
	}

	var r0 queries.StateAssemblyConstituency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, string, int32, string, int32, string, int32, string) (queries.StateAssemblyConstituency, error)); ok {
		return rf(ctx, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, string, int32, string, int32, string, int32, string) queries.StateAssemblyConstituency); ok {
		r0 = rf(ctx, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	} else {
		r0 = ret.Get(0).(queries.StateAssemblyConstituency)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, string, int32, string, int32, string, int32, string) error); ok {
		r1 = rf(ctx, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteStateAssemblyConstituency provides a mock function with given fields: ctx, id
func (_m *StateAssemblyConstituenciesService) DeleteStateAssemblyConstituency(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStateAssemblyConstituency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStateAssemblyConstituencies provides a mock function with given fields: ctx, stateID, federalConstituencyID
func (_m *StateAssemblyConstituenciesService) GetStateAssemblyConstituencies(ctx context.Context, stateID int32, federalConstituencyID int32) ([]queries.StateAssemblyConstituency, error) {
	ret := _m.Called(ctx, stateID, federalConstituencyID)

	if len(ret) == 0 {
		panic("no return value specified for GetStateAssemblyConstituencies")
	}

	var r0 []queries.StateAssemblyConstituency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]queries.StateAssemblyConstituency, error)); ok {
		return rf(ctx, stateID, federalConstituencyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []queries.StateAssemblyConstituency); ok {
		r0 = rf(ctx, stateID, federalConstituencyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]queries.StateAssemblyConstituency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, stateID, federalConstituencyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStateAssemblyConstituencyByID provides a mock function with given fields: ctx, id
func (_m *StateAssemblyConstituenciesService) GetStateAssemblyConstituencyByID(ctx context.Context, id int32) (queries.StateAssemblyConstituency, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStateAssemblyConstituencyByID")
	}

	var r0 queries.StateAssemblyConstituency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (queries.StateAssemblyConstituency, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) queries.StateAssemblyConstituency); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(queries.StateAssemblyConstituency)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStateAssemblyConstituency provides a mock function with given fields: ctx, id, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName
func (_m *StateAssemblyConstituenciesService) UpdateStateAssemblyConstituency(ctx context.Context, id int32, name string, lgaID int32, lgaName string, stateID int32, stateName string, senatorialDistrictID int32, senatorialDistrictName string, federalConstituencyID int32, federalConstituencyName string) (queries.StateAssemblyConstituency, error) {
	ret := _m.Called(ctx, id, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStateAssemblyConstituency")
	}

	var r0 queries.StateAssemblyConstituency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, int32, string, int32, string, int32, string, int32, string) (queries.StateAssemblyConstituency, error)); ok {
		return rf(ctx, id, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, int32, string, int32, string, int32, string, int32, string) queries.StateAssemblyConstituency); ok {
		r0 = rf(ctx, id, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	} else {
		r0 = ret.Get(0).(queries.StateAssemblyConstituency)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string, int32, string, int32, string, int32, string, int32, string) error); ok {
		r1 = rf(ctx, id, name, lgaID, lgaName, stateID, stateName, senatorialDistrictID, senatorialDistrictName, federalConstituencyID, federalConstituencyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStateAssemblyConstituenciesService creates a new instance of StateAssemblyConstituenciesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateAssemblyConstituenciesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateAssemblyConstituenciesService {
	mock := &StateAssemblyConstituenciesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
