-- +goose Up
CREATE TABLE occupations (
  id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  category VARCHAR(100) NOT NULL,
  name VARCHAR(100) UNIQUE NOT NULL
);

INSERT INTO occupations (category, name) VALUES
('Healthcare & Medical', 'Doctor'),
('Healthcare & Medical', 'Nurse'),
('Healthcare & Medical', 'Pharmacist'),
('Healthcare & Medical', 'Dentist'),
('Healthcare & Medical', 'Optometrist'),
('Healthcare & Medical', 'Physiotherapist'),
('Healthcare & Medical', 'Surgeon'),
('Healthcare & Medical', 'Medical Laboratory Scientist'),
('Healthcare & Medical', 'Paramedic'),
('Healthcare & Medical', 'Veterinarian'),
('Technology & Engineering', 'Software Engineer'),
('Technology & Engineering', 'Civil Engineer'),
('Technology & Engineering', 'Mechanical Engineer'),
('Technology & Engineering', 'Electrical Engineer'),
('Technology & Engineering', 'Data Analyst'),
('Technology & Engineering', 'Product Manager'),
('Technology & Engineering', 'Systems Administrator'),
('Technology & Engineering', 'Network Engineer'),
('Technology & Engineering', 'Cybersecurity Analyst'),
('Technology & Engineering', 'DevOps Engineer'),
('Technology & Engineering', 'UX/UI Designer'),
('Business, Finance & Administration', 'Accountant'),
('Business, Finance & Administration', 'Banker'),
('Business, Finance & Administration', 'Entrepreneur'),
('Business, Finance & Administration', 'Trader'),
('Business, Finance & Administration', 'Consultant'),
('Business, Finance & Administration', 'Marketer'),
('Business, Finance & Administration', 'Human Resources Manager'),
('Business, Finance & Administration', 'Real Estate Agent'),
('Business, Finance & Administration', 'Sales Representative'),
('Business, Finance & Administration', 'Economist'),
('Business, Finance & Administration', 'Business Analyst'),
('Business, Finance & Administration', 'Financial Advisor'),
('Business, Finance & Administration', 'Project Manager'),
('Education & Academia', 'Teacher'),
('Education & Academia', 'Lecturer / Professor'),
('Education & Academia', 'Researcher'),
('Education & Academia', 'Librarian'),
('Education & Academia', 'School Administrator'),
('Education & Academia', 'Academic Counselor'),
('Public Service, Law & Security', 'Civil Servant'),
('Public Service, Law & Security', 'Lawyer'),
('Public Service, Law & Security', 'Judge'),
('Public Service, Law & Security', 'Police Officer'),
('Public Service, Law & Security', 'Military Personnel'),
('Public Service, Law & Security', 'Firefighter'),
('Public Service, Law & Security', 'Diplomat'),
('Public Service, Law & Security', 'Customs Officer'),
('Public Service, Law & Security', 'Immigration Officer'),
('Public Service, Law & Security', 'Legal Assistant / Paralegal'),
('Public Service, Law & Security', 'Social Worker'),
('Trades, Crafts & Manual Labor', 'Mechanic'),
('Trades, Crafts & Manual Labor', 'Tailor / Fashion Designer'),
('Trades, Crafts & Manual Labor', 'Farmer'),
('Trades, Crafts & Manual Labor', 'Driver / Chauffeur'),
('Trades, Crafts & Manual Labor', 'Electrician'),
('Trades, Crafts & Manual Labor', 'Plumber'),
('Trades, Crafts & Manual Labor', 'Carpenter'),
('Trades, Crafts & Manual Labor', 'Welder'),
('Trades, Crafts & Manual Labor', 'Bricklayer'),
('Trades, Crafts & Manual Labor', 'Painter'),
('Trades, Crafts & Manual Labor', 'Cleaner / Janitor'),
('Trades, Crafts & Manual Labor', 'Factory Worker'),
('Trades, Crafts & Manual Labor', 'Logistics Coordinator'),
('Creative, Media & Arts', 'Journalist'),
('Creative, Media & Arts', 'Graphic Designer'),
('Creative, Media & Arts', 'Artist'),
('Creative, Media & Arts', 'Musician'),
('Creative, Media & Arts', 'Actor / Actress'),
('Creative, Media & Arts', 'Photographer'),
('Creative, Media & Arts', 'Videographer'),
('Creative, Media & Arts', 'Content Creator / Influencer'),
('Creative, Media & Arts', 'Writer / Author'),
('Creative, Media & Arts', 'Editor'),
('Creative, Media & Arts', 'Public Relations Specialist'),
('Hospitality & Personal Services', 'Chef / Baker'),
('Hospitality & Personal Services', 'Hairdresser / Barber'),
('Hospitality & Personal Services', 'Event Planner'),
('Hospitality & Personal Services', 'Hotel Manager'),
('Hospitality & Personal Services', 'Tour Guide'),
('Hospitality & Personal Services', 'Flight Attendant'),
('Hospitality & Personal Services', 'Customer Service Representative'),
('Hospitality & Personal Services', 'Makeup Artist'),
('Hospitality & Personal Services', 'Fitness Instructor / Personal Trainer'),
('Other / General', 'Student'),
('Other / General', 'Clergy (Pastor / Imam)'),
('Other / General', 'Athlete'),
('Other / General', 'Politician'),
('Other / General', 'Unemployed'),
('Other / General', 'Retiree');

-- +goose Down
DROP TABLE IF EXISTS occupations;

