-- +goose Up
CREATE TABLE c_regions (
  id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE c_subregions (
  id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  region_id SMALLINT NOT NULL REFERENCES c_regions(id) ON DELETE CASCADE
);

CREATE TABLE c_countries (
  id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  iso2 CHAR(2) NOT NULL,
  phonecode VARCHAR(10) NOT NULL,
  currency VARCHAR(5) NOT NULL,
  currency_symbol VARCHAR(10) NOT NULL,
  region_id SMALLINT,
  subregion_id SMALLINT,
  nationality VARCHAR(50) NOT NULL,
  latitude DECIMAL(10, 8) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude DECIMAL(11, 8) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  emoji VARCHAR(10) NOT NULL,
  emoji_unicode VARCHAR(20) NOT NULL
);

CREATE TABLE c_states (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  country_id SMALLINT NOT NULL,
  country_code VARCHAR(5) NOT NULL,
  latitude DECIMAL(10, 8) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude DECIMAL(11, 8) NOT NULL CHECK (longitude BETWEEN -180 AND 180)
);

CREATE TABLE c_cities (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  state_id SMALLINT NOT NULL,
  country_id SMALLINT NOT NULL,
  latitude DECIMAL(10, 8) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude DECIMAL(11, 8) NOT NULL CHECK (longitude BETWEEN -180 AND 180)
);


CREATE INDEX idx_c_countries_name ON c_countries(name);
CREATE INDEX idx_c_countries_region_id ON c_countries(region_id);
CREATE INDEX idx_c_countries_subregion_id ON c_countries(subregion_id);
CREATE INDEX idx_c_countries_latitude ON c_countries(latitude);
CREATE INDEX idx_c_countries_longitude ON c_countries(longitude);


CREATE INDEX idx_c_states_name ON c_states(name);
CREATE INDEX idx_c_states_country_id ON c_states(country_id);
CREATE INDEX idx_c_states_country_code ON c_states(country_code);
CREATE INDEX idx_c_states_latitude ON c_states(latitude);
CREATE INDEX idx_c_states_longitude ON c_states(longitude);


CREATE INDEX idx_c_cities_name ON c_cities(name);
CREATE INDEX idx_c_cities_state_id ON c_cities(state_id);
CREATE INDEX idx_c_cities_country_id ON c_cities(country_id);
CREATE INDEX idx_c_cities_latitude ON c_cities(latitude);
CREATE INDEX idx_c_cities_longitude ON c_cities(longitude);

-- +goose Down
DROP TABLE IF EXISTS c_cities;
DROP TABLE IF EXISTS c_states;
DROP TABLE IF EXISTS c_countries;
DROP TABLE IF EXISTS c_subregions;
DROP TABLE IF EXISTS c_regions;
