-- +goose Up
CREATE TABLE roles (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE role_permissions (
  id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE role_assigned_permissions (
  role_id SMALLINT REFERENCES roles(id) ON DELETE CASCADE,
  permission_id SMALLINT REFERENCES role_permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE user_roles (
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  role_id SMALLINT REFERENCES roles(id) ON DELETE CASCADE,
  role_code VARCHAR(50) NOT NULL,
  date_assigned TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  who_assigned_user_id BIGINT DEFAULT 0 NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);

-- Seed Default Permissions
INSERT INTO role_permissions (code, description) VALUES 
('manage_users', 'Can create, update, and delete users'),
('manage_parties', 'Can manage political parties'),
('manage_party_members', 'Can manage party members'),
('manage_elections', 'Can manage elections and candidates');

-- Seed Default Roles
INSERT INTO roles (id, code, name, description) VALUES 
(1, 'admin', 'Admin', 'Standard system administrator'),
(2, 'super_admin', 'Super Admin', 'Super administrator with full system access'),
(3, 'super_party_admin', 'Super Party Admin', 'Super administrator for a political party'),
(4, 'party_admin', 'Party Admin', 'Administrator for a political party');

-- Reset identity sequence
SELECT setval(pg_get_serial_sequence('roles', 'id'), coalesce(max(id), 1)) FROM roles;

-- Map Permissions to Roles
-- Super Admin and Admin get ALL role_permissions
INSERT INTO role_assigned_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, role_permissions p
WHERE r.code IN ('super_admin', 'admin');

-- Party Admin gets specific role_permissions (example)
INSERT INTO role_assigned_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, role_permissions p
WHERE r.code = 'super_party_admin' AND p.code IN ('manage_parties', 'manage_party_members', 'manage_elections');

-- +goose Down
DROP TABLE IF EXISTS role_assigned_permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS user_roles;
