-- +goose Up
CREATE TABLE IF NOT EXISTS senatorial_districts (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50),
    description TEXT,
    coalition_center VARCHAR(255),
    state_id INTEGER NOT NULL REFERENCES c_states(id) ON DELETE CASCADE,
    state_name VARCHAR(255) NOT NULL,
    federal_constituencies_count INTEGER DEFAULT 0,
    lgas_count INTEGER DEFAULT 0,
    state_constituencies_count INTEGER DEFAULT 0,
    wards_count INTEGER DEFAULT 0,
    polling_units_count INTEGER DEFAULT 0,
    status VARCHAR(50) DEFAULT 'active'
);

CREATE INDEX idx_senatorial_districts_name ON senatorial_districts (name);
CREATE INDEX idx_senatorial_districts_code ON senatorial_districts (code);
CREATE INDEX idx_senatorial_districts_state_id ON senatorial_districts (state_id);



-- SEED DATA START
INSERT INTO senatorial_districts (id, name, code, description, coalition_center, state_id, state_name, status) VALUES
(1, 'NIGER EAST', 'SD/076/NG ', NULL, NULL, 27, 'NIGER', 'active'),
(2, 'abia north', 'sd/001/ab', NULL, NULL, 1, 'ABIA', 'active'),
(5, 'adamawa north', 'sd/004/ad', NULL, NULL, 2, 'ADAMAWA', 'active'),
(6, 'adamawa south', 'sd/005/ad', NULL, NULL, 2, 'ADAMAWA', 'active'),
(7, 'ademawa central', 'sd/006/ad', NULL, NULL, 2, 'ADAMAWA', 'active'),
(8, 'anambra north', 'sd/010/an', NULL, NULL, 4, 'ANAMBRA', 'active'),
(9, 'anambra central', 'sd/011/an', NULL, NULL, 4, 'ANAMBRA', 'active'),
(10, 'anambra south', 'sd/012/an', NULL, NULL, 4, 'ANAMBRA', 'active'),
(13, 'akwa ibom south', 'sd/009/ak', NULL, NULL, 3, 'AKWA IBOM', 'active'),
(14, 'bauchi south', 'sd/013/ba', NULL, NULL, 5, 'BAUCHI', 'active'),
(15, 'bauchi central', 'sd/014/ba', NULL, NULL, 5, 'BAUCHI', 'active'),
(16, 'bauchi north', 'sd/015/ba', NULL, NULL, 5, 'BAUCHI', 'active'),
(17, 'bayelsa east', 'sd/016/by', NULL, NULL, 6, 'BAYELSA', 'active'),
(18, 'bayelsa central', 'sd/017/by', NULL, NULL, 6, 'BAYELSA', 'active'),
(19, 'bayelsa west', 'sd/018/by', NULL, NULL, 6, 'BAYELSA', 'active'),
(20, 'benue north east', 'sd/019/bn', NULL, NULL, 7, 'BENUE', 'active'),
(21, 'benue north west', 'sd/020/bn', NULL, NULL, 7, 'BENUE', 'active'),
(22, 'benue south', 'sd/021/bn', NULL, NULL, 7, 'BENUE', 'active'),
(25, 'borno south', 'sd/024/bo', NULL, NULL, 8, 'BORNO', 'active'),
(27, 'cross river central', 'sd/026/cr', NULL, NULL, 9, 'CROSS RIVER', 'active'),
(29, 'deltal central', 'sd/028/dt', NULL, NULL, 10, 'DELTA', 'active'),
(30, 'deltal north', 'sd/029/dt', NULL, NULL, 10, 'DELTA', 'active'),
(31, 'deltal south', 'sd/030/dt', NULL, NULL, 10, 'DELTA', 'active'),
(32, 'ebonyi north', 'sd/031/eb', NULL, NULL, 11, 'EBONYI', 'active'),
(33, 'ebonyi central', 'sd/032/eb', NULL, NULL, 11, 'EBONYI', 'active'),
(34, 'ebonyi south', 'sd/033/eb', NULL, NULL, 11, 'EBONYI', 'active'),
(35, 'edo central', 'sd/034/ed', NULL, NULL, 12, 'EDO', 'active'),
(36, 'edo north', 'sd/035/ed', NULL, NULL, 12, 'EDO', 'active'),
(37, 'edo south', 'sd/036/ed', NULL, NULL, 12, 'EDO', 'active'),
(38, 'ekiti north', 'sd/037/ek', NULL, NULL, 13, 'EKITI', 'active'),
(39, 'ekiti central', 'sd/038/ek', NULL, NULL, 13, 'EKITI', 'active'),
(40, 'ekiti south', 'sd/039/ek', NULL, NULL, 13, 'EKITI', 'active'),
(41, 'enugu east', 'sd/040/en', NULL, NULL, 14, 'ENUGU', 'active'),
(42, 'enugu west', 'sd/041/en', NULL, NULL, 14, 'ENUGU', 'active'),
(43, 'enugu north', 'sd/042/en', NULL, NULL, 14, 'ENUGU', 'active'),
(44, 'gombe central', 'sd/043/gm', NULL, NULL, 16, 'GOMBE', 'active'),
(45, 'gombe south', 'sd/044/gm', NULL, NULL, 16, 'GOMBE', 'active'),
(46, 'gombe north', 'sd/045/gm', NULL, NULL, 16, 'GOMBE', 'active'),
(47, 'imo east', 'sd/046/im', NULL, NULL, 17, 'IMO', 'active'),
(48, 'imo west', 'sd/047/im', NULL, NULL, 17, 'IMO', 'active'),
(49, 'imo north', 'sd/048/im', NULL, NULL, 17, 'IMO', 'active'),
(50, 'jigawa south-west', 'sd/049/jg', NULL, NULL, 18, 'JIGAWA', 'active'),
(51, 'jigawa north-east', 'sd/050/jg', NULL, NULL, 18, 'JIGAWA', 'active'),
(52, 'jigawa north-west', 'sd/051/jg', NULL, NULL, 18, 'JIGAWA', 'active'),
(53, 'kaduna north', 'sd/052/kd', NULL, NULL, 19, 'KADUNA', 'active'),
(54, 'kaduna central', 'sd/053/kd', NULL, NULL, 19, 'KADUNA', 'active'),
(55, 'kaduna south', 'sd/054/kd', NULL, NULL, 19, 'KADUNA', 'active'),
(56, 'kano central', 'sd/055/kn', NULL, NULL, 20, 'KANO', 'active'),
(59, 'katsina north', 'sd/058/kt', NULL, NULL, 21, 'KATSINA', 'active'),
(60, 'katsina south', 'sd/059/kt', NULL, NULL, 21, 'KATSINA', 'active'),
(61, 'katsina central', 'sd/060/kt', NULL, NULL, 21, 'KATSINA', 'active'),
(64, 'kebbi south', 'sd/063/kb', NULL, NULL, 22, 'KEBBI', 'active'),
(65, 'kogi central', 'sd/064/kg', NULL, NULL, 23, 'KOGI', 'active'),
(66, 'kogi east', 'sd/065/kg', NULL, NULL, 23, 'KOGI', 'active'),
(67, 'kogi west', 'sd/066/kg', NULL, NULL, 23, 'KOGI', 'active'),
(68, 'lagos central', 'sd/070/la', NULL, NULL, 25, 'LAGOS', 'active'),
(69, 'lagos east', 'sd/071/la', NULL, NULL, 25, 'LAGOS', 'active'),
(70, 'lagos west', 'sd/072/la', NULL, NULL, 25, 'LAGOS', 'active'),
(71, 'niger north', 'sd/077/ng', NULL, NULL, 27, 'NIGER', 'active'),
(72, 'niger south', 'sd/078/ng', NULL, NULL, 27, 'NIGER', 'active'),
(73, 'ogun central', 'sd/079/og', NULL, NULL, 28, 'OGUN', 'active'),
(74, 'ogun east', 'sd/080/og', NULL, NULL, 28, 'OGUN', 'active'),
(75, 'ogun west', 'sd/081/og', NULL, NULL, 28, 'OGUN', 'active'),
(76, 'ondo north', 'sd/082/od', NULL, NULL, 29, 'ONDO', 'active'),
(77, 'ondo central', 'sd/083/od', NULL, NULL, 29, 'ONDO', 'active'),
(78, 'ondo south', 'sd/084/od', NULL, NULL, 29, 'ONDO', 'active'),
(79, 'osun central', 'sd/085/os', NULL, NULL, 30, 'OSUN', 'active'),
(80, 'osun east', 'sd/086/os', NULL, NULL, 30, 'OSUN', 'active'),
(81, 'osun west', 'sd/087/os', NULL, NULL, 30, 'OSUN', 'active'),
(82, 'oyo central', 'sd/088/oy', NULL, NULL, 31, 'OYO', 'active'),
(83, 'oyo north', 'sd/089/oy', NULL, NULL, 31, 'OYO', 'active'),
(84, 'oyo south', 'sd/090/oy', NULL, NULL, 31, 'OYO', 'active'),
(86, 'plateau central', 'sd/092/pl', NULL, NULL, 32, 'PLATEAU', 'active'),
(88, 'rivers east', 'sd/094/rv', NULL, NULL, 33, 'RIVERS', 'active'),
(89, 'rivers south east', 'sd/095/rv', NULL, NULL, 33, 'RIVERS', 'active'),
(90, 'rivers west', 'sd/096/rv', NULL, NULL, 33, 'RIVERS', 'active'),
(91, 'sokoto east', 'sd/097/so', NULL, NULL, 34, 'SOKOTO', 'active'),
(92, 'sokoto north', 'sd/098/so', NULL, NULL, 34, 'SOKOTO', 'active'),
(93, 'sokoto south', 'sd/099/so', NULL, NULL, 34, 'SOKOTO', 'active'),
(94, 'taraba south', 'sd/100/tr', NULL, NULL, 35, 'TARABA', 'active'),
(95, 'taraba central', 'sd/101/tr', NULL, NULL, 35, 'TARABA', 'active'),
(96, 'taraba north', 'sd/102/tr', NULL, NULL, 35, 'TARABA', 'active'),
(98, 'yobe north', 'sd/104/yb', NULL, NULL, 36, 'YOBE', 'active'),
(101, 'zamfara central', 'sd/107/zf', NULL, NULL, 37, 'ZAMFARA', 'active'),
(103, 'fct', 'sd/109/fct', NULL, NULL, 15, 'FCT', 'active'),
(104, 'Kwara Central', 'SD/068/KW', NULL, NULL, 24, 'KWARA', 'active'),
(105, 'Kwara North', 'SD/067/KW', NULL, NULL, 24, 'KWARA', 'active'),
(106, 'Kwara South', 'SD/069/KW', NULL, NULL, 24, 'KWARA', 'active'),
(108, 'Nassarawa North', 'SD/073/NW', NULL, NULL, 26, 'NASARAWA', 'active'),
(109, 'Nassarawa West', 'SD/074/NW', NULL, NULL, 26, 'NASARAWA', 'active'),
(110, 'Nassarawa South', 'SD/075/NW', NULL, NULL, 26, 'NASARAWA', 'active'),
(111, 'abia south', 'sd/003/ab', NULL, NULL, 1, 'ABIA', 'active'),
(112, 'abia central', 'sd/002/ab', NULL, NULL, 1, 'ABIA', 'active'),
(113, 'borno central', 'sd/023/bo', NULL, NULL, 8, 'BORNO', 'active'),
(114, 'borno north', 'sd/022/bo', NULL, NULL, 8, 'BORNO', 'active'),
(115, 'akwa ibom north east', 'sd/007/ak', NULL, NULL, 3, 'AKWA IBOM', 'active'),
(117, 'akwa ibom north west', 'sd/008/ak', NULL, NULL, 3, 'AKWA IBOM', 'active'),
(118, 'cross river north', 'sd/025/cr', NULL, NULL, 9, 'CROSS RIVER', 'active'),
(119, 'cross river south', 'sd/027/cr', NULL, NULL, 9, 'CROSS RIVER', 'active'),
(120, 'kano north', 'sd/056/kn', NULL, NULL, 20, 'KANO', 'active'),
(121, 'kano south', 'sd/057/kn', NULL, NULL, 20, 'KANO', 'active'),
(122, 'kebbi north', 'sd/061/kb', NULL, NULL, 22, 'KEBBI', 'active'),
(123, 'kebbi central', 'sd/062/kb', NULL, NULL, 22, 'KEBBI', 'active'),
(124, 'plateau north', 'sd/093/pl', NULL, NULL, 32, 'PLATEAU', 'active'),
(125, 'plateau south', 'sd/091/pl', NULL, NULL, 32, 'PLATEAU', 'active'),
(126, 'yobe south', 'sd/105/yb', NULL, NULL, 36, 'YOBE', 'active'),
(127, 'yobe east', 'sd/103/yb', NULL, NULL, 36, 'YOBE', 'active'),
(128, 'zamfara north', 'sd/106/zf', NULL, NULL, 37, 'ZAMFARA', 'active'),
(129, 'zamfara west', 'sd/108/zf', NULL, NULL, 37, 'ZAMFARA', 'active')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, code = EXCLUDED.code, description = EXCLUDED.description, coalition_center = EXCLUDED.coalition_center, state_id = EXCLUDED.state_id, state_name = EXCLUDED.state_name, status = EXCLUDED.status;
-- SEED DATA END

-- +goose Down
DROP INDEX IF EXISTS idx_senatorial_districts_name;
DROP TABLE IF EXISTS senatorial_districts;
