-- +goose Up

CREATE TABLE party_chapters (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    party_id SMALLINT NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
    chapter_type VARCHAR(20) NOT NULL CHECK (chapter_type IN ('national', 'zonal', 'state', 'lga', 'ward')),
    country_id SMALLINT REFERENCES c_countries(id) ON DELETE CASCADE,
    zonal_id SMALLINT REFERENCES c_zones_nigeria(id) ON DELETE CASCADE,
    state_id SMALLINT REFERENCES c_states(id) ON DELETE CASCADE,
    lga_id INT REFERENCES lgas(id) ON DELETE CASCADE,
    ward_id INT REFERENCES wards(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Partial unique indexes to strictly enforce one chapter per entity level per party
CREATE UNIQUE INDEX idx_party_chapter_national ON party_chapters (party_id, country_id) WHERE chapter_type = 'national';
CREATE UNIQUE INDEX idx_party_chapter_zonal ON party_chapters (party_id, zonal_id) WHERE chapter_type = 'zonal';
CREATE UNIQUE INDEX idx_party_chapter_state ON party_chapters (party_id, state_id) WHERE chapter_type = 'state';
CREATE UNIQUE INDEX idx_party_chapter_lga ON party_chapters (party_id, lga_id) WHERE chapter_type = 'lga';
CREATE UNIQUE INDEX idx_party_chapter_ward ON party_chapters (party_id, ward_id) WHERE chapter_type = 'ward';

-- Listing / lookup indexes
CREATE INDEX idx_party_chapters_party_type ON party_chapters (party_id, chapter_type);
CREATE INDEX idx_party_chapters_state_id ON party_chapters (party_id, state_id);
CREATE INDEX idx_party_chapters_lga_id ON party_chapters (party_id, lga_id);
CREATE INDEX idx_party_chapters_ward_id ON party_chapters (party_id, ward_id);


CREATE TABLE party_membership (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    party_id SMALLINT NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
    chapter_id INT NOT NULL REFERENCES party_chapters(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, party_id, chapter_id)
);
-- Indexes for party membership queries
CREATE INDEX idx_party_membership_party_chapter ON party_membership(party_id, chapter_id);
CREATE INDEX idx_party_membership_party_user_status ON party_membership(party_id, user_id, status);
CREATE INDEX idx_party_membership_party_active_id ON party_membership(party_id, id DESC) WHERE status = 'active';


CREATE TABLE party_member_suspensions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    party_id SMALLINT NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    suspended_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reason TEXT,
    starts_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ends_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'lifted', 'expired')),
    lifted_at TIMESTAMPTZ,
    lifted_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    lift_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure a user can only have at most one active suspension per party at a time
CREATE UNIQUE INDEX idx_active_party_suspension ON party_member_suspensions (party_id, user_id) WHERE status = 'active';
CREATE INDEX idx_party_member_suspensions_party ON party_member_suspensions (party_id, id DESC) WHERE status = 'active';


CREATE TABLE party_member_milestones (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    party_id SMALLINT NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
    chapter_id INT REFERENCES party_chapters(id) ON DELETE SET NULL,
    milestone_type VARCHAR(50) NOT NULL, -- 'joined', 'left', 'appointed', 'promoted', 'donated', 'anniversary', 'custom'
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb, -- flexible attributes: { "position_id": 4, "amount_kobo": 5000000, etc. }
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- For member profile milestone timeline
CREATE INDEX idx_party_member_milestones_user ON party_member_milestones(user_id, id DESC);
-- For party or chapter activity feed
CREATE INDEX idx_party_member_milestones_party ON party_member_milestones(party_id, chapter_id, id DESC);



-- 1. Party Positions Catalog (Default pre-seeded positions + party custom positions)
CREATE TABLE party_positions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_type VARCHAR(20) NOT NULL DEFAULT 'default' CHECK (position_type IN ('default', 'custom')),
    name VARCHAR(150) NOT NULL,
    code VARCHAR(100) NOT NULL,
    party_id SMALLINT REFERENCES parties(id) ON DELETE CASCADE,
    description TEXT,
    allowed_levels VARCHAR(20)[] NOT NULL DEFAULT ARRAY['national', 'zonal', 'state', 'lga', 'ward'],
    rank_order SMALLINT NOT NULL DEFAULT 100,
    max_occupants SMALLINT NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_executive BOOLEAN NOT NULL DEFAULT true,
    category VARCHAR(50) NOT NULL DEFAULT 'executive',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_party_positions_party_code ON party_positions (party_id, code) WHERE party_id IS NOT NULL;
CREATE INDEX idx_party_positions_party_rank ON party_positions (party_id, rank_order ASC, name ASC);

-- 2. Party Position Assignments (Binds a member to a position within a chapter)
CREATE TABLE party_position_assignments (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    party_id SMALLINT NOT NULL REFERENCES parties(id) ON DELETE CASCADE,
    chapter_id INT NOT NULL REFERENCES party_chapters(id) ON DELETE CASCADE,
    position_id INT NOT NULL REFERENCES party_positions(id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    appointment_type VARCHAR(20) NOT NULL DEFAULT 'substantive' CHECK (appointment_type IN ('substantive', 'acting', 'caretaker', 'interim')),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'vacated', 'past')),
    tenure_start DATE NOT NULL DEFAULT CURRENT_DATE,
    tenure_end DATE,
    appointed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique index to prevent duplicate active assignment for the same position, chapter, and user
CREATE UNIQUE INDEX idx_unique_active_chapter_position_user ON party_position_assignments (chapter_id, position_id, user_id) WHERE status = 'active';
CREATE INDEX idx_pos_assign_chapter_pos_active ON party_position_assignments (chapter_id, position_id) WHERE status = 'active';
CREATE INDEX idx_pos_assign_party_user_active ON party_position_assignments (party_id, user_id) WHERE status IN ('active', 'suspended');
CREATE INDEX idx_pos_assign_chapter ON party_position_assignments (party_id, chapter_id, status);
CREATE INDEX idx_pos_assign_user ON party_position_assignments (user_id, status);
CREATE INDEX idx_pos_assign_position ON party_position_assignments (position_id);

-- 3. Pre-seed Default Party Positions
INSERT INTO party_positions (id, party_id, name, code, position_type, allowed_levels, rank_order, max_occupants, is_executive, category) VALUES
-- Executive (Leadership & Secretariat)
(1, NULL, 'Chairman', 'chairman', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 1, 1, true, 'executive'),
(2, NULL, 'Deputy Chairman', 'deputy_chairman', 'default', ARRAY['national', 'state', 'lga'], 2, 2, true, 'executive'),
(3, NULL, 'Vice Chairman', 'vice_chairman', 'default', ARRAY['national', 'zonal', 'state', 'ward'], 3, 6, true, 'executive'),
(4, NULL, 'Secretary', 'secretary', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 4, 1, true, 'executive'),
(5, NULL, 'Deputy Secretary', 'deputy_secretary', 'default', ARRAY['national', 'state'], 5, 1, true, 'executive'),
(6, NULL, 'Assistant Secretary', 'assistant_secretary', 'default', ARRAY['zonal', 'lga', 'ward'], 6, 1, true, 'executive'),

-- Operations (Party management, logistics, fieldwork)
(7, NULL, 'Organizing Secretary', 'organizing_secretary', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 7, 1, true, 'operations'),
(8, NULL, 'Assistant Organizing Secretary', 'assistant_organizing_secretary', 'default', ARRAY['national', 'state', 'lga', 'ward'], 8, 1, true, 'operations'),
(9, NULL, 'Welfare Secretary', 'welfare_secretary', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 9, 1, true, 'operations'),
(10, NULL, 'Protocol & Logistics Officer', 'protocol_logistics_officer', 'default', ARRAY['national', 'state', 'lga'], 10, 2, false, 'operations'),

-- Campaign & Elections (Voter-facing mobilization & electoral planning)
(11, NULL, 'Campaign Coordinator', 'campaign_coordinator', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 11, 2, false, 'campaign'),
(12, NULL, 'Director of Mobilization', 'director_mobilization', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 12, 1, false, 'campaign'),
(13, NULL, 'Election Planning Director', 'election_planning_director', 'default', ARRAY['national', 'state', 'lga'], 13, 1, false, 'campaign'),

-- Media & Communications (Publicity, press & digital reach)
(14, NULL, 'Publicity Secretary', 'publicity_secretary', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 14, 1, true, 'media'),
(15, NULL, 'Assistant Publicity Secretary', 'assistant_publicity_secretary', 'default', ARRAY['national', 'state', 'lga'], 15, 1, true, 'media'),
(16, NULL, 'New Media Director', 'new_media_director', 'default', ARRAY['national', 'state', 'lga'], 16, 1, false, 'media'),
(17, NULL, 'Head of Press', 'head_of_press', 'default', ARRAY['national', 'state'], 17, 1, false, 'media'),

-- Technology & ICT (Digital platforms, voter database, verification)
(18, NULL, 'Head of ICT', 'head_of_ict', 'default', ARRAY['national', 'state', 'lga'], 18, 1, false, 'technology'),
(19, NULL, 'Digital Strategy Lead', 'digital_strategy_lead', 'default', ARRAY['national', 'state'], 19, 1, false, 'technology'),
(20, NULL, 'Database / Portal Administrator', 'database_portal_admin', 'default', ARRAY['national', 'state', 'lga'], 20, 1, false, 'technology'),

-- Finance & Audit
(21, NULL, 'Treasurer', 'treasurer', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 21, 1, true, 'finance'),
(22, NULL, 'Financial Secretary', 'financial_secretary', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 22, 1, true, 'finance'),
(23, NULL, 'Auditor', 'auditor', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 23, 1, true, 'finance'),

-- Legal & Compliance
(24, NULL, 'Legal Adviser', 'legal_adviser', 'default', ARRAY['national', 'zonal', 'state', 'lga'], 24, 1, true, 'legal'),

-- Demographic & Special Wings
(25, NULL, 'Women Leader', 'women_leader', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 25, 1, true, 'wings'),
(26, NULL, 'Youth Leader', 'youth_leader', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 26, 1, true, 'wings'),
(27, NULL, 'Assistant Youth Leader', 'assistant_youth_leader', 'default', ARRAY['national', 'state', 'lga', 'ward'], 27, 1, true, 'wings'),
(28, NULL, 'Persons with Disabilities (PWD) Leader', 'pwd_leader', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 28, 1, true, 'wings'),

-- Advisory & Non-Portfolio Roles
(29, NULL, 'Ex-Officio Member', 'ex_officio', 'default', ARRAY['national', 'zonal', 'state', 'lga', 'ward'], 29, 6, false, 'advisory'),
(30, NULL, 'Special Adviser to Chairman', 'special_adviser_chairman', 'default', ARRAY['national', 'state'], 30, 3, false, 'advisory'),
(31, NULL, 'Elders Council Member', 'elders_council_member', 'default', ARRAY['national', 'state', 'lga'], 31, 10, false, 'advisory');

-- Resets the party_positions table id column to the max value + 1
SELECT setval(pg_get_serial_sequence('party_positions', 'id'), (SELECT MAX(id) FROM party_positions));

-- 4. Helper Function to Format Display Title with Geographic Context & Appointment Type
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION format_position_display_title(
    p_chapter_type VARCHAR,
    p_geo_name VARCHAR,
    p_position_name VARCHAR,
    p_appointment_type VARCHAR DEFAULT 'substantive'
) RETURNS VARCHAR AS $$
DECLARE
    v_prefix VARCHAR := '';
    v_title VARCHAR := '';
BEGIN
    IF p_appointment_type = 'acting' THEN
        v_prefix := 'Acting ';
    ELSIF p_appointment_type = 'caretaker' THEN
        v_prefix := 'Caretaker ';
    ELSIF p_appointment_type = 'interim' THEN
        v_prefix := 'Interim ';
    END IF;

    IF p_chapter_type = 'national' THEN
        v_title := 'National ' || p_position_name;
    ELSIF p_chapter_type = 'zonal' THEN
        v_title := COALESCE(p_geo_name || ' Zonal ', '') || p_position_name;
    ELSIF p_chapter_type = 'state' THEN
        v_title := COALESCE(p_geo_name || ' State ', '') || p_position_name;
    ELSIF p_chapter_type = 'lga' THEN
        v_title := COALESCE(p_geo_name || ' LGA ', '') || p_position_name;
    ELSIF p_chapter_type = 'ward' THEN
        v_title := COALESCE(p_geo_name || ' Ward ', '') || p_position_name;
    ELSE
        v_title := p_position_name;
    END IF;

    RETURN v_prefix || v_title;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
-- +goose StatementEnd

-- 5. Trigger to strictly enforce max_occupants for active position assignments
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION check_party_position_max_occupants()
RETURNS TRIGGER AS $$
DECLARE
    v_max SMALLINT;
    v_current BIGINT;
BEGIN
    IF NEW.status = 'active' THEN
        SELECT max_occupants INTO v_max 
        FROM party_positions 
        WHERE id = NEW.position_id;

        IF v_max > 0 THEN
            SELECT COUNT(*) INTO v_current 
            FROM party_position_assignments 
            WHERE chapter_id = NEW.chapter_id 
              AND position_id = NEW.position_id 
              AND status = 'active' 
              AND id != COALESCE(NEW.id, 0);

            IF v_current >= v_max THEN
                RAISE EXCEPTION 'Position has reached maximum occupancy of % for this chapter', v_max;
            END IF;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

-- Trigger: Enforce maximum occupants for active position assignments on create or update
CREATE TRIGGER trg_check_party_position_occupants
BEFORE INSERT OR UPDATE ON party_position_assignments
FOR EACH ROW EXECUTE FUNCTION check_party_position_max_occupants();

-- 6. Auto-provision National, Zonal, and State chapters on party creation
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION create_initial_party_chapters()
RETURNS TRIGGER AS $$
BEGIN
  -- 1. National Chapter (Nigeria = country_id 161)
  INSERT INTO party_chapters (party_id, chapter_type, country_id)
  VALUES (NEW.id, 'national', 161)
  ON CONFLICT (party_id, country_id) WHERE chapter_type = 'national' DO NOTHING;

  -- 2. Zonal Chapters (6 geopolitical zones)
  INSERT INTO party_chapters (party_id, chapter_type, zonal_id)
  SELECT NEW.id, 'zonal', id
  FROM c_zones_nigeria
  ON CONFLICT (party_id, zonal_id) WHERE chapter_type = 'zonal' DO NOTHING;

  -- 3. State Chapters (37 states including FCT)
  INSERT INTO party_chapters (party_id, chapter_type, state_id)
  SELECT NEW.id, 'state', id
  FROM c_states
  WHERE country_id = 161
  ON CONFLICT (party_id, state_id) WHERE chapter_type = 'state' DO NOTHING;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

-- Trigger: Automatically provision top-level chapters (National, 6 Zonal, 37 States) upon registering a new party
CREATE TRIGGER trg_create_party_top_chapters
AFTER INSERT ON parties
FOR EACH ROW
EXECUTE FUNCTION create_initial_party_chapters();

-- START backfill
-- One-time backfill: Provision National, Zonal, and State chapters for parties created prior to this migration
INSERT INTO party_chapters (party_id, chapter_type, country_id)
SELECT id, 'national', 161 FROM parties
ON CONFLICT (party_id, country_id) WHERE chapter_type = 'national' DO NOTHING;

INSERT INTO party_chapters (party_id, chapter_type, zonal_id)
SELECT p.id, 'zonal', z.id FROM parties p CROSS JOIN c_zones_nigeria z
ON CONFLICT (party_id, zonal_id) WHERE chapter_type = 'zonal' DO NOTHING;

INSERT INTO party_chapters (party_id, chapter_type, state_id)
SELECT p.id, 'state', s.id FROM parties p CROSS JOIN c_states s
WHERE s.country_id = 161
ON CONFLICT (party_id, state_id) WHERE chapter_type = 'state' DO NOTHING;
-- END backfill

-- +goose Down
DROP TRIGGER IF EXISTS trg_check_party_position_occupants ON party_position_assignments;
DROP FUNCTION IF EXISTS check_party_position_max_occupants();
DROP FUNCTION IF EXISTS format_position_display_title(VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP TRIGGER IF EXISTS trg_create_party_top_chapters ON parties;
DROP FUNCTION IF EXISTS create_initial_party_chapters();
DROP TABLE IF EXISTS party_position_assignments;
DROP TABLE IF EXISTS party_positions;
DROP TABLE IF EXISTS party_member_suspensions;
DROP TABLE IF EXISTS party_member_milestones;
DROP TABLE IF EXISTS party_membership;
DROP TABLE IF EXISTS party_chapters;
