-- +goose Up

-- Each user has exactly one reserved virtual account (wallet).
-- balance_kobo stores the ledger balance in Kobo (1 NGN = 100 Kobo)
-- to avoid floating-point precision issues with large Naira amounts.
CREATE TABLE user_wallets (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Monnify's unique reference for this reserved account
  account_reference     VARCHAR(100) UNIQUE NOT NULL,
  -- JSON array of {accountNumber, accountName, bankName, bankCode} issued by Monnify
  account_numbers       JSONB NOT NULL DEFAULT '[]',
  -- Ledger balance in Kobo (integer arithmetic, safe for billions of Naira)
  balance_kobo          BIGINT NOT NULL DEFAULT 0,
  currency_code         VARCHAR(10) NOT NULL DEFAULT 'NGN',
  -- active | suspended
  status                VARCHAR(50) NOT NULL DEFAULT 'active',
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

-- Immutable ledger of every credit/debit against a user wallet.
-- Each row corresponds to one Monnify webhook event or manual/payout transaction.
CREATE TABLE user_wallet_transactions (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id                BIGINT NOT NULL REFERENCES user_wallets(id) ON DELETE CASCADE,
  -- Monnify's transaction reference — unique, used for idempotency
  transaction_reference    VARCHAR(100) UNIQUE NOT NULL,
  -- 'credit' or 'debit'
  type                     VARCHAR(10) NOT NULL CHECK (type IN ('credit', 'debit')),
  amount_kobo              BIGINT NOT NULL CHECK (amount_kobo > 0),
  balance_after_kobo       BIGINT NOT NULL,
  payer_name               VARCHAR(255),
  payer_account_number     VARCHAR(20),
  payer_bank_code          VARCHAR(20),
  narration                TEXT,
  -- Full raw webhook payload stored for audit / dispute resolution
  raw_payload              JSONB,
  created_at               TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common lookups
CREATE INDEX idx_user_wallet_transactions_wallet_id ON user_wallet_transactions(wallet_id);
CREATE INDEX idx_user_wallet_transactions_created_at ON user_wallet_transactions(created_at DESC);

-- +goose Down
DROP INDEX IF EXISTS idx_user_wallet_transactions_created_at;
DROP INDEX IF EXISTS idx_user_wallet_transactions_wallet_id;
DROP TABLE IF EXISTS user_wallet_transactions;
DROP TABLE IF EXISTS user_wallets;
