# AWS Certificate Manager (ACM) Module
# This module requests an SSL/TLS certificate from AWS, creates the necessary DNS validation 
# records in Cloudflare, and waits for AWS to validate and issue the certificate.

terraform {
  # Define the required provider plugins and their version constraints for this module.
  required_providers {
    # HashiCorp AWS provider for managing AWS infrastructure (ACM certificates, etc.)
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
    # Cloudflare provider for managing DNS validation records
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = ">= 5.0"
    }
  }
}

# Request an SSL/TLS certificate from AWS Certificate Manager (ACM)
resource "aws_acm_certificate" "cert" {
  domain_name       = var.domain_name
  validation_method = "DNS" # Use DNS-based validation (requires adding CNAME records to DNS)

  # List of additional domains or wildcards to secure with the same certificate
  subject_alternative_names = var.subject_alternative_names

  lifecycle {
    # Crucial for zero-downtime certificate replacement: 
    # Create the new certificate before destroying the old one to avoid service interruption.
    create_before_destroy = true
  }

  tags = {
    Name        = "${var.website}-${var.environment}-cert"
    Environment = var.environment
  }
}

# Create DNS validation records in Cloudflare to prove domain ownership to AWS
resource "cloudflare_dns_record" "validation" {
  # Loop over all domain validation options returned by the ACM certificate.
  # Since there can be multiple domains (e.g., primary + SANs), we map each domain validation
  # option (dvo) by domain_name to construct individual Cloudflare DNS records.
  for_each = {
    for dvo in aws_acm_certificate.cert.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  zone_id = var.cloudflare_zone_id
  name    = each.value.name   # The validation record name generated by AWS
  content = each.value.record # The target validation value (usually a CNAME target)
  type    = each.value.type   # The record type (typically CNAME)
  ttl     = 60                # Low TTL of 60 seconds to speed up propagation and validation
}

# Wait for AWS ACM to verify the DNS validation records and issue the certificate.
# Note: This is a logical resource. It does not create real AWS infrastructure, but 
# acts as a gatekeeper that blocks downstream Terraform resources (like Load Balancers) 
# until the certificate is successfully validated and ready to use.
resource "aws_acm_certificate_validation" "cert" {
  certificate_arn = aws_acm_certificate.cert.arn

  # A list of validation FQDNs. Referencing the Cloudflare records creates a dependency 
  # ensuring that ACM validation is only attempted after the DNS records are created.
  validation_record_fqdns = [
    for record in cloudflare_dns_record.validation : record.name
  ]
}
