/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedPartyMembersRouteImport } from './routes/_authenticated/party-members'
import { Route as AuthenticatedPartiesRouteImport } from './routes/_authenticated/parties'
import { Route as AuthenticatedElectionsRouteImport } from './routes/_authenticated/elections'
import { Route as AuthenticatedBodiesRouteImport } from './routes/_authenticated/bodies'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet/index'
import { Route as AuthenticatedPartyMembersIndexRouteImport } from './routes/_authenticated/party-members/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedElectionsIndexRouteImport } from './routes/_authenticated/elections/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthenticatedPartyMembersAgentRouteImport } from './routes/_authenticated/party-members/agent'
import { Route as AuthenticatedPartyMembersAdminRouteImport } from './routes/_authenticated/party-members/admin'
import { Route as AuthenticatedElectionsInstancesRouteImport } from './routes/_authenticated/elections/instances'
import { Route as AuthenticatedApplicationsRejectedRouteImport } from './routes/_authenticated/applications/rejected'
import { Route as AuthenticatedApplicationsAcceptedRouteImport } from './routes/_authenticated/applications/accepted'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartyMembersRoute =
  AuthenticatedPartyMembersRouteImport.update({
    id: '/party-members',
    path: '/party-members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPartiesRoute = AuthenticatedPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedElectionsRoute = AuthenticatedElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBodiesRoute = AuthenticatedBodiesRouteImport.update({
  id: '/bodies',
  path: '/bodies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedPartyMembersIndexRoute =
  AuthenticatedPartyMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartyMembersRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedElectionsIndexRoute =
  AuthenticatedElectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedElectionsRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedPartyMembersAgentRoute =
  AuthenticatedPartyMembersAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => AuthenticatedPartyMembersRoute,
  } as any)
const AuthenticatedPartyMembersAdminRoute =
  AuthenticatedPartyMembersAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPartyMembersRoute,
  } as any)
const AuthenticatedElectionsInstancesRoute =
  AuthenticatedElectionsInstancesRouteImport.update({
    id: '/instances',
    path: '/instances',
    getParentRoute: () => AuthenticatedElectionsRoute,
  } as any)
const AuthenticatedApplicationsRejectedRoute =
  AuthenticatedApplicationsRejectedRouteImport.update({
    id: '/rejected',
    path: '/rejected',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedApplicationsAcceptedRoute =
  AuthenticatedApplicationsAcceptedRouteImport.update({
    id: '/accepted',
    path: '/accepted',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/bodies': typeof AuthenticatedBodiesRoute
  '/elections': typeof AuthenticatedElectionsRouteWithChildren
  '/parties': typeof AuthenticatedPartiesRoute
  '/party-members': typeof AuthenticatedPartyMembersRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/applications/accepted': typeof AuthenticatedApplicationsAcceptedRoute
  '/applications/rejected': typeof AuthenticatedApplicationsRejectedRoute
  '/elections/instances': typeof AuthenticatedElectionsInstancesRoute
  '/party-members/admin': typeof AuthenticatedPartyMembersAdminRoute
  '/party-members/agent': typeof AuthenticatedPartyMembersAgentRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/elections/': typeof AuthenticatedElectionsIndexRoute
  '/home/': typeof AuthenticatedHomeIndexRoute
  '/party-members/': typeof AuthenticatedPartyMembersIndexRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bodies': typeof AuthenticatedBodiesRoute
  '/parties': typeof AuthenticatedPartiesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/applications/accepted': typeof AuthenticatedApplicationsAcceptedRoute
  '/applications/rejected': typeof AuthenticatedApplicationsRejectedRoute
  '/elections/instances': typeof AuthenticatedElectionsInstancesRoute
  '/party-members/admin': typeof AuthenticatedPartyMembersAdminRoute
  '/party-members/agent': typeof AuthenticatedPartyMembersAgentRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/elections': typeof AuthenticatedElectionsIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/party-members': typeof AuthenticatedPartyMembersIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/bodies': typeof AuthenticatedBodiesRoute
  '/_authenticated/elections': typeof AuthenticatedElectionsRouteWithChildren
  '/_authenticated/parties': typeof AuthenticatedPartiesRoute
  '/_authenticated/party-members': typeof AuthenticatedPartyMembersRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/_authenticated/applications/accepted': typeof AuthenticatedApplicationsAcceptedRoute
  '/_authenticated/applications/rejected': typeof AuthenticatedApplicationsRejectedRoute
  '/_authenticated/elections/instances': typeof AuthenticatedElectionsInstancesRoute
  '/_authenticated/party-members/admin': typeof AuthenticatedPartyMembersAdminRoute
  '/_authenticated/party-members/agent': typeof AuthenticatedPartyMembersAgentRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/elections/': typeof AuthenticatedElectionsIndexRoute
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/party-members/': typeof AuthenticatedPartyMembersIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/bodies'
    | '/elections'
    | '/parties'
    | '/party-members'
    | '/users'
    | '/wallet'
    | '/applications/accepted'
    | '/applications/rejected'
    | '/elections/instances'
    | '/party-members/admin'
    | '/party-members/agent'
    | '/applications/'
    | '/elections/'
    | '/home/'
    | '/party-members/'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bodies'
    | '/parties'
    | '/users'
    | '/applications/accepted'
    | '/applications/rejected'
    | '/elections/instances'
    | '/party-members/admin'
    | '/party-members/agent'
    | '/applications'
    | '/elections'
    | '/home'
    | '/party-members'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/applications'
    | '/_authenticated/bodies'
    | '/_authenticated/elections'
    | '/_authenticated/parties'
    | '/_authenticated/party-members'
    | '/_authenticated/users'
    | '/_authenticated/wallet'
    | '/_authenticated/applications/accepted'
    | '/_authenticated/applications/rejected'
    | '/_authenticated/elections/instances'
    | '/_authenticated/party-members/admin'
    | '/_authenticated/party-members/agent'
    | '/_authenticated/applications/'
    | '/_authenticated/elections/'
    | '/_authenticated/home/'
    | '/_authenticated/party-members/'
    | '/_authenticated/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/party-members': {
      id: '/_authenticated/party-members'
      path: '/party-members'
      fullPath: '/party-members'
      preLoaderRoute: typeof AuthenticatedPartyMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parties': {
      id: '/_authenticated/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AuthenticatedPartiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/elections': {
      id: '/_authenticated/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof AuthenticatedElectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bodies': {
      id: '/_authenticated/bodies'
      path: '/bodies'
      fullPath: '/bodies'
      preLoaderRoute: typeof AuthenticatedBodiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/party-members/': {
      id: '/_authenticated/party-members/'
      path: '/'
      fullPath: '/party-members/'
      preLoaderRoute: typeof AuthenticatedPartyMembersIndexRouteImport
      parentRoute: typeof AuthenticatedPartyMembersRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/elections/': {
      id: '/_authenticated/elections/'
      path: '/'
      fullPath: '/elections/'
      preLoaderRoute: typeof AuthenticatedElectionsIndexRouteImport
      parentRoute: typeof AuthenticatedElectionsRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/party-members/agent': {
      id: '/_authenticated/party-members/agent'
      path: '/agent'
      fullPath: '/party-members/agent'
      preLoaderRoute: typeof AuthenticatedPartyMembersAgentRouteImport
      parentRoute: typeof AuthenticatedPartyMembersRoute
    }
    '/_authenticated/party-members/admin': {
      id: '/_authenticated/party-members/admin'
      path: '/admin'
      fullPath: '/party-members/admin'
      preLoaderRoute: typeof AuthenticatedPartyMembersAdminRouteImport
      parentRoute: typeof AuthenticatedPartyMembersRoute
    }
    '/_authenticated/elections/instances': {
      id: '/_authenticated/elections/instances'
      path: '/instances'
      fullPath: '/elections/instances'
      preLoaderRoute: typeof AuthenticatedElectionsInstancesRouteImport
      parentRoute: typeof AuthenticatedElectionsRoute
    }
    '/_authenticated/applications/rejected': {
      id: '/_authenticated/applications/rejected'
      path: '/rejected'
      fullPath: '/applications/rejected'
      preLoaderRoute: typeof AuthenticatedApplicationsRejectedRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/applications/accepted': {
      id: '/_authenticated/applications/accepted'
      path: '/accepted'
      fullPath: '/applications/accepted'
      preLoaderRoute: typeof AuthenticatedApplicationsAcceptedRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsAcceptedRoute: typeof AuthenticatedApplicationsAcceptedRoute
  AuthenticatedApplicationsRejectedRoute: typeof AuthenticatedApplicationsRejectedRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsAcceptedRoute:
      AuthenticatedApplicationsAcceptedRoute,
    AuthenticatedApplicationsRejectedRoute:
      AuthenticatedApplicationsRejectedRoute,
    AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedElectionsRouteChildren {
  AuthenticatedElectionsInstancesRoute: typeof AuthenticatedElectionsInstancesRoute
  AuthenticatedElectionsIndexRoute: typeof AuthenticatedElectionsIndexRoute
}

const AuthenticatedElectionsRouteChildren: AuthenticatedElectionsRouteChildren =
  {
    AuthenticatedElectionsInstancesRoute: AuthenticatedElectionsInstancesRoute,
    AuthenticatedElectionsIndexRoute: AuthenticatedElectionsIndexRoute,
  }

const AuthenticatedElectionsRouteWithChildren =
  AuthenticatedElectionsRoute._addFileChildren(
    AuthenticatedElectionsRouteChildren,
  )

interface AuthenticatedPartyMembersRouteChildren {
  AuthenticatedPartyMembersAdminRoute: typeof AuthenticatedPartyMembersAdminRoute
  AuthenticatedPartyMembersAgentRoute: typeof AuthenticatedPartyMembersAgentRoute
  AuthenticatedPartyMembersIndexRoute: typeof AuthenticatedPartyMembersIndexRoute
}

const AuthenticatedPartyMembersRouteChildren: AuthenticatedPartyMembersRouteChildren =
  {
    AuthenticatedPartyMembersAdminRoute: AuthenticatedPartyMembersAdminRoute,
    AuthenticatedPartyMembersAgentRoute: AuthenticatedPartyMembersAgentRoute,
    AuthenticatedPartyMembersIndexRoute: AuthenticatedPartyMembersIndexRoute,
  }

const AuthenticatedPartyMembersRouteWithChildren =
  AuthenticatedPartyMembersRoute._addFileChildren(
    AuthenticatedPartyMembersRouteChildren,
  )

interface AuthenticatedWalletRouteChildren {
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedWalletRouteChildren: AuthenticatedWalletRouteChildren = {
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedWalletRouteWithChildren =
  AuthenticatedWalletRoute._addFileChildren(AuthenticatedWalletRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedBodiesRoute: typeof AuthenticatedBodiesRoute
  AuthenticatedElectionsRoute: typeof AuthenticatedElectionsRouteWithChildren
  AuthenticatedPartiesRoute: typeof AuthenticatedPartiesRoute
  AuthenticatedPartyMembersRoute: typeof AuthenticatedPartyMembersRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRouteWithChildren
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedBodiesRoute: AuthenticatedBodiesRoute,
  AuthenticatedElectionsRoute: AuthenticatedElectionsRouteWithChildren,
  AuthenticatedPartiesRoute: AuthenticatedPartiesRoute,
  AuthenticatedPartyMembersRoute: AuthenticatedPartyMembersRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRouteWithChildren,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
