// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (
    module, action, actor_id, actor_role, entity_type, entity_id, old_values, new_values, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, module, action, actor_id, actor_role, entity_type, entity_id, old_values, new_values, ip_address, user_agent, created_at
`

type InsertAuditLogParams struct {
	Module     pgtype.Text `json:"module"`
	Action     string      `json:"action"`
	ActorID    int64       `json:"actor_id"`
	ActorRole  pgtype.Text `json:"actor_role"`
	EntityType string      `json:"entity_type"`
	EntityID   string      `json:"entity_id"`
	OldValues  []byte      `json:"old_values"`
	NewValues  []byte      `json:"new_values"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.Module,
		arg.Action,
		arg.ActorID,
		arg.ActorRole,
		arg.EntityType,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Action,
		&i.ActorID,
		&i.ActorRole,
		&i.EntityType,
		&i.EntityID,
		&i.OldValues,
		&i.NewValues,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
