// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocks.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockUser = `-- name: BlockUser :one

INSERT INTO user_blocks (
  blocker_id,
  blocked_user_id,
  created_at
) VALUES (
  $1, $2, NOW()
)
ON CONFLICT (blocker_id, blocked_user_id) DO UPDATE
SET created_at = EXCLUDED.created_at
RETURNING id, blocker_id, blocked_user_id, created_at
`

type BlockUserParams struct {
	BlockerID     int64 `json:"blocker_id"`
	BlockedUserID int64 `json:"blocked_user_id"`
}

// ========================================================
// USER BLOCKS
// ========================================================
func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) (UserBlock, error) {
	row := q.db.QueryRow(ctx, blockUser, arg.BlockerID, arg.BlockedUserID)
	var i UserBlock
	err := row.Scan(
		&i.ID,
		&i.BlockerID,
		&i.BlockedUserID,
		&i.CreatedAt,
	)
	return i, err
}

const blockUserByParty = `-- name: BlockUserByParty :one

INSERT INTO party_user_blocks (
  party_id,
  blocked_user_id,
  blocked_by_user_id,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, NOW(), NOW()
)
ON CONFLICT (party_id, blocked_user_id) DO UPDATE
SET
  blocked_by_user_id = EXCLUDED.blocked_by_user_id,
  updated_at = NOW()
RETURNING id, party_id, blocked_user_id, blocked_by_user_id, created_at, updated_at
`

type BlockUserByPartyParams struct {
	PartyID         int16       `json:"party_id"`
	BlockedUserID   int64       `json:"blocked_user_id"`
	BlockedByUserID pgtype.Int8 `json:"blocked_by_user_id"`
}

// ========================================================
// PARTY USER BLOCKS
// ========================================================
func (q *Queries) BlockUserByParty(ctx context.Context, arg BlockUserByPartyParams) (PartyUserBlock, error) {
	row := q.db.QueryRow(ctx, blockUserByParty, arg.PartyID, arg.BlockedUserID, arg.BlockedByUserID)
	var i PartyUserBlock
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.BlockedUserID,
		&i.BlockedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlockedPartyIDsForUser = `-- name: GetBlockedPartyIDsForUser :many
SELECT party_id
FROM party_user_blocks
WHERE blocked_user_id = $1
`

func (q *Queries) GetBlockedPartyIDsForUser(ctx context.Context, blockedUserID int64) ([]int16, error) {
	rows, err := q.db.Query(ctx, getBlockedPartyIDsForUser, blockedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var party_id int16
		if err := rows.Scan(&party_id); err != nil {
			return nil, err
		}
		items = append(items, party_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockedUserIDsForUser = `-- name: GetBlockedUserIDsForUser :many
SELECT blocked_user_id
FROM user_blocks
WHERE blocker_id = $1
`

// Helper for filtering feeds / search results
func (q *Queries) GetBlockedUserIDsForUser(ctx context.Context, blockerID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getBlockedUserIDsForUser, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var blocked_user_id int64
		if err := rows.Scan(&blocked_user_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserBlocked = `-- name: IsUserBlocked :one
SELECT EXISTS (
  SELECT 1 FROM user_blocks
  WHERE blocker_id = $1 AND blocked_user_id = $2
) AS is_blocked
`

type IsUserBlockedParams struct {
	BlockerID     int64 `json:"blocker_id"`
	BlockedUserID int64 `json:"blocked_user_id"`
}

// Checks if blocker_id has blocked blocked_user_id
func (q *Queries) IsUserBlocked(ctx context.Context, arg IsUserBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBlocked, arg.BlockerID, arg.BlockedUserID)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const isUserBlockedBidirectional = `-- name: IsUserBlockedBidirectional :one
SELECT EXISTS (
  SELECT 1 FROM user_blocks
  WHERE (blocker_id = $1 AND blocked_user_id = $2)
     OR (blocker_id = $2 AND blocked_user_id = $1)
) AS is_blocked
`

type IsUserBlockedBidirectionalParams struct {
	BlockerID     int64 `json:"blocker_id"`
	BlockedUserID int64 `json:"blocked_user_id"`
}

// Useful for chat/DMs/feed: true if either user has blocked the other
func (q *Queries) IsUserBlockedBidirectional(ctx context.Context, arg IsUserBlockedBidirectionalParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBlockedBidirectional, arg.BlockerID, arg.BlockedUserID)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const isUserBlockedByParty = `-- name: IsUserBlockedByParty :one
SELECT EXISTS (
  SELECT 1 FROM party_user_blocks
  WHERE party_id = $1 AND blocked_user_id = $2
) AS is_blocked
`

type IsUserBlockedByPartyParams struct {
	PartyID       int16 `json:"party_id"`
	BlockedUserID int64 `json:"blocked_user_id"`
}

func (q *Queries) IsUserBlockedByParty(ctx context.Context, arg IsUserBlockedByPartyParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBlockedByParty, arg.PartyID, arg.BlockedUserID)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const listBlockedUsersByParty = `-- name: ListBlockedUsersByParty :many
SELECT
  pub.id,
  pub.party_id,
  pub.blocked_user_id,
  pub.blocked_by_user_id,
  pub.created_at,
  pub.updated_at,
  u.username AS blocked_username,
  u.first_name AS blocked_first_name,
  u.last_name AS blocked_last_name,
  u.avatar AS blocked_avatar,
  admin.username AS admin_username
FROM party_user_blocks pub
JOIN users u ON u.id = pub.blocked_user_id
LEFT JOIN users admin ON admin.id = pub.blocked_by_user_id
WHERE pub.party_id = $1::smallint
  AND ($2::bigint IS NULL OR pub.id < $2::bigint)
ORDER BY pub.id DESC
LIMIT $3::int
`

type ListBlockedUsersByPartyParams struct {
	PartyID  int16       `json:"party_id"`
	Cursor   pgtype.Int8 `json:"cursor"`
	LimitNum int32       `json:"limit_num"`
}

type ListBlockedUsersByPartyRow struct {
	ID               int64              `json:"id"`
	PartyID          int16              `json:"party_id"`
	BlockedUserID    int64              `json:"blocked_user_id"`
	BlockedByUserID  pgtype.Int8        `json:"blocked_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BlockedUsername  pgtype.Text        `json:"blocked_username"`
	BlockedFirstName pgtype.Text        `json:"blocked_first_name"`
	BlockedLastName  pgtype.Text        `json:"blocked_last_name"`
	BlockedAvatar    pgtype.Text        `json:"blocked_avatar"`
	AdminUsername    pgtype.Text        `json:"admin_username"`
}

func (q *Queries) ListBlockedUsersByParty(ctx context.Context, arg ListBlockedUsersByPartyParams) ([]ListBlockedUsersByPartyRow, error) {
	rows, err := q.db.Query(ctx, listBlockedUsersByParty, arg.PartyID, arg.Cursor, arg.LimitNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedUsersByPartyRow
	for rows.Next() {
		var i ListBlockedUsersByPartyRow
		if err := rows.Scan(
			&i.ID,
			&i.PartyID,
			&i.BlockedUserID,
			&i.BlockedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockedUsername,
			&i.BlockedFirstName,
			&i.BlockedLastName,
			&i.BlockedAvatar,
			&i.AdminUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockedUsersByUser = `-- name: ListBlockedUsersByUser :many
SELECT
  ub.id,
  ub.blocker_id,
  ub.blocked_user_id,
  ub.created_at,
  u.username,
  u.first_name,
  u.last_name,
  u.avatar
FROM user_blocks ub
JOIN users u ON u.id = ub.blocked_user_id
WHERE ub.blocker_id = $1
ORDER BY ub.created_at DESC
LIMIT $2 OFFSET $3
`

type ListBlockedUsersByUserParams struct {
	BlockerID int64 `json:"blocker_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListBlockedUsersByUserRow struct {
	ID            int64              `json:"id"`
	BlockerID     int64              `json:"blocker_id"`
	BlockedUserID int64              `json:"blocked_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Username      pgtype.Text        `json:"username"`
	FirstName     pgtype.Text        `json:"first_name"`
	LastName      pgtype.Text        `json:"last_name"`
	Avatar        pgtype.Text        `json:"avatar"`
}

func (q *Queries) ListBlockedUsersByUser(ctx context.Context, arg ListBlockedUsersByUserParams) ([]ListBlockedUsersByUserRow, error) {
	rows, err := q.db.Query(ctx, listBlockedUsersByUser, arg.BlockerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedUsersByUserRow
	for rows.Next() {
		var i ListBlockedUsersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BlockerID,
			&i.BlockedUserID,
			&i.CreatedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM user_blocks
WHERE blocker_id = $1 AND blocked_user_id = $2
`

type UnblockUserParams struct {
	BlockerID     int64 `json:"blocker_id"`
	BlockedUserID int64 `json:"blocked_user_id"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedUserID)
	return err
}

const unblockUserByID = `-- name: UnblockUserByID :exec
DELETE FROM user_blocks
WHERE id = $1 AND blocker_id = $2
`

type UnblockUserByIDParams struct {
	ID        int64 `json:"id"`
	BlockerID int64 `json:"blocker_id"`
}

func (q *Queries) UnblockUserByID(ctx context.Context, arg UnblockUserByIDParams) error {
	_, err := q.db.Exec(ctx, unblockUserByID, arg.ID, arg.BlockerID)
	return err
}

const unblockUserByParty = `-- name: UnblockUserByParty :exec
DELETE FROM party_user_blocks
WHERE party_id = $1 AND blocked_user_id = $2
`

type UnblockUserByPartyParams struct {
	PartyID       int16 `json:"party_id"`
	BlockedUserID int64 `json:"blocked_user_id"`
}

func (q *Queries) UnblockUserByParty(ctx context.Context, arg UnblockUserByPartyParams) error {
	_, err := q.db.Exec(ctx, unblockUserByParty, arg.PartyID, arg.BlockedUserID)
	return err
}

const unblockUserByPartyBlockID = `-- name: UnblockUserByPartyBlockID :exec
DELETE FROM party_user_blocks
WHERE id = $1 AND party_id = $2
`

type UnblockUserByPartyBlockIDParams struct {
	ID      int64 `json:"id"`
	PartyID int16 `json:"party_id"`
}

func (q *Queries) UnblockUserByPartyBlockID(ctx context.Context, arg UnblockUserByPartyBlockIDParams) error {
	_, err := q.db.Exec(ctx, unblockUserByPartyBlockID, arg.ID, arg.PartyID)
	return err
}
