// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: countries.sql

package queries

import (
	"context"
)

const getCityByID = `-- name: GetCityByID :one
SELECT id, name FROM c_cities
WHERE id = $1 and state_id = $2 LIMIT 1
`

type GetCityByIDParams struct {
	ID      int32 `json:"id"`
	StateID int16 `json:"state_id"`
}

type GetCityByIDRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetCityByID(ctx context.Context, arg GetCityByIDParams) (GetCityByIDRow, error) {
	row := q.db.QueryRow(ctx, getCityByID, arg.ID, arg.StateID)
	var i GetCityByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, name, iso2  FROM c_countries
WHERE id = $1 LIMIT 1
`

type GetCountryByIDRow struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
	Iso2 string `json:"iso2"`
}

func (q *Queries) GetCountryByID(ctx context.Context, id int16) (GetCountryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCountryByID, id)
	var i GetCountryByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Iso2)
	return i, err
}

const getStateByID = `-- name: GetStateByID :one
SELECT id, name FROM c_states
WHERE id = $1 and country_id = $2 LIMIT 1
`

type GetStateByIDParams struct {
	ID        int16 `json:"id"`
	CountryID int16 `json:"country_id"`
}

type GetStateByIDRow struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetStateByID(ctx context.Context, arg GetStateByIDParams) (GetStateByIDRow, error) {
	row := q.db.QueryRow(ctx, getStateByID, arg.ID, arg.CountryID)
	var i GetStateByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
