// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: countries.sql

package queries

import (
	"context"
)

const getCitiesByStateID = `-- name: GetCitiesByStateID :many
SELECT id, name FROM c_cities
WHERE state_id = $1
ORDER BY name ASC
`

type GetCitiesByStateIDRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetCitiesByStateID(ctx context.Context, stateID int16) ([]GetCitiesByStateIDRow, error) {
	rows, err := q.db.Query(ctx, getCitiesByStateID, stateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCitiesByStateIDRow
	for rows.Next() {
		var i GetCitiesByStateIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCityByID = `-- name: GetCityByID :one
SELECT id, name FROM c_cities
WHERE id = $1 and state_id = $2 LIMIT 1
`

type GetCityByIDParams struct {
	ID      int32 `json:"id"`
	StateID int16 `json:"state_id"`
}

type GetCityByIDRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetCityByID(ctx context.Context, arg GetCityByIDParams) (GetCityByIDRow, error) {
	row := q.db.QueryRow(ctx, getCityByID, arg.ID, arg.StateID)
	var i GetCityByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, name, iso2  FROM c_countries
WHERE id = $1 LIMIT 1
`

type GetCountryByIDRow struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
	Iso2 string `json:"iso2"`
}

func (q *Queries) GetCountryByID(ctx context.Context, id int16) (GetCountryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCountryByID, id)
	var i GetCountryByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Iso2)
	return i, err
}

const getStateByID = `-- name: GetStateByID :one
SELECT id, name FROM c_states
WHERE id = $1 and country_id = $2 LIMIT 1
`

type GetStateByIDParams struct {
	ID        int16 `json:"id"`
	CountryID int16 `json:"country_id"`
}

type GetStateByIDRow struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetStateByID(ctx context.Context, arg GetStateByIDParams) (GetStateByIDRow, error) {
	row := q.db.QueryRow(ctx, getStateByID, arg.ID, arg.CountryID)
	var i GetStateByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getStatesByCountryID = `-- name: GetStatesByCountryID :many
SELECT id, name FROM c_states
WHERE country_id = $1
ORDER BY name ASC
`

type GetStatesByCountryIDRow struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetStatesByCountryID(ctx context.Context, countryID int16) ([]GetStatesByCountryIDRow, error) {
	rows, err := q.db.Query(ctx, getStatesByCountryID, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatesByCountryIDRow
	for rows.Next() {
		var i GetStatesByCountryIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountries = `-- name: ListCountries :many
SELECT id, name, iso2, phonecode FROM c_countries
ORDER BY name ASC
`

type ListCountriesRow struct {
	ID        int16  `json:"id"`
	Name      string `json:"name"`
	Iso2      string `json:"iso2"`
	Phonecode string `json:"phonecode"`
}

func (q *Queries) ListCountries(ctx context.Context) ([]ListCountriesRow, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCountriesRow
	for rows.Next() {
		var i ListCountriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Iso2,
			&i.Phonecode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
