// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: election_groups.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createElectionGroup = `-- name: CreateElectionGroup :one
INSERT INTO election_groups (name, rank, elections_count, states_count, election_date, senatorial_districts_count, federal_constituencies_count, lgas_count, state_constituencies_count, wards_count, polling_units_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, rank, elections_count, states_count, senatorial_districts_count, federal_constituencies_count, lgas_count, state_constituencies_count, wards_count, polling_units_count, state_supervisors_count, unique_state_supervisors_count, lga_supervisors_count, unique_lga_supervisors_count, ward_supervisors_count, unique_ward_supervisors_count, applications_count, accepted_applications_count, rejected_applications_count, ward_supervisor_applications_count, ward_supervisor_accepted_applications_count, ward_supervisor_rejected_applications_count, lga_supervisor_applications_count, lga_supervisor_accepted_applications_count, lga_supervisor_rejected_applications_count, state_supervisor_applications_count, state_supervisor_accepted_applications_count, state_supervisor_rejected_applications_count, pu_reports_count, pu_updates_count, results_submitted_count, unique_final_results_expected, pu_agents_count, unique_pu_agents_count, pu_agents_in_attendance_count, pu_average_arrival_time, pu_average_election_started_at, pu_average_election_ended_at, pu_election_practice_test_readiness_percentage, pu_final_results_uploaded_count, unique_pu_final_results_uploaded_count, pu_average_update_time_interval_in_seconds, pu_live_voters_referred_by_agent_count, total_pu_with_reports, total_pu_with_updates, total_pu_with_agents_in_attendance, total_pu_where_election_has_started, total_pu_where_election_has_ended, total_pu_unique_final_results_uploaded, total_pu_where_agents_referred_live_voters, parties, election_date, created_at, updated_at
`

type CreateElectionGroupParams struct {
	Name                       string      `json:"name"`
	Rank                       int32       `json:"rank"`
	ElectionsCount             int32       `json:"elections_count"`
	StatesCount                int32       `json:"states_count"`
	ElectionDate               pgtype.Date `json:"election_date"`
	SenatorialDistrictsCount   int32       `json:"senatorial_districts_count"`
	FederalConstituenciesCount int32       `json:"federal_constituencies_count"`
	LgasCount                  int32       `json:"lgas_count"`
	StateConstituenciesCount   int32       `json:"state_constituencies_count"`
	WardsCount                 int32       `json:"wards_count"`
	PollingUnitsCount          int32       `json:"polling_units_count"`
}

func (q *Queries) CreateElectionGroup(ctx context.Context, arg CreateElectionGroupParams) (ElectionGroup, error) {
	row := q.db.QueryRow(ctx, createElectionGroup,
		arg.Name,
		arg.Rank,
		arg.ElectionsCount,
		arg.StatesCount,
		arg.ElectionDate,
		arg.SenatorialDistrictsCount,
		arg.FederalConstituenciesCount,
		arg.LgasCount,
		arg.StateConstituenciesCount,
		arg.WardsCount,
		arg.PollingUnitsCount,
	)
	var i ElectionGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rank,
		&i.ElectionsCount,
		&i.StatesCount,
		&i.SenatorialDistrictsCount,
		&i.FederalConstituenciesCount,
		&i.LgasCount,
		&i.StateConstituenciesCount,
		&i.WardsCount,
		&i.PollingUnitsCount,
		&i.StateSupervisorsCount,
		&i.UniqueStateSupervisorsCount,
		&i.LgaSupervisorsCount,
		&i.UniqueLgaSupervisorsCount,
		&i.WardSupervisorsCount,
		&i.UniqueWardSupervisorsCount,
		&i.ApplicationsCount,
		&i.AcceptedApplicationsCount,
		&i.RejectedApplicationsCount,
		&i.WardSupervisorApplicationsCount,
		&i.WardSupervisorAcceptedApplicationsCount,
		&i.WardSupervisorRejectedApplicationsCount,
		&i.LgaSupervisorApplicationsCount,
		&i.LgaSupervisorAcceptedApplicationsCount,
		&i.LgaSupervisorRejectedApplicationsCount,
		&i.StateSupervisorApplicationsCount,
		&i.StateSupervisorAcceptedApplicationsCount,
		&i.StateSupervisorRejectedApplicationsCount,
		&i.PuReportsCount,
		&i.PuUpdatesCount,
		&i.ResultsSubmittedCount,
		&i.UniqueFinalResultsExpected,
		&i.PuAgentsCount,
		&i.UniquePuAgentsCount,
		&i.PuAgentsInAttendanceCount,
		&i.PuAverageArrivalTime,
		&i.PuAverageElectionStartedAt,
		&i.PuAverageElectionEndedAt,
		&i.PuElectionPracticeTestReadinessPercentage,
		&i.PuFinalResultsUploadedCount,
		&i.UniquePuFinalResultsUploadedCount,
		&i.PuAverageUpdateTimeIntervalInSeconds,
		&i.PuLiveVotersReferredByAgentCount,
		&i.TotalPuWithReports,
		&i.TotalPuWithUpdates,
		&i.TotalPuWithAgentsInAttendance,
		&i.TotalPuWhereElectionHasStarted,
		&i.TotalPuWhereElectionHasEnded,
		&i.TotalPuUniqueFinalResultsUploaded,
		&i.TotalPuWhereAgentsReferredLiveVoters,
		&i.Parties,
		&i.ElectionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteElectionGroup = `-- name: DeleteElectionGroup :exec
DELETE FROM election_groups WHERE id = $1
`

func (q *Queries) DeleteElectionGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteElectionGroup, id)
	return err
}

const getElectionGroupByID = `-- name: GetElectionGroupByID :one
SELECT id, name, rank, elections_count, states_count, senatorial_districts_count, federal_constituencies_count, lgas_count, state_constituencies_count, wards_count, polling_units_count, state_supervisors_count, unique_state_supervisors_count, lga_supervisors_count, unique_lga_supervisors_count, ward_supervisors_count, unique_ward_supervisors_count, applications_count, accepted_applications_count, rejected_applications_count, ward_supervisor_applications_count, ward_supervisor_accepted_applications_count, ward_supervisor_rejected_applications_count, lga_supervisor_applications_count, lga_supervisor_accepted_applications_count, lga_supervisor_rejected_applications_count, state_supervisor_applications_count, state_supervisor_accepted_applications_count, state_supervisor_rejected_applications_count, pu_reports_count, pu_updates_count, results_submitted_count, unique_final_results_expected, pu_agents_count, unique_pu_agents_count, pu_agents_in_attendance_count, pu_average_arrival_time, pu_average_election_started_at, pu_average_election_ended_at, pu_election_practice_test_readiness_percentage, pu_final_results_uploaded_count, unique_pu_final_results_uploaded_count, pu_average_update_time_interval_in_seconds, pu_live_voters_referred_by_agent_count, total_pu_with_reports, total_pu_with_updates, total_pu_with_agents_in_attendance, total_pu_where_election_has_started, total_pu_where_election_has_ended, total_pu_unique_final_results_uploaded, total_pu_where_agents_referred_live_voters, parties, election_date, created_at, updated_at FROM election_groups WHERE id = $1
`

func (q *Queries) GetElectionGroupByID(ctx context.Context, id int64) (ElectionGroup, error) {
	row := q.db.QueryRow(ctx, getElectionGroupByID, id)
	var i ElectionGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rank,
		&i.ElectionsCount,
		&i.StatesCount,
		&i.SenatorialDistrictsCount,
		&i.FederalConstituenciesCount,
		&i.LgasCount,
		&i.StateConstituenciesCount,
		&i.WardsCount,
		&i.PollingUnitsCount,
		&i.StateSupervisorsCount,
		&i.UniqueStateSupervisorsCount,
		&i.LgaSupervisorsCount,
		&i.UniqueLgaSupervisorsCount,
		&i.WardSupervisorsCount,
		&i.UniqueWardSupervisorsCount,
		&i.ApplicationsCount,
		&i.AcceptedApplicationsCount,
		&i.RejectedApplicationsCount,
		&i.WardSupervisorApplicationsCount,
		&i.WardSupervisorAcceptedApplicationsCount,
		&i.WardSupervisorRejectedApplicationsCount,
		&i.LgaSupervisorApplicationsCount,
		&i.LgaSupervisorAcceptedApplicationsCount,
		&i.LgaSupervisorRejectedApplicationsCount,
		&i.StateSupervisorApplicationsCount,
		&i.StateSupervisorAcceptedApplicationsCount,
		&i.StateSupervisorRejectedApplicationsCount,
		&i.PuReportsCount,
		&i.PuUpdatesCount,
		&i.ResultsSubmittedCount,
		&i.UniqueFinalResultsExpected,
		&i.PuAgentsCount,
		&i.UniquePuAgentsCount,
		&i.PuAgentsInAttendanceCount,
		&i.PuAverageArrivalTime,
		&i.PuAverageElectionStartedAt,
		&i.PuAverageElectionEndedAt,
		&i.PuElectionPracticeTestReadinessPercentage,
		&i.PuFinalResultsUploadedCount,
		&i.UniquePuFinalResultsUploadedCount,
		&i.PuAverageUpdateTimeIntervalInSeconds,
		&i.PuLiveVotersReferredByAgentCount,
		&i.TotalPuWithReports,
		&i.TotalPuWithUpdates,
		&i.TotalPuWithAgentsInAttendance,
		&i.TotalPuWhereElectionHasStarted,
		&i.TotalPuWhereElectionHasEnded,
		&i.TotalPuUniqueFinalResultsUploaded,
		&i.TotalPuWhereAgentsReferredLiveVoters,
		&i.Parties,
		&i.ElectionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getElectionGroupByName = `-- name: GetElectionGroupByName :one
SELECT id, name, rank, elections_count, states_count, senatorial_districts_count, federal_constituencies_count, lgas_count, state_constituencies_count, wards_count, polling_units_count, state_supervisors_count, unique_state_supervisors_count, lga_supervisors_count, unique_lga_supervisors_count, ward_supervisors_count, unique_ward_supervisors_count, applications_count, accepted_applications_count, rejected_applications_count, ward_supervisor_applications_count, ward_supervisor_accepted_applications_count, ward_supervisor_rejected_applications_count, lga_supervisor_applications_count, lga_supervisor_accepted_applications_count, lga_supervisor_rejected_applications_count, state_supervisor_applications_count, state_supervisor_accepted_applications_count, state_supervisor_rejected_applications_count, pu_reports_count, pu_updates_count, results_submitted_count, unique_final_results_expected, pu_agents_count, unique_pu_agents_count, pu_agents_in_attendance_count, pu_average_arrival_time, pu_average_election_started_at, pu_average_election_ended_at, pu_election_practice_test_readiness_percentage, pu_final_results_uploaded_count, unique_pu_final_results_uploaded_count, pu_average_update_time_interval_in_seconds, pu_live_voters_referred_by_agent_count, total_pu_with_reports, total_pu_with_updates, total_pu_with_agents_in_attendance, total_pu_where_election_has_started, total_pu_where_election_has_ended, total_pu_unique_final_results_uploaded, total_pu_where_agents_referred_live_voters, parties, election_date, created_at, updated_at FROM election_groups WHERE name = $1
`

func (q *Queries) GetElectionGroupByName(ctx context.Context, name string) (ElectionGroup, error) {
	row := q.db.QueryRow(ctx, getElectionGroupByName, name)
	var i ElectionGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rank,
		&i.ElectionsCount,
		&i.StatesCount,
		&i.SenatorialDistrictsCount,
		&i.FederalConstituenciesCount,
		&i.LgasCount,
		&i.StateConstituenciesCount,
		&i.WardsCount,
		&i.PollingUnitsCount,
		&i.StateSupervisorsCount,
		&i.UniqueStateSupervisorsCount,
		&i.LgaSupervisorsCount,
		&i.UniqueLgaSupervisorsCount,
		&i.WardSupervisorsCount,
		&i.UniqueWardSupervisorsCount,
		&i.ApplicationsCount,
		&i.AcceptedApplicationsCount,
		&i.RejectedApplicationsCount,
		&i.WardSupervisorApplicationsCount,
		&i.WardSupervisorAcceptedApplicationsCount,
		&i.WardSupervisorRejectedApplicationsCount,
		&i.LgaSupervisorApplicationsCount,
		&i.LgaSupervisorAcceptedApplicationsCount,
		&i.LgaSupervisorRejectedApplicationsCount,
		&i.StateSupervisorApplicationsCount,
		&i.StateSupervisorAcceptedApplicationsCount,
		&i.StateSupervisorRejectedApplicationsCount,
		&i.PuReportsCount,
		&i.PuUpdatesCount,
		&i.ResultsSubmittedCount,
		&i.UniqueFinalResultsExpected,
		&i.PuAgentsCount,
		&i.UniquePuAgentsCount,
		&i.PuAgentsInAttendanceCount,
		&i.PuAverageArrivalTime,
		&i.PuAverageElectionStartedAt,
		&i.PuAverageElectionEndedAt,
		&i.PuElectionPracticeTestReadinessPercentage,
		&i.PuFinalResultsUploadedCount,
		&i.UniquePuFinalResultsUploadedCount,
		&i.PuAverageUpdateTimeIntervalInSeconds,
		&i.PuLiveVotersReferredByAgentCount,
		&i.TotalPuWithReports,
		&i.TotalPuWithUpdates,
		&i.TotalPuWithAgentsInAttendance,
		&i.TotalPuWhereElectionHasStarted,
		&i.TotalPuWhereElectionHasEnded,
		&i.TotalPuUniqueFinalResultsUploaded,
		&i.TotalPuWhereAgentsReferredLiveVoters,
		&i.Parties,
		&i.ElectionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listElectionGroups = `-- name: ListElectionGroups :many
SELECT id, name, rank, elections_count, states_count, senatorial_districts_count, federal_constituencies_count, lgas_count, state_constituencies_count, wards_count, polling_units_count, state_supervisors_count, unique_state_supervisors_count, lga_supervisors_count, unique_lga_supervisors_count, ward_supervisors_count, unique_ward_supervisors_count, applications_count, accepted_applications_count, rejected_applications_count, ward_supervisor_applications_count, ward_supervisor_accepted_applications_count, ward_supervisor_rejected_applications_count, lga_supervisor_applications_count, lga_supervisor_accepted_applications_count, lga_supervisor_rejected_applications_count, state_supervisor_applications_count, state_supervisor_accepted_applications_count, state_supervisor_rejected_applications_count, pu_reports_count, pu_updates_count, results_submitted_count, unique_final_results_expected, pu_agents_count, unique_pu_agents_count, pu_agents_in_attendance_count, pu_average_arrival_time, pu_average_election_started_at, pu_average_election_ended_at, pu_election_practice_test_readiness_percentage, pu_final_results_uploaded_count, unique_pu_final_results_uploaded_count, pu_average_update_time_interval_in_seconds, pu_live_voters_referred_by_agent_count, total_pu_with_reports, total_pu_with_updates, total_pu_with_agents_in_attendance, total_pu_where_election_has_started, total_pu_where_election_has_ended, total_pu_unique_final_results_uploaded, total_pu_where_agents_referred_live_voters, parties, election_date, created_at, updated_at FROM election_groups
ORDER BY election_date DESC, id DESC
`

func (q *Queries) ListElectionGroups(ctx context.Context) ([]ElectionGroup, error) {
	rows, err := q.db.Query(ctx, listElectionGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ElectionGroup
	for rows.Next() {
		var i ElectionGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.ElectionsCount,
			&i.StatesCount,
			&i.SenatorialDistrictsCount,
			&i.FederalConstituenciesCount,
			&i.LgasCount,
			&i.StateConstituenciesCount,
			&i.WardsCount,
			&i.PollingUnitsCount,
			&i.StateSupervisorsCount,
			&i.UniqueStateSupervisorsCount,
			&i.LgaSupervisorsCount,
			&i.UniqueLgaSupervisorsCount,
			&i.WardSupervisorsCount,
			&i.UniqueWardSupervisorsCount,
			&i.ApplicationsCount,
			&i.AcceptedApplicationsCount,
			&i.RejectedApplicationsCount,
			&i.WardSupervisorApplicationsCount,
			&i.WardSupervisorAcceptedApplicationsCount,
			&i.WardSupervisorRejectedApplicationsCount,
			&i.LgaSupervisorApplicationsCount,
			&i.LgaSupervisorAcceptedApplicationsCount,
			&i.LgaSupervisorRejectedApplicationsCount,
			&i.StateSupervisorApplicationsCount,
			&i.StateSupervisorAcceptedApplicationsCount,
			&i.StateSupervisorRejectedApplicationsCount,
			&i.PuReportsCount,
			&i.PuUpdatesCount,
			&i.ResultsSubmittedCount,
			&i.UniqueFinalResultsExpected,
			&i.PuAgentsCount,
			&i.UniquePuAgentsCount,
			&i.PuAgentsInAttendanceCount,
			&i.PuAverageArrivalTime,
			&i.PuAverageElectionStartedAt,
			&i.PuAverageElectionEndedAt,
			&i.PuElectionPracticeTestReadinessPercentage,
			&i.PuFinalResultsUploadedCount,
			&i.UniquePuFinalResultsUploadedCount,
			&i.PuAverageUpdateTimeIntervalInSeconds,
			&i.PuLiveVotersReferredByAgentCount,
			&i.TotalPuWithReports,
			&i.TotalPuWithUpdates,
			&i.TotalPuWithAgentsInAttendance,
			&i.TotalPuWhereElectionHasStarted,
			&i.TotalPuWhereElectionHasEnded,
			&i.TotalPuUniqueFinalResultsUploaded,
			&i.TotalPuWhereAgentsReferredLiveVoters,
			&i.Parties,
			&i.ElectionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listElectionGroupsWithPartyStats = `-- name: ListElectionGroupsWithPartyStats :many
SELECT 
    eg.id, 
    eg.name, 
    eg.rank, 
    eg.elections_count, 
    eg.states_count, 
    eg.election_date, 
    eg.created_at, 
    eg.updated_at,
    COALESCE(peg.polling_agents_coverage, '{}'::jsonb)::jsonb AS polling_agents_coverage,
    COALESCE(peg.elections_contesting, 0)::integer AS elections_contesting
FROM election_groups eg
LEFT JOIN party_election_groups peg 
    ON eg.id = peg.election_group_id AND peg.party_id = $1
ORDER BY eg.election_date DESC, eg.id DESC
`

type ListElectionGroupsWithPartyStatsRow struct {
	ID                    int64              `json:"id"`
	Name                  string             `json:"name"`
	Rank                  int32              `json:"rank"`
	ElectionsCount        int32              `json:"elections_count"`
	StatesCount           int32              `json:"states_count"`
	ElectionDate          pgtype.Date        `json:"election_date"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	PollingAgentsCoverage []byte             `json:"polling_agents_coverage"`
	ElectionsContesting   int32              `json:"elections_contesting"`
}

func (q *Queries) ListElectionGroupsWithPartyStats(ctx context.Context, partyID int16) ([]ListElectionGroupsWithPartyStatsRow, error) {
	rows, err := q.db.Query(ctx, listElectionGroupsWithPartyStats, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListElectionGroupsWithPartyStatsRow
	for rows.Next() {
		var i ListElectionGroupsWithPartyStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rank,
			&i.ElectionsCount,
			&i.StatesCount,
			&i.ElectionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PollingAgentsCoverage,
			&i.ElectionsContesting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateElectionGroup = `-- name: UpdateElectionGroup :one
UPDATE election_groups
SET name = $1, rank = $2, elections_count = $3, states_count = $4, election_date = $5, updated_at = NOW()
WHERE id = $6
RETURNING id, name, rank, elections_count, states_count, senatorial_districts_count, federal_constituencies_count, lgas_count, state_constituencies_count, wards_count, polling_units_count, state_supervisors_count, unique_state_supervisors_count, lga_supervisors_count, unique_lga_supervisors_count, ward_supervisors_count, unique_ward_supervisors_count, applications_count, accepted_applications_count, rejected_applications_count, ward_supervisor_applications_count, ward_supervisor_accepted_applications_count, ward_supervisor_rejected_applications_count, lga_supervisor_applications_count, lga_supervisor_accepted_applications_count, lga_supervisor_rejected_applications_count, state_supervisor_applications_count, state_supervisor_accepted_applications_count, state_supervisor_rejected_applications_count, pu_reports_count, pu_updates_count, results_submitted_count, unique_final_results_expected, pu_agents_count, unique_pu_agents_count, pu_agents_in_attendance_count, pu_average_arrival_time, pu_average_election_started_at, pu_average_election_ended_at, pu_election_practice_test_readiness_percentage, pu_final_results_uploaded_count, unique_pu_final_results_uploaded_count, pu_average_update_time_interval_in_seconds, pu_live_voters_referred_by_agent_count, total_pu_with_reports, total_pu_with_updates, total_pu_with_agents_in_attendance, total_pu_where_election_has_started, total_pu_where_election_has_ended, total_pu_unique_final_results_uploaded, total_pu_where_agents_referred_live_voters, parties, election_date, created_at, updated_at
`

type UpdateElectionGroupParams struct {
	Name           string      `json:"name"`
	Rank           int32       `json:"rank"`
	ElectionsCount int32       `json:"elections_count"`
	StatesCount    int32       `json:"states_count"`
	ElectionDate   pgtype.Date `json:"election_date"`
	ID             int64       `json:"id"`
}

func (q *Queries) UpdateElectionGroup(ctx context.Context, arg UpdateElectionGroupParams) (ElectionGroup, error) {
	row := q.db.QueryRow(ctx, updateElectionGroup,
		arg.Name,
		arg.Rank,
		arg.ElectionsCount,
		arg.StatesCount,
		arg.ElectionDate,
		arg.ID,
	)
	var i ElectionGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rank,
		&i.ElectionsCount,
		&i.StatesCount,
		&i.SenatorialDistrictsCount,
		&i.FederalConstituenciesCount,
		&i.LgasCount,
		&i.StateConstituenciesCount,
		&i.WardsCount,
		&i.PollingUnitsCount,
		&i.StateSupervisorsCount,
		&i.UniqueStateSupervisorsCount,
		&i.LgaSupervisorsCount,
		&i.UniqueLgaSupervisorsCount,
		&i.WardSupervisorsCount,
		&i.UniqueWardSupervisorsCount,
		&i.ApplicationsCount,
		&i.AcceptedApplicationsCount,
		&i.RejectedApplicationsCount,
		&i.WardSupervisorApplicationsCount,
		&i.WardSupervisorAcceptedApplicationsCount,
		&i.WardSupervisorRejectedApplicationsCount,
		&i.LgaSupervisorApplicationsCount,
		&i.LgaSupervisorAcceptedApplicationsCount,
		&i.LgaSupervisorRejectedApplicationsCount,
		&i.StateSupervisorApplicationsCount,
		&i.StateSupervisorAcceptedApplicationsCount,
		&i.StateSupervisorRejectedApplicationsCount,
		&i.PuReportsCount,
		&i.PuUpdatesCount,
		&i.ResultsSubmittedCount,
		&i.UniqueFinalResultsExpected,
		&i.PuAgentsCount,
		&i.UniquePuAgentsCount,
		&i.PuAgentsInAttendanceCount,
		&i.PuAverageArrivalTime,
		&i.PuAverageElectionStartedAt,
		&i.PuAverageElectionEndedAt,
		&i.PuElectionPracticeTestReadinessPercentage,
		&i.PuFinalResultsUploadedCount,
		&i.UniquePuFinalResultsUploadedCount,
		&i.PuAverageUpdateTimeIntervalInSeconds,
		&i.PuLiveVotersReferredByAgentCount,
		&i.TotalPuWithReports,
		&i.TotalPuWithUpdates,
		&i.TotalPuWithAgentsInAttendance,
		&i.TotalPuWhereElectionHasStarted,
		&i.TotalPuWhereElectionHasEnded,
		&i.TotalPuUniqueFinalResultsUploaded,
		&i.TotalPuWhereAgentsReferredLiveVoters,
		&i.Parties,
		&i.ElectionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPartyElectionGroupCoverage = `-- name: UpsertPartyElectionGroupCoverage :one
INSERT INTO party_election_groups (party_id, election_group_id, polling_agents_coverage, elections_contesting)
VALUES ($1, $2, $3::jsonb, 0)
ON CONFLICT (party_id, election_group_id) 
DO UPDATE SET 
    polling_agents_coverage = EXCLUDED.polling_agents_coverage,
    updated_at = NOW()
RETURNING id, party_id, election_group_id, polling_agents_coverage, elections_contesting, reports_count, updates_count, results_submitted_count, created_at, updated_at
`

type UpsertPartyElectionGroupCoverageParams struct {
	PartyID         int16  `json:"party_id"`
	ElectionGroupID int64  `json:"election_group_id"`
	Column3         []byte `json:"column_3"`
}

func (q *Queries) UpsertPartyElectionGroupCoverage(ctx context.Context, arg UpsertPartyElectionGroupCoverageParams) (PartyElectionGroup, error) {
	row := q.db.QueryRow(ctx, upsertPartyElectionGroupCoverage, arg.PartyID, arg.ElectionGroupID, arg.Column3)
	var i PartyElectionGroup
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.ElectionGroupID,
		&i.PollingAgentsCoverage,
		&i.ElectionsContesting,
		&i.ReportsCount,
		&i.UpdatesCount,
		&i.ResultsSubmittedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPartyElectionGroupStats = `-- name: UpsertPartyElectionGroupStats :one
INSERT INTO party_election_groups (party_id, election_group_id, polling_agents_coverage, elections_contesting)
VALUES ($1, $2, $3::jsonb, $4)
ON CONFLICT (party_id, election_group_id) 
DO UPDATE SET 
    polling_agents_coverage = EXCLUDED.polling_agents_coverage,
    elections_contesting = EXCLUDED.elections_contesting,
    updated_at = NOW()
RETURNING id, party_id, election_group_id, polling_agents_coverage, elections_contesting, reports_count, updates_count, results_submitted_count, created_at, updated_at
`

type UpsertPartyElectionGroupStatsParams struct {
	PartyID             int16  `json:"party_id"`
	ElectionGroupID     int64  `json:"election_group_id"`
	Column3             []byte `json:"column_3"`
	ElectionsContesting int32  `json:"elections_contesting"`
}

func (q *Queries) UpsertPartyElectionGroupStats(ctx context.Context, arg UpsertPartyElectionGroupStatsParams) (PartyElectionGroup, error) {
	row := q.db.QueryRow(ctx, upsertPartyElectionGroupStats,
		arg.PartyID,
		arg.ElectionGroupID,
		arg.Column3,
		arg.ElectionsContesting,
	)
	var i PartyElectionGroup
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.ElectionGroupID,
		&i.PollingAgentsCoverage,
		&i.ElectionsContesting,
		&i.ReportsCount,
		&i.UpdatesCount,
		&i.ResultsSubmittedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
