// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CCity struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	StateID   int16          `json:"state_id"`
	CountryID int16          `json:"country_id"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
	CityRank  pgtype.Int2    `json:"city_rank"`
}

type CCountry struct {
	ID             int16          `json:"id"`
	Name           string         `json:"name"`
	Iso2           string         `json:"iso2"`
	Phonecode      string         `json:"phonecode"`
	Currency       string         `json:"currency"`
	CurrencySymbol string         `json:"currency_symbol"`
	RegionID       pgtype.Int2    `json:"region_id"`
	SubregionID    pgtype.Int2    `json:"subregion_id"`
	Nationality    string         `json:"nationality"`
	Latitude       pgtype.Numeric `json:"latitude"`
	Longitude      pgtype.Numeric `json:"longitude"`
	Emoji          string         `json:"emoji"`
	EmojiUnicode   string         `json:"emoji_unicode"`
}

type CRegion struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type CState struct {
	ID          int16          `json:"id"`
	Name        string         `json:"name"`
	CountryID   int16          `json:"country_id"`
	CountryCode string         `json:"country_code"`
	Latitude    pgtype.Numeric `json:"latitude"`
	Longitude   pgtype.Numeric `json:"longitude"`
}

type CSubregion struct {
	ID       int16  `json:"id"`
	Name     string `json:"name"`
	RegionID int16  `json:"region_id"`
}

type Election struct {
	ID                    int64              `json:"id"`
	Name                  string             `json:"name"`
	Rank                  int32              `json:"rank"`
	CandidatesCount       int32              `json:"candidates_count"`
	ElectionDate          pgtype.Date        `json:"election_date"`
	ElectionGroupID       int64              `json:"election_group_id"`
	ElectionGroupName     string             `json:"election_group_name"`
	OfficeID              int64              `json:"office_id"`
	OfficeName            string             `json:"office_name"`
	Scope                 string             `json:"scope"`
	StateID               pgtype.Int2        `json:"state_id"`
	SenatorialDistrictID  pgtype.Int4        `json:"senatorial_district_id"`
	FederalConstituencyID pgtype.Int4        `json:"federal_constituency_id"`
	StateConstituencyID   pgtype.Int4        `json:"state_constituency_id"`
	LgaID                 pgtype.Int4        `json:"lga_id"`
	WardID                pgtype.Int4        `json:"ward_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ElectionCandidate struct {
	ID          int64              `json:"id"`
	ElectionID  int64              `json:"election_id"`
	CandidateID int64              `json:"candidate_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ElectionGroup struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Rank           int32              `json:"rank"`
	ElectionsCount int32              `json:"elections_count"`
	StatesCount    int32              `json:"states_count"`
	ElectionDate   pgtype.Date        `json:"election_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type FederalConstituency struct {
	ID                     int32  `json:"id"`
	Name                   string `json:"name"`
	StateID                int32  `json:"state_id"`
	StateName              string `json:"state_name"`
	SenatorialDistrictID   int32  `json:"senatorial_district_id"`
	SenatorialDistrictName string `json:"senatorial_district_name"`
}

type File struct {
	ID           int64              `json:"id"`
	OriginalName string             `json:"original_name"`
	MimeType     string             `json:"mime_type"`
	FileSize     int64              `json:"file_size"`
	FileKey      string             `json:"file_key"`
	PublicUrl    string             `json:"public_url"`
	Folder       string             `json:"folder"`
	IsPublic     bool               `json:"is_public"`
	Status       string             `json:"status"`
	UploadedBy   pgtype.Int8        `json:"uploaded_by"`
	UploadedAt   pgtype.Timestamptz `json:"uploaded_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Lga struct {
	ID                      int32  `json:"id"`
	Name                    string `json:"name"`
	Abbreviation            string `json:"abbreviation"`
	StateID                 int32  `json:"state_id"`
	StateName               string `json:"state_name"`
	SenatorialDistrictID    int32  `json:"senatorial_district_id"`
	SenatorialDistrictName  string `json:"senatorial_district_name"`
	FederalConstituencyID   int32  `json:"federal_constituency_id"`
	FederalConstituencyName string `json:"federal_constituency_name"`
}

type Office struct {
	ID             int64              `json:"id"`
	Name           string             `json:"name"`
	Election       string             `json:"election"`
	Scope          string             `json:"scope"`
	Rank           int32              `json:"rank"`
	InstancesCount int32              `json:"instances_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Party struct {
	ID        int64              `json:"id"`
	ShortName string             `json:"short_name"`
	Name      string             `json:"name"`
	Logo      string             `json:"logo"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PollingUnit struct {
	ID                 int32         `json:"id"`
	Name               string        `json:"name"`
	Abbreviation       pgtype.Text   `json:"abbreviation"`
	Units              pgtype.Text   `json:"units"`
	Delimitation       pgtype.Text   `json:"delimitation"`
	Remark             pgtype.Text   `json:"remark"`
	RegistrationAreaID pgtype.Int4   `json:"registration_area_id"`
	WardID             int32         `json:"ward_id"`
	WardName           string        `json:"ward_name"`
	LgaID              int32         `json:"lga_id"`
	LgaName            string        `json:"lga_name"`
	StateID            int32         `json:"state_id"`
	StateName          string        `json:"state_name"`
	Latitude           pgtype.Float8 `json:"latitude"`
	Longitude          pgtype.Float8 `json:"longitude"`
	PreciseLocation    pgtype.Text   `json:"precise_location"`
	FormattedAddress   pgtype.Text   `json:"formatted_address"`
	GooglePlaceID      pgtype.Text   `json:"google_place_id"`
}

type SenatorialDistrict struct {
	ID              int32       `json:"id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	CoalitionCenter pgtype.Text `json:"coalition_center"`
	StateID         int32       `json:"state_id"`
	StateName       string      `json:"state_name"`
}

type StateAssemblyConstituency struct {
	ID                      int32  `json:"id"`
	Name                    string `json:"name"`
	LgaID                   int32  `json:"lga_id"`
	LgaName                 string `json:"lga_name"`
	StateID                 int32  `json:"state_id"`
	StateName               string `json:"state_name"`
	SenatorialDistrictID    int32  `json:"senatorial_district_id"`
	SenatorialDistrictName  string `json:"senatorial_district_name"`
	FederalConstituencyID   int32  `json:"federal_constituency_id"`
	FederalConstituencyName string `json:"federal_constituency_name"`
}

type User struct {
	ID             int64              `json:"id"`
	FakeID         pgtype.Int8        `json:"fake_id"`
	Email          pgtype.Text        `json:"email"`
	Avatar         pgtype.Text        `json:"avatar"`
	Phone          pgtype.Text        `json:"phone"`
	Username       pgtype.Text        `json:"username"`
	PasswordHash   string             `json:"password_hash"`
	LastName       pgtype.Text        `json:"last_name"`
	FirstName      pgtype.Text        `json:"first_name"`
	MiddleName     pgtype.Text        `json:"middle_name"`
	Gender         pgtype.Text        `json:"gender"`
	DateOfBirth    pgtype.Date        `json:"date_of_birth"`
	CurrentCountry int16              `json:"current_country"`
	CurrentState   int16              `json:"current_state"`
	CurrentCity    pgtype.Int4        `json:"current_city"`
	StateOfOrigin  pgtype.Int2        `json:"state_of_origin"`
	NinVerified    pgtype.Text        `json:"nin_verified"`
	PhoneVerified  pgtype.Text        `json:"phone_verified"`
	Role           pgtype.Text        `json:"role"`
	RoleLevel      pgtype.Text        `json:"role_level"`
	AccountStatus  pgtype.Text        `json:"account_status"`
	PartyID        pgtype.Int8        `json:"party_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserSecurityQuestion struct {
	ID        int64  `json:"id"`
	UserFid   int64  `json:"user_fid"`
	Nin       string `json:"nin"`
	Question1 int16  `json:"question1"`
	Answer1   string `json:"answer1"`
	Question2 int16  `json:"question2"`
	Answer2   string `json:"answer2"`
}

type UsersNin struct {
	ID     int32  `json:"id"`
	UserID int64  `json:"user_id"`
	Nin    string `json:"nin"`
}

type UsersPhoneNumber struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	Phone      string      `json:"phone"`
	OnWhatsapp pgtype.Text `json:"on_whatsapp"`
}

type Ward struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
	LgaID        int32  `json:"lga_id"`
	LgaName      string `json:"lga_name"`
	StateID      int32  `json:"state_id"`
	StateName    string `json:"state_name"`
}
