// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offices.sql

package queries

import (
	"context"
)

const createOffice = `-- name: CreateOffice :one
INSERT INTO offices (name, election, scope, rank)
VALUES ($1, $2, $3, $4)
RETURNING id, name, election, scope, rank, instances_count, created_at, updated_at
`

type CreateOfficeParams struct {
	Name     string `json:"name"`
	Election string `json:"election"`
	Scope    string `json:"scope"`
	Rank     int32  `json:"rank"`
}

func (q *Queries) CreateOffice(ctx context.Context, arg CreateOfficeParams) (Office, error) {
	row := q.db.QueryRow(ctx, createOffice,
		arg.Name,
		arg.Election,
		arg.Scope,
		arg.Rank,
	)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Election,
		&i.Scope,
		&i.Rank,
		&i.InstancesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOffice = `-- name: DeleteOffice :exec
DELETE FROM offices WHERE id = $1
`

func (q *Queries) DeleteOffice(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOffice, id)
	return err
}

const getOfficeByID = `-- name: GetOfficeByID :one
SELECT id, name, election, scope, rank, instances_count, created_at, updated_at FROM offices WHERE id = $1
`

func (q *Queries) GetOfficeByID(ctx context.Context, id int64) (Office, error) {
	row := q.db.QueryRow(ctx, getOfficeByID, id)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Election,
		&i.Scope,
		&i.Rank,
		&i.InstancesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOfficeByName = `-- name: GetOfficeByName :one
SELECT id, name, election, scope, rank, instances_count, created_at, updated_at FROM offices WHERE name = $1
`

func (q *Queries) GetOfficeByName(ctx context.Context, name string) (Office, error) {
	row := q.db.QueryRow(ctx, getOfficeByName, name)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Election,
		&i.Scope,
		&i.Rank,
		&i.InstancesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOffices = `-- name: ListOffices :many
SELECT id, name, election, scope, rank, instances_count, created_at, updated_at FROM offices
ORDER BY id ASC
`

func (q *Queries) ListOffices(ctx context.Context) ([]Office, error) {
	rows, err := q.db.Query(ctx, listOffices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Office
	for rows.Next() {
		var i Office
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Election,
			&i.Scope,
			&i.Rank,
			&i.InstancesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOffice = `-- name: UpdateOffice :one
UPDATE offices
SET name = $1, election = $2, scope = $3, rank = $4, updated_at = NOW()
WHERE id = $5
RETURNING id, name, election, scope, rank, instances_count, created_at, updated_at
`

type UpdateOfficeParams struct {
	Name     string `json:"name"`
	Election string `json:"election"`
	Scope    string `json:"scope"`
	Rank     int32  `json:"rank"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (Office, error) {
	row := q.db.QueryRow(ctx, updateOffice,
		arg.Name,
		arg.Election,
		arg.Scope,
		arg.Rank,
		arg.ID,
	)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Election,
		&i.Scope,
		&i.Rank,
		&i.InstancesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
