// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_verifications_updates.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updatePartyIsVerified = `-- name: UpdatePartyIsVerified :exec
UPDATE parties
SET is_verified = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePartyIsVerifiedParams struct {
	ID         int16       `json:"id"`
	IsVerified pgtype.Bool `json:"is_verified"`
}

func (q *Queries) UpdatePartyIsVerified(ctx context.Context, arg UpdatePartyIsVerifiedParams) error {
	_, err := q.db.Exec(ctx, updatePartyIsVerified, arg.ID, arg.IsVerified)
	return err
}

const updateUserIsVerified = `-- name: UpdateUserIsVerified :exec
UPDATE users
SET is_verified = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserIsVerifiedParams struct {
	ID         int64       `json:"id"`
	IsVerified pgtype.Bool `json:"is_verified"`
}

func (q *Queries) UpdateUserIsVerified(ctx context.Context, arg UpdateUserIsVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateUserIsVerified, arg.ID, arg.IsVerified)
	return err
}

const updateUserPhoneNumberIsVerified = `-- name: UpdateUserPhoneNumberIsVerified :exec
UPDATE users_phone_numbers
SET owner_is_verified = $2
WHERE user_id = $1
`

type UpdateUserPhoneNumberIsVerifiedParams struct {
	UserID          int64       `json:"user_id"`
	OwnerIsVerified pgtype.Bool `json:"owner_is_verified"`
}

func (q *Queries) UpdateUserPhoneNumberIsVerified(ctx context.Context, arg UpdateUserPhoneNumberIsVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateUserPhoneNumberIsVerified, arg.UserID, arg.OwnerIsVerified)
	return err
}
