// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: page_verifications.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPageVerification = `-- name: AddPageVerification :one
INSERT INTO pages_verified (
  page_type, page_id, verification_type_id
) VALUES (
  $1, $2, $3
)
ON CONFLICT (page_type, page_id, verification_type_id) 
DO UPDATE SET verified_at = CURRENT_TIMESTAMP
RETURNING id, page_type, page_id, verification_type_id, verified_at
`

type AddPageVerificationParams struct {
	PageType           string `json:"page_type"`
	PageID             int64  `json:"page_id"`
	VerificationTypeID int16  `json:"verification_type_id"`
}

func (q *Queries) AddPageVerification(ctx context.Context, arg AddPageVerificationParams) (PagesVerified, error) {
	row := q.db.QueryRow(ctx, addPageVerification, arg.PageType, arg.PageID, arg.VerificationTypeID)
	var i PagesVerified
	err := row.Scan(
		&i.ID,
		&i.PageType,
		&i.PageID,
		&i.VerificationTypeID,
		&i.VerifiedAt,
	)
	return i, err
}

const checkIfPageHasAnyVerification = `-- name: CheckIfPageHasAnyVerification :one
SELECT EXISTS(
  SELECT 1 FROM pages_verified WHERE page_type = $1 AND page_id = $2
)
`

type CheckIfPageHasAnyVerificationParams struct {
	PageType string `json:"page_type"`
	PageID   int64  `json:"page_id"`
}

func (q *Queries) CheckIfPageHasAnyVerification(ctx context.Context, arg CheckIfPageHasAnyVerificationParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkIfPageHasAnyVerification, arg.PageType, arg.PageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPageVerificationType = `-- name: GetPageVerificationType :one
SELECT id, verification_type, verification_title, verification_description, badge FROM page_verification_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPageVerificationType(ctx context.Context, id int16) (PageVerificationType, error) {
	row := q.db.QueryRow(ctx, getPageVerificationType, id)
	var i PageVerificationType
	err := row.Scan(
		&i.ID,
		&i.VerificationType,
		&i.VerificationTitle,
		&i.VerificationDescription,
		&i.Badge,
	)
	return i, err
}

const getPageVerifications = `-- name: GetPageVerifications :many
SELECT 
  pv.id,
  pv.page_type,
  pv.page_id,
  pv.verification_type_id,
  pv.verified_at,
  pvt.verification_type,
  pvt.verification_title,
  pvt.verification_description,
  pvt.badge
FROM pages_verified pv
JOIN page_verification_types pvt ON pv.verification_type_id = pvt.id
WHERE pv.page_type = $1 AND pv.page_id = $2
`

type GetPageVerificationsParams struct {
	PageType string `json:"page_type"`
	PageID   int64  `json:"page_id"`
}

type GetPageVerificationsRow struct {
	ID                      int64              `json:"id"`
	PageType                string             `json:"page_type"`
	PageID                  int64              `json:"page_id"`
	VerificationTypeID      int16              `json:"verification_type_id"`
	VerifiedAt              pgtype.Timestamptz `json:"verified_at"`
	VerificationType        string             `json:"verification_type"`
	VerificationTitle       string             `json:"verification_title"`
	VerificationDescription pgtype.Text        `json:"verification_description"`
	Badge                   pgtype.Text        `json:"badge"`
}

func (q *Queries) GetPageVerifications(ctx context.Context, arg GetPageVerificationsParams) ([]GetPageVerificationsRow, error) {
	rows, err := q.db.Query(ctx, getPageVerifications, arg.PageType, arg.PageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPageVerificationsRow
	for rows.Next() {
		var i GetPageVerificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PageType,
			&i.PageID,
			&i.VerificationTypeID,
			&i.VerifiedAt,
			&i.VerificationType,
			&i.VerificationTitle,
			&i.VerificationDescription,
			&i.Badge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerificationTypes = `-- name: ListVerificationTypes :many
SELECT id, verification_type, verification_title, verification_description, badge FROM page_verification_types ORDER BY id ASC
`

func (q *Queries) ListVerificationTypes(ctx context.Context) ([]PageVerificationType, error) {
	rows, err := q.db.Query(ctx, listVerificationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageVerificationType
	for rows.Next() {
		var i PageVerificationType
		if err := rows.Scan(
			&i.ID,
			&i.VerificationType,
			&i.VerificationTitle,
			&i.VerificationDescription,
			&i.Badge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePageVerification = `-- name: RemovePageVerification :exec
DELETE FROM pages_verified
WHERE page_type = $1 AND page_id = $2 AND verification_type_id = $3
`

type RemovePageVerificationParams struct {
	PageType           string `json:"page_type"`
	PageID             int64  `json:"page_id"`
	VerificationTypeID int16  `json:"verification_type_id"`
}

func (q *Queries) RemovePageVerification(ctx context.Context, arg RemovePageVerificationParams) error {
	_, err := q.db.Exec(ctx, removePageVerification, arg.PageType, arg.PageID, arg.VerificationTypeID)
	return err
}
