// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parties.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPartyMembership = `-- name: AddPartyMembership :exec
INSERT INTO party_membership (user_id, party_id, chapter_id, status)
VALUES ($1, $2, $3, 'active')
`

type AddPartyMembershipParams struct {
	UserID    int64 `json:"user_id"`
	PartyID   int32 `json:"party_id"`
	ChapterID int32 `json:"chapter_id"`
}

func (q *Queries) AddPartyMembership(ctx context.Context, arg AddPartyMembershipParams) error {
	_, err := q.db.Exec(ctx, addPartyMembership, arg.UserID, arg.PartyID, arg.ChapterID)
	return err
}

const addPartyMembershipRequest = `-- name: AddPartyMembershipRequest :one
INSERT INTO party_membership_requests (user_id, party_id, chapter_id)
VALUES ($1, $2, $3)
RETURNING id, party_id, chapter_id, user_id, status, created_at, updated_at
`

type AddPartyMembershipRequestParams struct {
	UserID    int64 `json:"user_id"`
	PartyID   int16 `json:"party_id"`
	ChapterID int32 `json:"chapter_id"`
}

func (q *Queries) AddPartyMembershipRequest(ctx context.Context, arg AddPartyMembershipRequestParams) (PartyMembershipRequest, error) {
	row := q.db.QueryRow(ctx, addPartyMembershipRequest, arg.UserID, arg.PartyID, arg.ChapterID)
	var i PartyMembershipRequest
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.ChapterID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChapterSettings = `-- name: CreateChapterSettings :one
INSERT INTO party_chapter_settings (party_id, chapter_id, settings)
VALUES ($1, $2, $3)
RETURNING settings
`

type CreateChapterSettingsParams struct {
	PartyID   int16  `json:"party_id"`
	ChapterID int32  `json:"chapter_id"`
	Settings  []byte `json:"settings"`
}

func (q *Queries) CreateChapterSettings(ctx context.Context, arg CreateChapterSettingsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createChapterSettings, arg.PartyID, arg.ChapterID, arg.Settings)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const createNationalChapter = `-- name: CreateNationalChapter :one
INSERT INTO party_chapters (party_id, chapter_type, country_id)
VALUES ($1, 'national', $2)
RETURNING id
`

type CreateNationalChapterParams struct {
	PartyID   int16       `json:"party_id"`
	CountryID pgtype.Int2 `json:"country_id"`
}

func (q *Queries) CreateNationalChapter(ctx context.Context, arg CreateNationalChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, createNationalChapter, arg.PartyID, arg.CountryID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createParty = `-- name: CreateParty :one
INSERT INTO parties (short_name, name, logo, logo_file_id, display_order, color_hex, dark_color_hex, cover_image, cover_image_file_id, cover_position_y, date_founded)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, short_name, name, logo, logo_file_id, cover_image, cover_image_file_id, cover_position_y, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, date_founded, created_at, updated_at
`

type CreatePartyParams struct {
	ShortName        string      `json:"short_name"`
	Name             string      `json:"name"`
	Logo             string      `json:"logo"`
	LogoFileID       pgtype.Int8 `json:"logo_file_id"`
	DisplayOrder     int32       `json:"display_order"`
	ColorHex         pgtype.Text `json:"color_hex"`
	DarkColorHex     pgtype.Text `json:"dark_color_hex"`
	CoverImage       pgtype.Text `json:"cover_image"`
	CoverImageFileID pgtype.Int8 `json:"cover_image_file_id"`
	CoverPositionY   pgtype.Int2 `json:"cover_position_y"`
	DateFounded      pgtype.Date `json:"date_founded"`
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty,
		arg.ShortName,
		arg.Name,
		arg.Logo,
		arg.LogoFileID,
		arg.DisplayOrder,
		arg.ColorHex,
		arg.DarkColorHex,
		arg.CoverImage,
		arg.CoverImageFileID,
		arg.CoverPositionY,
		arg.DateFounded,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.LogoFileID,
		&i.CoverImage,
		&i.CoverImageFileID,
		&i.CoverPositionY,
		&i.DisplayOrder,
		&i.Status,
		&i.Slots,
		&i.IsVerified,
		&i.DiscountPercentage,
		&i.AgentPaymentBalanceKobo,
		&i.AgentPaymentAllocationKobo,
		&i.AgentAcquisitionTargets,
		&i.AutoAcceptApplications,
		&i.ColorHex,
		&i.DarkColorHex,
		&i.DateFounded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deductPartyAgentPaymentBalance = `-- name: DeductPartyAgentPaymentBalance :one
UPDATE parties
SET agent_payment_balance_kobo = agent_payment_balance_kobo - $1,
    updated_at = NOW()
WHERE id = $2 AND agent_payment_balance_kobo >= $1
RETURNING id, short_name, name, logo, logo_file_id, cover_image, cover_image_file_id, cover_position_y, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, date_founded, created_at, updated_at
`

type DeductPartyAgentPaymentBalanceParams struct {
	AgentPaymentBalanceKobo int64 `json:"agent_payment_balance_kobo"`
	ID                      int16 `json:"id"`
}

func (q *Queries) DeductPartyAgentPaymentBalance(ctx context.Context, arg DeductPartyAgentPaymentBalanceParams) (Party, error) {
	row := q.db.QueryRow(ctx, deductPartyAgentPaymentBalance, arg.AgentPaymentBalanceKobo, arg.ID)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.LogoFileID,
		&i.CoverImage,
		&i.CoverImageFileID,
		&i.CoverPositionY,
		&i.DisplayOrder,
		&i.Status,
		&i.Slots,
		&i.IsVerified,
		&i.DiscountPercentage,
		&i.AgentPaymentBalanceKobo,
		&i.AgentPaymentAllocationKobo,
		&i.AgentAcquisitionTargets,
		&i.AutoAcceptApplications,
		&i.ColorHex,
		&i.DarkColorHex,
		&i.DateFounded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteParty = `-- name: DeleteParty :exec
UPDATE parties SET status = 'deleted' WHERE id = $1
`

func (q *Queries) DeleteParty(ctx context.Context, id int16) error {
	_, err := q.db.Exec(ctx, deleteParty, id)
	return err
}

const deletePartyMembership = `-- name: DeletePartyMembership :many
DELETE FROM party_membership WHERE user_id = $1 AND party_id = $2 RETURNING chapter_id
`

type DeletePartyMembershipParams struct {
	UserID  int64 `json:"user_id"`
	PartyID int32 `json:"party_id"`
}

func (q *Queries) DeletePartyMembership(ctx context.Context, arg DeletePartyMembershipParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, deletePartyMembership, arg.UserID, arg.PartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var chapter_id int32
		if err := rows.Scan(&chapter_id); err != nil {
			return nil, err
		}
		items = append(items, chapter_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChapterMemberCount = `-- name: GetChapterMemberCount :one
SELECT COUNT(*) FROM party_membership WHERE chapter_id = $1 AND status = 'active'
`

func (q *Queries) GetChapterMemberCount(ctx context.Context, chapterID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getChapterMemberCount, chapterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getChapterSettings = `-- name: GetChapterSettings :one
SELECT settings FROM party_chapter_settings
WHERE party_id = $1 AND chapter_id = $2 LIMIT 1
`

type GetChapterSettingsParams struct {
	PartyID   int16 `json:"party_id"`
	ChapterID int32 `json:"chapter_id"`
}

func (q *Queries) GetChapterSettings(ctx context.Context, arg GetChapterSettingsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getChapterSettings, arg.PartyID, arg.ChapterID)
	var settings []byte
	err := row.Scan(&settings)
	return settings, err
}

const getLGAChapter = `-- name: GetLGAChapter :one
SELECT id FROM party_chapters
WHERE party_id = $1 AND chapter_type = 'lga' AND lga_id = $2 LIMIT 1
`

type GetLGAChapterParams struct {
	PartyID int16       `json:"party_id"`
	LgaID   pgtype.Int4 `json:"lga_id"`
}

func (q *Queries) GetLGAChapter(ctx context.Context, arg GetLGAChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getLGAChapter, arg.PartyID, arg.LgaID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getNationalChapter = `-- name: GetNationalChapter :one
SELECT id FROM party_chapters 
WHERE party_id = $1 AND chapter_type = 'national' AND country_id = $2 LIMIT 1
`

type GetNationalChapterParams struct {
	PartyID   int16       `json:"party_id"`
	CountryID pgtype.Int2 `json:"country_id"`
}

func (q *Queries) GetNationalChapter(ctx context.Context, arg GetNationalChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNationalChapter, arg.PartyID, arg.CountryID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateLGAChapter = `-- name: GetOrCreateLGAChapter :one
INSERT INTO party_chapters (party_id, chapter_type, state_id, lga_id)
SELECT $1, 'lga', l.state_id, l.id
FROM lgas l WHERE l.id = $2
ON CONFLICT (party_id, lga_id) WHERE chapter_type = 'lga'
DO UPDATE SET party_id = EXCLUDED.party_id
RETURNING id
`

type GetOrCreateLGAChapterParams struct {
	PartyID int16 `json:"party_id"`
	ID      int32 `json:"id"`
}

func (q *Queries) GetOrCreateLGAChapter(ctx context.Context, arg GetOrCreateLGAChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateLGAChapter, arg.PartyID, arg.ID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateNationalChapter = `-- name: GetOrCreateNationalChapter :one
INSERT INTO party_chapters (party_id, chapter_type, country_id)
VALUES ($1, 'national', $2)
ON CONFLICT (party_id, country_id) WHERE chapter_type = 'national'
DO UPDATE SET party_id = EXCLUDED.party_id
RETURNING id
`

type GetOrCreateNationalChapterParams struct {
	PartyID   int16       `json:"party_id"`
	CountryID pgtype.Int2 `json:"country_id"`
}

func (q *Queries) GetOrCreateNationalChapter(ctx context.Context, arg GetOrCreateNationalChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateNationalChapter, arg.PartyID, arg.CountryID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateStateChapter = `-- name: GetOrCreateStateChapter :one
INSERT INTO party_chapters (party_id, chapter_type, state_id)
VALUES ($1, 'state', $2)
ON CONFLICT (party_id, state_id) WHERE chapter_type = 'state'
DO UPDATE SET party_id = EXCLUDED.party_id
RETURNING id
`

type GetOrCreateStateChapterParams struct {
	PartyID int16       `json:"party_id"`
	StateID pgtype.Int2 `json:"state_id"`
}

func (q *Queries) GetOrCreateStateChapter(ctx context.Context, arg GetOrCreateStateChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateStateChapter, arg.PartyID, arg.StateID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateWardChapter = `-- name: GetOrCreateWardChapter :one
INSERT INTO party_chapters (party_id, chapter_type, state_id, lga_id, ward_id)
SELECT $1, 'ward', w.state_id, w.lga_id, w.id
FROM wards w WHERE w.id = $2
ON CONFLICT (party_id, ward_id) WHERE chapter_type = 'ward'
DO UPDATE SET party_id = EXCLUDED.party_id
RETURNING id
`

type GetOrCreateWardChapterParams struct {
	PartyID int16 `json:"party_id"`
	ID      int32 `json:"id"`
}

func (q *Queries) GetOrCreateWardChapter(ctx context.Context, arg GetOrCreateWardChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateWardChapter, arg.PartyID, arg.ID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrCreateZonalChapter = `-- name: GetOrCreateZonalChapter :one
INSERT INTO party_chapters (party_id, chapter_type, zonal_id)
VALUES ($1, 'zonal', $2)
ON CONFLICT (party_id, zonal_id) WHERE chapter_type = 'zonal'
DO UPDATE SET party_id = EXCLUDED.party_id
RETURNING id
`

type GetOrCreateZonalChapterParams struct {
	PartyID int16       `json:"party_id"`
	ZonalID pgtype.Int2 `json:"zonal_id"`
}

func (q *Queries) GetOrCreateZonalChapter(ctx context.Context, arg GetOrCreateZonalChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getOrCreateZonalChapter, arg.PartyID, arg.ZonalID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPartiesActiveMemberCounts = `-- name: GetPartiesActiveMemberCounts :many
SELECT party_id::smallint, COUNT(DISTINCT user_id)::bigint AS member_count
FROM party_membership
WHERE status = 'active'
GROUP BY party_id
`

type GetPartiesActiveMemberCountsRow struct {
	PartyID     int16 `json:"party_id"`
	MemberCount int64 `json:"member_count"`
}

func (q *Queries) GetPartiesActiveMemberCounts(ctx context.Context) ([]GetPartiesActiveMemberCountsRow, error) {
	rows, err := q.db.Query(ctx, getPartiesActiveMemberCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartiesActiveMemberCountsRow
	for rows.Next() {
		var i GetPartiesActiveMemberCountsRow
		if err := rows.Scan(&i.PartyID, &i.MemberCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartiesSampleMemberAvatars = `-- name: GetPartiesSampleMemberAvatars :many
SELECT party_id::smallint, user_id, first_name, last_name, username, avatar
FROM (
  SELECT pm.party_id, u.id AS user_id, u.first_name, u.last_name, u.username, u.avatar,
         ROW_NUMBER() OVER (PARTITION BY pm.party_id ORDER BY pm.created_at DESC) as rn
  FROM party_membership pm
  JOIN users u ON u.id = pm.user_id
  WHERE pm.status = 'active' AND u.avatar IS NOT NULL AND u.avatar != ''
) sub
WHERE rn <= 5
`

type GetPartiesSampleMemberAvatarsRow struct {
	PartyID   int16       `json:"party_id"`
	UserID    int64       `json:"user_id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Username  pgtype.Text `json:"username"`
	Avatar    pgtype.Text `json:"avatar"`
}

func (q *Queries) GetPartiesSampleMemberAvatars(ctx context.Context) ([]GetPartiesSampleMemberAvatarsRow, error) {
	rows, err := q.db.Query(ctx, getPartiesSampleMemberAvatars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartiesSampleMemberAvatarsRow
	for rows.Next() {
		var i GetPartiesSampleMemberAvatarsRow
		if err := rows.Scan(
			&i.PartyID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartiesTopNationalOfficials = `-- name: GetPartiesTopNationalOfficials :many
SELECT party_id, position_id, position_name, position_code, rank_order,
       user_id, first_name, last_name, username, avatar, tenure_start
FROM (
  SELECT pa.party_id, pa.position_id, pos.name AS position_name, pos.code AS position_code, pos.rank_order,
         pa.user_id, u.first_name, u.last_name, u.username, u.avatar, pa.tenure_start,
         ROW_NUMBER() OVER (PARTITION BY pa.party_id ORDER BY pos.rank_order ASC, pa.tenure_start DESC) as rn
  FROM party_position_assignments pa
  JOIN party_positions pos ON pos.id = pa.position_id
  JOIN party_chapters pc ON pc.id = pa.chapter_id AND pc.chapter_type = 'national'
  JOIN users u ON u.id = pa.user_id
  WHERE pa.status = 'active'
) sub
WHERE rn <= 2
`

type GetPartiesTopNationalOfficialsRow struct {
	PartyID      int16       `json:"party_id"`
	PositionID   int32       `json:"position_id"`
	PositionName string      `json:"position_name"`
	PositionCode string      `json:"position_code"`
	RankOrder    int16       `json:"rank_order"`
	UserID       int64       `json:"user_id"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	Username     pgtype.Text `json:"username"`
	Avatar       pgtype.Text `json:"avatar"`
	TenureStart  pgtype.Date `json:"tenure_start"`
}

func (q *Queries) GetPartiesTopNationalOfficials(ctx context.Context) ([]GetPartiesTopNationalOfficialsRow, error) {
	rows, err := q.db.Query(ctx, getPartiesTopNationalOfficials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartiesTopNationalOfficialsRow
	for rows.Next() {
		var i GetPartiesTopNationalOfficialsRow
		if err := rows.Scan(
			&i.PartyID,
			&i.PositionID,
			&i.PositionName,
			&i.PositionCode,
			&i.RankOrder,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Avatar,
			&i.TenureStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartyBasicInfo = `-- name: GetPartyBasicInfo :one
SELECT id, short_name, name, logo, is_verified, color_hex, dark_color_hex FROM parties WHERE id = $1 LIMIT 1
`

type GetPartyBasicInfoRow struct {
	ID           int16       `json:"id"`
	ShortName    string      `json:"short_name"`
	Name         string      `json:"name"`
	Logo         string      `json:"logo"`
	IsVerified   pgtype.Bool `json:"is_verified"`
	ColorHex     pgtype.Text `json:"color_hex"`
	DarkColorHex pgtype.Text `json:"dark_color_hex"`
}

func (q *Queries) GetPartyBasicInfo(ctx context.Context, id int16) (GetPartyBasicInfoRow, error) {
	row := q.db.QueryRow(ctx, getPartyBasicInfo, id)
	var i GetPartyBasicInfoRow
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.IsVerified,
		&i.ColorHex,
		&i.DarkColorHex,
	)
	return i, err
}

const getPartyByID = `-- name: GetPartyByID :one
SELECT id, short_name, name, logo, logo_file_id, cover_image, cover_image_file_id, cover_position_y, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, date_founded, created_at, updated_at FROM parties WHERE id = $1
`

func (q *Queries) GetPartyByID(ctx context.Context, id int16) (Party, error) {
	row := q.db.QueryRow(ctx, getPartyByID, id)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.LogoFileID,
		&i.CoverImage,
		&i.CoverImageFileID,
		&i.CoverPositionY,
		&i.DisplayOrder,
		&i.Status,
		&i.Slots,
		&i.IsVerified,
		&i.DiscountPercentage,
		&i.AgentPaymentBalanceKobo,
		&i.AgentPaymentAllocationKobo,
		&i.AgentAcquisitionTargets,
		&i.AutoAcceptApplications,
		&i.ColorHex,
		&i.DarkColorHex,
		&i.DateFounded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyByShortName = `-- name: GetPartyByShortName :one
SELECT id, short_name, name, logo, logo_file_id, cover_image, cover_image_file_id, cover_position_y, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, date_founded, created_at, updated_at FROM parties WHERE short_name = $1
`

func (q *Queries) GetPartyByShortName(ctx context.Context, shortName string) (Party, error) {
	row := q.db.QueryRow(ctx, getPartyByShortName, shortName)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.LogoFileID,
		&i.CoverImage,
		&i.CoverImageFileID,
		&i.CoverPositionY,
		&i.DisplayOrder,
		&i.Status,
		&i.Slots,
		&i.IsVerified,
		&i.DiscountPercentage,
		&i.AgentPaymentBalanceKobo,
		&i.AgentPaymentAllocationKobo,
		&i.AgentAcquisitionTargets,
		&i.AutoAcceptApplications,
		&i.ColorHex,
		&i.DarkColorHex,
		&i.DateFounded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyChapterByID = `-- name: GetPartyChapterByID :one
SELECT id, party_id, chapter_type, country_id, zonal_id, state_id, lga_id, ward_id, created_at FROM party_chapters
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPartyChapterByID(ctx context.Context, id int32) (PartyChapter, error) {
	row := q.db.QueryRow(ctx, getPartyChapterByID, id)
	var i PartyChapter
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.ChapterType,
		&i.CountryID,
		&i.ZonalID,
		&i.StateID,
		&i.LgaID,
		&i.WardID,
		&i.CreatedAt,
	)
	return i, err
}

const getStateChapter = `-- name: GetStateChapter :one
SELECT id FROM party_chapters
WHERE party_id = $1 AND chapter_type = 'state' AND state_id = $2 LIMIT 1
`

type GetStateChapterParams struct {
	PartyID int16       `json:"party_id"`
	StateID pgtype.Int2 `json:"state_id"`
}

func (q *Queries) GetStateChapter(ctx context.Context, arg GetStateChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getStateChapter, arg.PartyID, arg.StateID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserActivePartyIDs = `-- name: GetUserActivePartyIDs :many
SELECT DISTINCT p_id::smallint AS party_id
FROM (
  SELECT party_id AS p_id FROM party_membership WHERE user_id = $1 AND status = 'active'
  UNION
  SELECT party_id AS p_id FROM users WHERE id = $1 AND party_id IS NOT NULL
) sub
`

func (q *Queries) GetUserActivePartyIDs(ctx context.Context, userID int64) ([]int16, error) {
	rows, err := q.db.Query(ctx, getUserActivePartyIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int16
	for rows.Next() {
		var party_id int16
		if err := rows.Scan(&party_id); err != nil {
			return nil, err
		}
		items = append(items, party_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWardChapter = `-- name: GetWardChapter :one
SELECT id FROM party_chapters
WHERE party_id = $1 AND chapter_type = 'ward' AND ward_id = $2 LIMIT 1
`

type GetWardChapterParams struct {
	PartyID int16       `json:"party_id"`
	WardID  pgtype.Int4 `json:"ward_id"`
}

func (q *Queries) GetWardChapter(ctx context.Context, arg GetWardChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getWardChapter, arg.PartyID, arg.WardID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getZonalChapter = `-- name: GetZonalChapter :one
SELECT id FROM party_chapters
WHERE party_id = $1 AND chapter_type = 'zonal' AND zonal_id = $2 LIMIT 1
`

type GetZonalChapterParams struct {
	PartyID int16       `json:"party_id"`
	ZonalID pgtype.Int2 `json:"zonal_id"`
}

func (q *Queries) GetZonalChapter(ctx context.Context, arg GetZonalChapterParams) (int32, error) {
	row := q.db.QueryRow(ctx, getZonalChapter, arg.PartyID, arg.ZonalID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listAcceptingParties = `-- name: ListAcceptingParties :many
SELECT 
  id, short_name, name, logo, display_order, status, slots, is_verified,
  discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets,
  color_hex, dark_color_hex,
  created_at, updated_at
FROM parties
WHERE 
  -- Ensure targets are set
  agent_acquisition_targets IS NOT NULL 
  AND agent_acquisition_targets != '{}'::jsonb
  
  -- Ensure allocation is set
  AND agent_payment_allocation_kobo IS NOT NULL 
  AND agent_payment_allocation_kobo != '{}'::jsonb
  
  -- Ensure balance is sufficient
  AND agent_payment_balance_kobo > 0
  AND agent_payment_balance_kobo >= COALESCE(
    (
      SELECT MAX((value->>'default')::bigint)
      FROM jsonb_each(agent_payment_allocation_kobo)
      WHERE value->>'default' IS NOT NULL
    ), 0
  )
ORDER BY display_order ASC, name ASC
`

type ListAcceptingPartiesRow struct {
	ID                         int16              `json:"id"`
	ShortName                  string             `json:"short_name"`
	Name                       string             `json:"name"`
	Logo                       string             `json:"logo"`
	DisplayOrder               int32              `json:"display_order"`
	Status                     string             `json:"status"`
	Slots                      int32              `json:"slots"`
	IsVerified                 pgtype.Bool        `json:"is_verified"`
	DiscountPercentage         pgtype.Numeric     `json:"discount_percentage"`
	AgentPaymentBalanceKobo    int64              `json:"agent_payment_balance_kobo"`
	AgentPaymentAllocationKobo []byte             `json:"agent_payment_allocation_kobo"`
	AgentAcquisitionTargets    []byte             `json:"agent_acquisition_targets"`
	ColorHex                   pgtype.Text        `json:"color_hex"`
	DarkColorHex               pgtype.Text        `json:"dark_color_hex"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAcceptingParties(ctx context.Context) ([]ListAcceptingPartiesRow, error) {
	rows, err := q.db.Query(ctx, listAcceptingParties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptingPartiesRow
	for rows.Next() {
		var i ListAcceptingPartiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortName,
			&i.Name,
			&i.Logo,
			&i.DisplayOrder,
			&i.Status,
			&i.Slots,
			&i.IsVerified,
			&i.DiscountPercentage,
			&i.AgentPaymentBalanceKobo,
			&i.AgentPaymentAllocationKobo,
			&i.AgentAcquisitionTargets,
			&i.ColorHex,
			&i.DarkColorHex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParties = `-- name: ListParties :many
SELECT id, short_name, name, logo, logo_file_id, cover_image, cover_image_file_id, cover_position_y, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, date_founded, created_at, updated_at FROM parties
WHERE status = 'active'
ORDER BY display_order ASC, name ASC
`

func (q *Queries) ListParties(ctx context.Context) ([]Party, error) {
	rows, err := q.db.Query(ctx, listParties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Party
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.ShortName,
			&i.Name,
			&i.Logo,
			&i.LogoFileID,
			&i.CoverImage,
			&i.CoverImageFileID,
			&i.CoverPositionY,
			&i.DisplayOrder,
			&i.Status,
			&i.Slots,
			&i.IsVerified,
			&i.DiscountPercentage,
			&i.AgentPaymentBalanceKobo,
			&i.AgentPaymentAllocationKobo,
			&i.AgentAcquisitionTargets,
			&i.AutoAcceptApplications,
			&i.ColorHex,
			&i.DarkColorHex,
			&i.DateFounded,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartyChapters = `-- name: ListPartyChapters :many
SELECT id, party_id, chapter_type, country_id, zonal_id, state_id, lga_id, ward_id, created_at FROM party_chapters
WHERE party_id = $1 
  AND ($2::varchar IS NULL OR chapter_type = $2)
  AND ($3::smallint IS NULL OR state_id = $3)
  AND ($4::int IS NULL OR lga_id = $4)
ORDER BY id ASC
`

type ListPartyChaptersParams struct {
	PartyID     int16       `json:"party_id"`
	ChapterType pgtype.Text `json:"chapter_type"`
	StateID     pgtype.Int2 `json:"state_id"`
	LgaID       pgtype.Int4 `json:"lga_id"`
}

func (q *Queries) ListPartyChapters(ctx context.Context, arg ListPartyChaptersParams) ([]PartyChapter, error) {
	rows, err := q.db.Query(ctx, listPartyChapters,
		arg.PartyID,
		arg.ChapterType,
		arg.StateID,
		arg.LgaID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartyChapter
	for rows.Next() {
		var i PartyChapter
		if err := rows.Scan(
			&i.ID,
			&i.PartyID,
			&i.ChapterType,
			&i.CountryID,
			&i.ZonalID,
			&i.StateID,
			&i.LgaID,
			&i.WardID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPartyMembershipHistory = `-- name: RecordPartyMembershipHistory :exec
INSERT INTO party_membership_history (user_id, party_id, chapter_id, action)
VALUES ($1, $2, $3, $4)
`

type RecordPartyMembershipHistoryParams struct {
	UserID    int64  `json:"user_id"`
	PartyID   int16  `json:"party_id"`
	ChapterID int32  `json:"chapter_id"`
	Action    string `json:"action"`
}

func (q *Queries) RecordPartyMembershipHistory(ctx context.Context, arg RecordPartyMembershipHistoryParams) error {
	_, err := q.db.Exec(ctx, recordPartyMembershipHistory,
		arg.UserID,
		arg.PartyID,
		arg.ChapterID,
		arg.Action,
	)
	return err
}

const resetPartyLogo = `-- name: ResetPartyLogo :exec
UPDATE parties
SET logo = '', logo_file_id = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetPartyLogo(ctx context.Context, id int16) error {
	_, err := q.db.Exec(ctx, resetPartyLogo, id)
	return err
}

const updateParty = `-- name: UpdateParty :one
UPDATE parties
SET short_name = $1, name = $2, logo = $3, logo_file_id = $4, display_order = $5, color_hex = $6, dark_color_hex = $7,
    cover_image = $8, cover_image_file_id = $9, cover_position_y = $10, date_founded = $11, updated_at = NOW()
WHERE id = $12
RETURNING id, short_name, name, logo, logo_file_id, cover_image, cover_image_file_id, cover_position_y, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, date_founded, created_at, updated_at
`

type UpdatePartyParams struct {
	ShortName        string      `json:"short_name"`
	Name             string      `json:"name"`
	Logo             string      `json:"logo"`
	LogoFileID       pgtype.Int8 `json:"logo_file_id"`
	DisplayOrder     int32       `json:"display_order"`
	ColorHex         pgtype.Text `json:"color_hex"`
	DarkColorHex     pgtype.Text `json:"dark_color_hex"`
	CoverImage       pgtype.Text `json:"cover_image"`
	CoverImageFileID pgtype.Int8 `json:"cover_image_file_id"`
	CoverPositionY   pgtype.Int2 `json:"cover_position_y"`
	DateFounded      pgtype.Date `json:"date_founded"`
	ID               int16       `json:"id"`
}

func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, updateParty,
		arg.ShortName,
		arg.Name,
		arg.Logo,
		arg.LogoFileID,
		arg.DisplayOrder,
		arg.ColorHex,
		arg.DarkColorHex,
		arg.CoverImage,
		arg.CoverImageFileID,
		arg.CoverPositionY,
		arg.DateFounded,
		arg.ID,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.LogoFileID,
		&i.CoverImage,
		&i.CoverImageFileID,
		&i.CoverPositionY,
		&i.DisplayOrder,
		&i.Status,
		&i.Slots,
		&i.IsVerified,
		&i.DiscountPercentage,
		&i.AgentPaymentBalanceKobo,
		&i.AgentPaymentAllocationKobo,
		&i.AgentAcquisitionTargets,
		&i.AutoAcceptApplications,
		&i.ColorHex,
		&i.DarkColorHex,
		&i.DateFounded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePartyAgentAcquisitionTargets = `-- name: UpdatePartyAgentAcquisitionTargets :one
UPDATE parties
SET agent_acquisition_targets = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, short_name, name, logo, logo_file_id, cover_image, cover_image_file_id, cover_position_y, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, date_founded, created_at, updated_at
`

type UpdatePartyAgentAcquisitionTargetsParams struct {
	ID                      int16  `json:"id"`
	AgentAcquisitionTargets []byte `json:"agent_acquisition_targets"`
}

func (q *Queries) UpdatePartyAgentAcquisitionTargets(ctx context.Context, arg UpdatePartyAgentAcquisitionTargetsParams) (Party, error) {
	row := q.db.QueryRow(ctx, updatePartyAgentAcquisitionTargets, arg.ID, arg.AgentAcquisitionTargets)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.LogoFileID,
		&i.CoverImage,
		&i.CoverImageFileID,
		&i.CoverPositionY,
		&i.DisplayOrder,
		&i.Status,
		&i.Slots,
		&i.IsVerified,
		&i.DiscountPercentage,
		&i.AgentPaymentBalanceKobo,
		&i.AgentPaymentAllocationKobo,
		&i.AgentAcquisitionTargets,
		&i.AutoAcceptApplications,
		&i.ColorHex,
		&i.DarkColorHex,
		&i.DateFounded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
