// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: party_slots.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPartySlots = `-- name: AddPartySlots :one
UPDATE parties
SET slots = slots + $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, short_name, name, logo, logo_file_id, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, created_at, updated_at
`

type AddPartySlotsParams struct {
	Slots int32 `json:"slots"`
	ID    int16 `json:"id"`
}

func (q *Queries) AddPartySlots(ctx context.Context, arg AddPartySlotsParams) (Party, error) {
	row := q.db.QueryRow(ctx, addPartySlots, arg.Slots, arg.ID)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.LogoFileID,
		&i.DisplayOrder,
		&i.Status,
		&i.Slots,
		&i.IsVerified,
		&i.DiscountPercentage,
		&i.AgentPaymentBalanceKobo,
		&i.AgentPaymentAllocationKobo,
		&i.AgentAcquisitionTargets,
		&i.AutoAcceptApplications,
		&i.ColorHex,
		&i.DarkColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deductPartySlots = `-- name: DeductPartySlots :one
UPDATE parties
SET slots = slots - $1,
    updated_at = NOW()
WHERE id = $2 AND slots >= $1
RETURNING id, short_name, name, logo, logo_file_id, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, created_at, updated_at
`

type DeductPartySlotsParams struct {
	Slots int32 `json:"slots"`
	ID    int16 `json:"id"`
}

func (q *Queries) DeductPartySlots(ctx context.Context, arg DeductPartySlotsParams) (Party, error) {
	row := q.db.QueryRow(ctx, deductPartySlots, arg.Slots, arg.ID)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.LogoFileID,
		&i.DisplayOrder,
		&i.Status,
		&i.Slots,
		&i.IsVerified,
		&i.DiscountPercentage,
		&i.AgentPaymentBalanceKobo,
		&i.AgentPaymentAllocationKobo,
		&i.AgentAcquisitionTargets,
		&i.AutoAcceptApplications,
		&i.ColorHex,
		&i.DarkColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT key, value, description, created_at, updated_at FROM system_settings WHERE key = $1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePartyDiscount = `-- name: UpdatePartyDiscount :one
UPDATE parties
SET discount_percentage = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, short_name, name, logo, logo_file_id, display_order, status, slots, is_verified, discount_percentage, agent_payment_balance_kobo, agent_payment_allocation_kobo, agent_acquisition_targets, auto_accept_applications, color_hex, dark_color_hex, created_at, updated_at
`

type UpdatePartyDiscountParams struct {
	DiscountPercentage pgtype.Numeric `json:"discount_percentage"`
	ID                 int16          `json:"id"`
}

func (q *Queries) UpdatePartyDiscount(ctx context.Context, arg UpdatePartyDiscountParams) (Party, error) {
	row := q.db.QueryRow(ctx, updatePartyDiscount, arg.DiscountPercentage, arg.ID)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.ShortName,
		&i.Name,
		&i.Logo,
		&i.LogoFileID,
		&i.DisplayOrder,
		&i.Status,
		&i.Slots,
		&i.IsVerified,
		&i.DiscountPercentage,
		&i.AgentPaymentBalanceKobo,
		&i.AgentPaymentAllocationKobo,
		&i.AgentAcquisitionTargets,
		&i.AutoAcceptApplications,
		&i.ColorHex,
		&i.DarkColorHex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSystemSetting = `-- name: UpdateSystemSetting :one
UPDATE system_settings
SET 
    value = $2, 
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE key = $1
RETURNING key, value, description, created_at, updated_at
`

type UpdateSystemSettingParams struct {
	Key         string      `json:"key"`
	Value       []byte      `json:"value"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateSystemSetting(ctx context.Context, arg UpdateSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, updateSystemSetting, arg.Key, arg.Value, arg.Description)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
