// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: party_wallets.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPartyWallet = `-- name: CreatePartyWallet :one
INSERT INTO party_wallets (party_id, account_reference, account_numbers)
VALUES ($1, $2, $3)
RETURNING id, party_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at
`

type CreatePartyWalletParams struct {
	PartyID          int16  `json:"party_id"`
	AccountReference string `json:"account_reference"`
	AccountNumbers   []byte `json:"account_numbers"`
}

func (q *Queries) CreatePartyWallet(ctx context.Context, arg CreatePartyWalletParams) (PartyWallet, error) {
	row := q.db.QueryRow(ctx, createPartyWallet, arg.PartyID, arg.AccountReference, arg.AccountNumbers)
	var i PartyWallet
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO party_wallet_transactions (
  wallet_id,
  transaction_reference,
  type,
  transaction_category,
  amount_kobo,
  balance_after_kobo,
  payer_name,
  payer_account_number,
  payer_bank_code,
  narration,
  raw_payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, wallet_id, transaction_reference, type, amount_kobo, balance_after_kobo, payer_name, payer_account_number, payer_bank_code, narration, transaction_category, raw_payload, created_at
`

type CreateWalletTransactionParams struct {
	WalletID             int64       `json:"wallet_id"`
	TransactionReference string      `json:"transaction_reference"`
	Type                 string      `json:"type"`
	TransactionCategory  string      `json:"transaction_category"`
	AmountKobo           int64       `json:"amount_kobo"`
	BalanceAfterKobo     int64       `json:"balance_after_kobo"`
	PayerName            pgtype.Text `json:"payer_name"`
	PayerAccountNumber   pgtype.Text `json:"payer_account_number"`
	PayerBankCode        pgtype.Text `json:"payer_bank_code"`
	Narration            pgtype.Text `json:"narration"`
	RawPayload           []byte      `json:"raw_payload"`
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (PartyWalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction,
		arg.WalletID,
		arg.TransactionReference,
		arg.Type,
		arg.TransactionCategory,
		arg.AmountKobo,
		arg.BalanceAfterKobo,
		arg.PayerName,
		arg.PayerAccountNumber,
		arg.PayerBankCode,
		arg.Narration,
		arg.RawPayload,
	)
	var i PartyWalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TransactionReference,
		&i.Type,
		&i.AmountKobo,
		&i.BalanceAfterKobo,
		&i.PayerName,
		&i.PayerAccountNumber,
		&i.PayerBankCode,
		&i.Narration,
		&i.TransactionCategory,
		&i.RawPayload,
		&i.CreatedAt,
	)
	return i, err
}

const creditPartyWallet = `-- name: CreditPartyWallet :one
UPDATE party_wallets
SET balance_kobo = balance_kobo + $1,
    updated_at   = NOW()
WHERE id = $2
RETURNING id, party_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at
`

type CreditPartyWalletParams struct {
	BalanceKobo int64 `json:"balance_kobo"`
	ID          int64 `json:"id"`
}

func (q *Queries) CreditPartyWallet(ctx context.Context, arg CreditPartyWalletParams) (PartyWallet, error) {
	row := q.db.QueryRow(ctx, creditPartyWallet, arg.BalanceKobo, arg.ID)
	var i PartyWallet
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const debitPartyWallet = `-- name: DebitPartyWallet :one
UPDATE party_wallets
SET balance_kobo = balance_kobo - $1,
    updated_at   = NOW()
WHERE id = $2 AND balance_kobo >= $1
RETURNING id, party_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at
`

type DebitPartyWalletParams struct {
	BalanceKobo int64 `json:"balance_kobo"`
	ID          int64 `json:"id"`
}

func (q *Queries) DebitPartyWallet(ctx context.Context, arg DebitPartyWalletParams) (PartyWallet, error) {
	row := q.db.QueryRow(ctx, debitPartyWallet, arg.BalanceKobo, arg.ID)
	var i PartyWallet
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyWalletByAccountReference = `-- name: GetPartyWalletByAccountReference :one
SELECT id, party_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at FROM party_wallets WHERE account_reference = $1
`

func (q *Queries) GetPartyWalletByAccountReference(ctx context.Context, accountReference string) (PartyWallet, error) {
	row := q.db.QueryRow(ctx, getPartyWalletByAccountReference, accountReference)
	var i PartyWallet
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyWalletByID = `-- name: GetPartyWalletByID :one
SELECT id, party_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at FROM party_wallets WHERE id = $1
`

func (q *Queries) GetPartyWalletByID(ctx context.Context, id int64) (PartyWallet, error) {
	row := q.db.QueryRow(ctx, getPartyWalletByID, id)
	var i PartyWallet
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyWalletByPartyID = `-- name: GetPartyWalletByPartyID :one
SELECT id, party_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at FROM party_wallets WHERE party_id = $1
`

func (q *Queries) GetPartyWalletByPartyID(ctx context.Context, partyID int16) (PartyWallet, error) {
	row := q.db.QueryRow(ctx, getPartyWalletByPartyID, partyID)
	var i PartyWallet
	err := row.Scan(
		&i.ID,
		&i.PartyID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTransactionByReference = `-- name: GetWalletTransactionByReference :one
SELECT id, wallet_id, transaction_reference, type, amount_kobo, balance_after_kobo, payer_name, payer_account_number, payer_bank_code, narration, transaction_category, raw_payload, created_at FROM party_wallet_transactions
WHERE transaction_reference = $1
`

func (q *Queries) GetWalletTransactionByReference(ctx context.Context, transactionReference string) (PartyWalletTransaction, error) {
	row := q.db.QueryRow(ctx, getWalletTransactionByReference, transactionReference)
	var i PartyWalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TransactionReference,
		&i.Type,
		&i.AmountKobo,
		&i.BalanceAfterKobo,
		&i.PayerName,
		&i.PayerAccountNumber,
		&i.PayerBankCode,
		&i.Narration,
		&i.TransactionCategory,
		&i.RawPayload,
		&i.CreatedAt,
	)
	return i, err
}

const listPartiesWithoutWallet = `-- name: ListPartiesWithoutWallet :many
SELECT p.id, p.short_name, p.name, p.logo, p.display_order, p.status, p.slots, p.is_verified, p.discount_percentage, p.agent_payment_balance_kobo, p.agent_payment_allocation, p.agent_acquisition_targets, p.created_at, p.updated_at FROM parties p
LEFT JOIN party_wallets pw ON pw.party_id = p.id
WHERE pw.id IS NULL
ORDER BY p.id ASC
`

func (q *Queries) ListPartiesWithoutWallet(ctx context.Context) ([]Party, error) {
	rows, err := q.db.Query(ctx, listPartiesWithoutWallet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Party
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.ShortName,
			&i.Name,
			&i.Logo,
			&i.LogoFileID,
			&i.DisplayOrder,
			&i.Status,
			&i.Slots,
			&i.IsVerified,
			&i.DiscountPercentage,
			&i.AgentPaymentBalanceKobo,
			&i.AgentPaymentAllocation,
			&i.AgentAcquisitionTargets,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, wallet_id, transaction_reference, type, amount_kobo, balance_after_kobo, payer_name, payer_account_number, payer_bank_code, narration, transaction_category, raw_payload, created_at FROM party_wallet_transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]PartyWalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartyWalletTransaction
	for rows.Next() {
		var i PartyWalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TransactionReference,
			&i.Type,
			&i.AmountKobo,
			&i.BalanceAfterKobo,
			&i.PayerName,
			&i.PayerAccountNumber,
			&i.PayerBankCode,
			&i.Narration,
			&i.TransactionCategory,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
