// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: practice_tests.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendPracticeTestTask = `-- name: AppendPracticeTestTask :one
UPDATE user_practice_tests
SET
  task_stats = task_stats || $1::jsonb,
  updated_at = NOW()
WHERE id = $2
  AND user_id = $3
RETURNING id, user_id, election_group_id, role, sequence, task_stats, final_score, status, started_at, completed_at, created_at, updated_at
`

type AppendPracticeTestTaskParams struct {
	TaskStat []byte `json:"task_stat"`
	ID       int64  `json:"id"`
	UserID   int64  `json:"user_id"`
}

func (q *Queries) AppendPracticeTestTask(ctx context.Context, arg AppendPracticeTestTaskParams) (UserPracticeTest, error) {
	row := q.db.QueryRow(ctx, appendPracticeTestTask, arg.TaskStat, arg.ID, arg.UserID)
	var i UserPracticeTest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ElectionGroupID,
		&i.Role,
		&i.Sequence,
		&i.TaskStats,
		&i.FinalScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completePracticeTest = `-- name: CompletePracticeTest :one
UPDATE user_practice_tests
SET
  final_score  = $1,
  status       = 'completed',
  completed_at = NOW(),
  updated_at   = NOW()
WHERE id = $2
  AND user_id = $3
RETURNING id, user_id, election_group_id, role, sequence, task_stats, final_score, status, started_at, completed_at, created_at, updated_at
`

type CompletePracticeTestParams struct {
	FinalScore pgtype.Numeric `json:"final_score"`
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
}

func (q *Queries) CompletePracticeTest(ctx context.Context, arg CompletePracticeTestParams) (UserPracticeTest, error) {
	row := q.db.QueryRow(ctx, completePracticeTest, arg.FinalScore, arg.ID, arg.UserID)
	var i UserPracticeTest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ElectionGroupID,
		&i.Role,
		&i.Sequence,
		&i.TaskStats,
		&i.FinalScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPracticeTest = `-- name: CreatePracticeTest :one
INSERT INTO user_practice_tests (
  user_id,
  election_group_id,
  role,
  sequence
) VALUES (
  $1,
  $2,
  $3,
  (
    SELECT COALESCE(MAX(sequence), 0) + 1
    FROM user_practice_tests
    WHERE user_id = $1
      AND ($2::bigint = 0 OR election_group_id = $2)
      AND role = $3
  )
)
RETURNING id, user_id, election_group_id, role, sequence, task_stats, final_score, status, started_at, completed_at, created_at, updated_at
`

type CreatePracticeTestParams struct {
	UserID          int64       `json:"user_id"`
	ElectionGroupID pgtype.Int8 `json:"election_group_id"`
	Role            string      `json:"role"`
}

func (q *Queries) CreatePracticeTest(ctx context.Context, arg CreatePracticeTestParams) (UserPracticeTest, error) {
	row := q.db.QueryRow(ctx, createPracticeTest, arg.UserID, arg.ElectionGroupID, arg.Role)
	var i UserPracticeTest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ElectionGroupID,
		&i.Role,
		&i.Sequence,
		&i.TaskStats,
		&i.FinalScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPracticeTest = `-- name: GetPracticeTest :one
SELECT id, user_id, election_group_id, role, sequence, task_stats, final_score, status, started_at, completed_at, created_at, updated_at FROM user_practice_tests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPracticeTest(ctx context.Context, id int64) (UserPracticeTest, error) {
	row := q.db.QueryRow(ctx, getPracticeTest, id)
	var i UserPracticeTest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ElectionGroupID,
		&i.Role,
		&i.Sequence,
		&i.TaskStats,
		&i.FinalScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserPracticeTests = `-- name: ListUserPracticeTests :many
SELECT
  upt.id, upt.user_id, upt.election_group_id, upt.role, upt.sequence, upt.task_stats, upt.final_score, upt.status, upt.started_at, upt.completed_at, upt.created_at, upt.updated_at,
  u.first_name,
  u.last_name,
  u.username
FROM user_practice_tests upt
JOIN users u ON upt.user_id = u.id
WHERE
  ($1::bigint = 0 OR upt.user_id = $1) AND
  ($2::bigint = 0 OR upt.election_group_id = $2) AND
  ($3::varchar = '' OR upt.status = $3) AND
  ($4::bigint = 0 OR upt.id < $4)
ORDER BY upt.id DESC
LIMIT $5::int
`

type ListUserPracticeTestsParams struct {
	UserID          int64  `json:"user_id"`
	ElectionGroupID int64  `json:"election_group_id"`
	Status          string `json:"status"`
	Cursor          int64  `json:"cursor"`
	LimitVal        int32  `json:"limit_val"`
}

type ListUserPracticeTestsRow struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	ElectionGroupID pgtype.Int8        `json:"election_group_id"`
	Role            string             `json:"role"`
	Sequence        int16              `json:"sequence"`
	TaskStats       []byte             `json:"task_stats"`
	FinalScore      pgtype.Numeric     `json:"final_score"`
	Status          string             `json:"status"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FirstName       pgtype.Text        `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	Username        pgtype.Text        `json:"username"`
}

func (q *Queries) ListUserPracticeTests(ctx context.Context, arg ListUserPracticeTestsParams) ([]ListUserPracticeTestsRow, error) {
	rows, err := q.db.Query(ctx, listUserPracticeTests,
		arg.UserID,
		arg.ElectionGroupID,
		arg.Status,
		arg.Cursor,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPracticeTestsRow
	for rows.Next() {
		var i ListUserPracticeTestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ElectionGroupID,
			&i.Role,
			&i.Sequence,
			&i.TaskStats,
			&i.FinalScore,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
