// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: practice_tests.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPracticeTest = `-- name: GetPracticeTest :one
SELECT id, user_id, election_group_id, role, test_attempts, overall_score, earned_amount_kobo, created_at, updated_at FROM user_practice_tests
WHERE user_id = $1 
  AND election_group_id = $2
  AND role = $3
LIMIT 1
`

type GetPracticeTestParams struct {
	UserID          int64       `json:"user_id"`
	ElectionGroupID pgtype.Int8 `json:"election_group_id"`
	Role            string      `json:"role"`
}

func (q *Queries) GetPracticeTest(ctx context.Context, arg GetPracticeTestParams) (UserPracticeTest, error) {
	row := q.db.QueryRow(ctx, getPracticeTest, arg.UserID, arg.ElectionGroupID, arg.Role)
	var i UserPracticeTest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ElectionGroupID,
		&i.Role,
		&i.TestAttempts,
		&i.OverallScore,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserPracticeTests = `-- name: ListUserPracticeTests :many
SELECT
  upt.id, upt.user_id, upt.election_group_id, upt.role, upt.test_attempts, upt.overall_score, upt.earned_amount_kobo, upt.created_at, upt.updated_at,
  u.first_name,
  u.last_name,
  u.username
FROM user_practice_tests upt
JOIN users u ON upt.user_id = u.id
WHERE
  ($1::bigint = 0 OR upt.user_id = $1) AND
  ($2::bigint = 0 OR upt.election_group_id = $2) AND
  ($3::bigint = 0 OR upt.id < $3)
ORDER BY upt.id DESC
LIMIT $4::int
`

type ListUserPracticeTestsParams struct {
	UserID          int64 `json:"user_id"`
	ElectionGroupID int64 `json:"election_group_id"`
	Cursor          int64 `json:"cursor"`
	LimitVal        int32 `json:"limit_val"`
}

type ListUserPracticeTestsRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	ElectionGroupID  pgtype.Int8        `json:"election_group_id"`
	Role             string             `json:"role"`
	TestAttempts     []byte             `json:"test_attempts"`
	OverallScore     pgtype.Numeric     `json:"overall_score"`
	EarnedAmountKobo int64              `json:"earned_amount_kobo"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        pgtype.Text        `json:"first_name"`
	LastName         pgtype.Text        `json:"last_name"`
	Username         pgtype.Text        `json:"username"`
}

func (q *Queries) ListUserPracticeTests(ctx context.Context, arg ListUserPracticeTestsParams) ([]ListUserPracticeTestsRow, error) {
	rows, err := q.db.Query(ctx, listUserPracticeTests,
		arg.UserID,
		arg.ElectionGroupID,
		arg.Cursor,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPracticeTestsRow
	for rows.Next() {
		var i ListUserPracticeTestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ElectionGroupID,
			&i.Role,
			&i.TestAttempts,
			&i.OverallScore,
			&i.EarnedAmountKobo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPracticeTestAttemptsPaid = `-- name: MarkPracticeTestAttemptsPaid :one
UPDATE user_practice_tests
SET test_attempts = (
  SELECT jsonb_agg(
    CASE
      WHEN (elem->>'been_paid')::boolean IS NOT TRUE
      THEN elem || '{"been_paid": true}'::jsonb
      ELSE elem
    END
  )
  FROM jsonb_array_elements(test_attempts) AS elem
),
earned_amount_kobo = earned_amount_kobo + $1::bigint,
updated_at = NOW()
WHERE id = $2::bigint
RETURNING id, user_id, election_group_id, role, test_attempts, overall_score, earned_amount_kobo, created_at, updated_at
`

type MarkPracticeTestAttemptsPaidParams struct {
	EarnedDeltaKobo int64 `json:"earned_delta_kobo"`
	ID              int64 `json:"id"`
}

// Sets been_paid=true on every attempt that currently has been_paid=false and increments earned_amount_kobo.
func (q *Queries) MarkPracticeTestAttemptsPaid(ctx context.Context, arg MarkPracticeTestAttemptsPaidParams) (UserPracticeTest, error) {
	row := q.db.QueryRow(ctx, markPracticeTestAttemptsPaid, arg.EarnedDeltaKobo, arg.ID)
	var i UserPracticeTest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ElectionGroupID,
		&i.Role,
		&i.TestAttempts,
		&i.OverallScore,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitPracticeTest = `-- name: SubmitPracticeTest :one
INSERT INTO user_practice_tests (
  user_id,
  election_group_id,
  role,
  test_attempts,
  overall_score,
  earned_amount_kobo
) VALUES (
  $1,
  $2,
  $3,
  JSONB_BUILD_ARRAY($4::jsonb),
  $5,
  $6
)
ON CONFLICT (user_id, election_group_id, role)
DO UPDATE SET
  test_attempts = user_practice_tests.test_attempts || $4::jsonb,
  overall_score = GREATEST(user_practice_tests.overall_score, $5),
  earned_amount_kobo = user_practice_tests.earned_amount_kobo + $6::bigint,
  updated_at = NOW()
RETURNING id, user_id, election_group_id, role, test_attempts, overall_score, earned_amount_kobo, created_at, updated_at
`

type SubmitPracticeTestParams struct {
	UserID           int64          `json:"user_id"`
	ElectionGroupID  pgtype.Int8    `json:"election_group_id"`
	Role             string         `json:"role"`
	Attempt          []byte         `json:"attempt"`
	OverallScore     pgtype.Numeric `json:"overall_score"`
	EarnedAmountKobo int64          `json:"earned_amount_kobo"`
}

func (q *Queries) SubmitPracticeTest(ctx context.Context, arg SubmitPracticeTestParams) (UserPracticeTest, error) {
	row := q.db.QueryRow(ctx, submitPracticeTest,
		arg.UserID,
		arg.ElectionGroupID,
		arg.Role,
		arg.Attempt,
		arg.OverallScore,
		arg.EarnedAmountKobo,
	)
	var i UserPracticeTest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ElectionGroupID,
		&i.Role,
		&i.TestAttempts,
		&i.OverallScore,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
