// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supervisor_assignments.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLgaSupervisor = `-- name: CreateLgaSupervisor :one
INSERT INTO lga_election_supervisors (
  user_id,
  state_id,
  lga_id,
  election_group_id,
  party_id,
  role_type,
  assigned_by,
  potential_payment_kobo
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, state_id, lga_id, election_group_id, party_id, role_type, assigned_by, arrived_at, arrival_video_url, potential_payment_kobo, earned_amount_kobo, created_at, updated_at
`

type CreateLgaSupervisorParams struct {
	UserID               int64       `json:"user_id"`
	StateID              int16       `json:"state_id"`
	LgaID                int32       `json:"lga_id"`
	ElectionGroupID      int64       `json:"election_group_id"`
	PartyID              int16       `json:"party_id"`
	RoleType             pgtype.Text `json:"role_type"`
	AssignedBy           pgtype.Int8 `json:"assigned_by"`
	PotentialPaymentKobo int64       `json:"potential_payment_kobo"`
}

func (q *Queries) CreateLgaSupervisor(ctx context.Context, arg CreateLgaSupervisorParams) (LgaElectionSupervisor, error) {
	row := q.db.QueryRow(ctx, createLgaSupervisor,
		arg.UserID,
		arg.StateID,
		arg.LgaID,
		arg.ElectionGroupID,
		arg.PartyID,
		arg.RoleType,
		arg.AssignedBy,
		arg.PotentialPaymentKobo,
	)
	var i LgaElectionSupervisor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StateID,
		&i.LgaID,
		&i.ElectionGroupID,
		&i.PartyID,
		&i.RoleType,
		&i.AssignedBy,
		&i.ArrivedAt,
		&i.ArrivalVideoUrl,
		&i.PotentialPaymentKobo,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStateSupervisor = `-- name: CreateStateSupervisor :one
INSERT INTO state_election_supervisors (
  user_id,
  state_id,
  election_group_id,
  party_id,
  role_type,
  assigned_by,
  potential_payment_kobo
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, state_id, election_group_id, party_id, role_type, assigned_by, arrived_at, arrival_video_url, potential_payment_kobo, earned_amount_kobo, created_at, updated_at
`

type CreateStateSupervisorParams struct {
	UserID               int64       `json:"user_id"`
	StateID              int16       `json:"state_id"`
	ElectionGroupID      int64       `json:"election_group_id"`
	PartyID              int16       `json:"party_id"`
	RoleType             pgtype.Text `json:"role_type"`
	AssignedBy           pgtype.Int8 `json:"assigned_by"`
	PotentialPaymentKobo int64       `json:"potential_payment_kobo"`
}

func (q *Queries) CreateStateSupervisor(ctx context.Context, arg CreateStateSupervisorParams) (StateElectionSupervisor, error) {
	row := q.db.QueryRow(ctx, createStateSupervisor,
		arg.UserID,
		arg.StateID,
		arg.ElectionGroupID,
		arg.PartyID,
		arg.RoleType,
		arg.AssignedBy,
		arg.PotentialPaymentKobo,
	)
	var i StateElectionSupervisor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StateID,
		&i.ElectionGroupID,
		&i.PartyID,
		&i.RoleType,
		&i.AssignedBy,
		&i.ArrivedAt,
		&i.ArrivalVideoUrl,
		&i.PotentialPaymentKobo,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWardSupervisor = `-- name: CreateWardSupervisor :one
INSERT INTO ward_election_supervisors (
  user_id,
  state_id,
  lga_id,
  ward_id,
  election_group_id,
  party_id,
  role_type,
  assigned_by,
  potential_payment_kobo
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, state_id, lga_id, ward_id, election_group_id, party_id, role_type, assigned_by, arrived_at, arrival_video_url, potential_payment_kobo, earned_amount_kobo, created_at, updated_at
`

type CreateWardSupervisorParams struct {
	UserID               int64       `json:"user_id"`
	StateID              int16       `json:"state_id"`
	LgaID                int32       `json:"lga_id"`
	WardID               int32       `json:"ward_id"`
	ElectionGroupID      int64       `json:"election_group_id"`
	PartyID              int16       `json:"party_id"`
	RoleType             pgtype.Text `json:"role_type"`
	AssignedBy           pgtype.Int8 `json:"assigned_by"`
	PotentialPaymentKobo int64       `json:"potential_payment_kobo"`
}

func (q *Queries) CreateWardSupervisor(ctx context.Context, arg CreateWardSupervisorParams) (WardElectionSupervisor, error) {
	row := q.db.QueryRow(ctx, createWardSupervisor,
		arg.UserID,
		arg.StateID,
		arg.LgaID,
		arg.WardID,
		arg.ElectionGroupID,
		arg.PartyID,
		arg.RoleType,
		arg.AssignedBy,
		arg.PotentialPaymentKobo,
	)
	var i WardElectionSupervisor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StateID,
		&i.LgaID,
		&i.WardID,
		&i.ElectionGroupID,
		&i.PartyID,
		&i.RoleType,
		&i.AssignedBy,
		&i.ArrivedAt,
		&i.ArrivalVideoUrl,
		&i.PotentialPaymentKobo,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLgaSupervisorByElectionGroup = `-- name: GetLgaSupervisorByElectionGroup :one
SELECT id, user_id, state_id, lga_id, election_group_id, party_id, role_type, assigned_by, arrived_at, arrival_video_url, potential_payment_kobo, earned_amount_kobo, created_at, updated_at FROM lga_election_supervisors 
WHERE user_id = $1 AND election_group_id = $2 LIMIT 1
`

type GetLgaSupervisorByElectionGroupParams struct {
	UserID          int64 `json:"user_id"`
	ElectionGroupID int64 `json:"election_group_id"`
}

func (q *Queries) GetLgaSupervisorByElectionGroup(ctx context.Context, arg GetLgaSupervisorByElectionGroupParams) (LgaElectionSupervisor, error) {
	row := q.db.QueryRow(ctx, getLgaSupervisorByElectionGroup, arg.UserID, arg.ElectionGroupID)
	var i LgaElectionSupervisor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StateID,
		&i.LgaID,
		&i.ElectionGroupID,
		&i.PartyID,
		&i.RoleType,
		&i.AssignedBy,
		&i.ArrivedAt,
		&i.ArrivalVideoUrl,
		&i.PotentialPaymentKobo,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStateSupervisorByElectionGroup = `-- name: GetStateSupervisorByElectionGroup :one
SELECT id, user_id, state_id, election_group_id, party_id, role_type, assigned_by, arrived_at, arrival_video_url, potential_payment_kobo, earned_amount_kobo, created_at, updated_at FROM state_election_supervisors 
WHERE user_id = $1 AND election_group_id = $2 LIMIT 1
`

type GetStateSupervisorByElectionGroupParams struct {
	UserID          int64 `json:"user_id"`
	ElectionGroupID int64 `json:"election_group_id"`
}

func (q *Queries) GetStateSupervisorByElectionGroup(ctx context.Context, arg GetStateSupervisorByElectionGroupParams) (StateElectionSupervisor, error) {
	row := q.db.QueryRow(ctx, getStateSupervisorByElectionGroup, arg.UserID, arg.ElectionGroupID)
	var i StateElectionSupervisor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StateID,
		&i.ElectionGroupID,
		&i.PartyID,
		&i.RoleType,
		&i.AssignedBy,
		&i.ArrivedAt,
		&i.ArrivalVideoUrl,
		&i.PotentialPaymentKobo,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWardSupervisorByElectionGroup = `-- name: GetWardSupervisorByElectionGroup :one
SELECT id, user_id, state_id, lga_id, ward_id, election_group_id, party_id, role_type, assigned_by, arrived_at, arrival_video_url, potential_payment_kobo, earned_amount_kobo, created_at, updated_at FROM ward_election_supervisors 
WHERE user_id = $1 AND election_group_id = $2 LIMIT 1
`

type GetWardSupervisorByElectionGroupParams struct {
	UserID          int64 `json:"user_id"`
	ElectionGroupID int64 `json:"election_group_id"`
}

func (q *Queries) GetWardSupervisorByElectionGroup(ctx context.Context, arg GetWardSupervisorByElectionGroupParams) (WardElectionSupervisor, error) {
	row := q.db.QueryRow(ctx, getWardSupervisorByElectionGroup, arg.UserID, arg.ElectionGroupID)
	var i WardElectionSupervisor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StateID,
		&i.LgaID,
		&i.WardID,
		&i.ElectionGroupID,
		&i.PartyID,
		&i.RoleType,
		&i.AssignedBy,
		&i.ArrivedAt,
		&i.ArrivalVideoUrl,
		&i.PotentialPaymentKobo,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLgaSupervisorEarnedAmountKobo = `-- name: UpdateLgaSupervisorEarnedAmountKobo :one
UPDATE lga_election_supervisors
SET earned_amount_kobo = earned_amount_kobo + $1::bigint,
    updated_at = NOW()
WHERE user_id = $2 AND election_group_id = $3
RETURNING id, user_id, state_id, lga_id, election_group_id, party_id, role_type, assigned_by, arrived_at, arrival_video_url, potential_payment_kobo, earned_amount_kobo, created_at, updated_at
`

type UpdateLgaSupervisorEarnedAmountKoboParams struct {
	EarnedDeltaKobo int64 `json:"earned_delta_kobo"`
	UserID          int64 `json:"user_id"`
	ElectionGroupID int64 `json:"election_group_id"`
}

func (q *Queries) UpdateLgaSupervisorEarnedAmountKobo(ctx context.Context, arg UpdateLgaSupervisorEarnedAmountKoboParams) (LgaElectionSupervisor, error) {
	row := q.db.QueryRow(ctx, updateLgaSupervisorEarnedAmountKobo, arg.EarnedDeltaKobo, arg.UserID, arg.ElectionGroupID)
	var i LgaElectionSupervisor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StateID,
		&i.LgaID,
		&i.ElectionGroupID,
		&i.PartyID,
		&i.RoleType,
		&i.AssignedBy,
		&i.ArrivedAt,
		&i.ArrivalVideoUrl,
		&i.PotentialPaymentKobo,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStateSupervisorEarnedAmountKobo = `-- name: UpdateStateSupervisorEarnedAmountKobo :one
UPDATE state_election_supervisors
SET earned_amount_kobo = earned_amount_kobo + $1::bigint,
    updated_at = NOW()
WHERE user_id = $2 AND election_group_id = $3
RETURNING id, user_id, state_id, election_group_id, party_id, role_type, assigned_by, arrived_at, arrival_video_url, potential_payment_kobo, earned_amount_kobo, created_at, updated_at
`

type UpdateStateSupervisorEarnedAmountKoboParams struct {
	EarnedDeltaKobo int64 `json:"earned_delta_kobo"`
	UserID          int64 `json:"user_id"`
	ElectionGroupID int64 `json:"election_group_id"`
}

func (q *Queries) UpdateStateSupervisorEarnedAmountKobo(ctx context.Context, arg UpdateStateSupervisorEarnedAmountKoboParams) (StateElectionSupervisor, error) {
	row := q.db.QueryRow(ctx, updateStateSupervisorEarnedAmountKobo, arg.EarnedDeltaKobo, arg.UserID, arg.ElectionGroupID)
	var i StateElectionSupervisor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StateID,
		&i.ElectionGroupID,
		&i.PartyID,
		&i.RoleType,
		&i.AssignedBy,
		&i.ArrivedAt,
		&i.ArrivalVideoUrl,
		&i.PotentialPaymentKobo,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWardSupervisorEarnedAmountKobo = `-- name: UpdateWardSupervisorEarnedAmountKobo :one
UPDATE ward_election_supervisors
SET earned_amount_kobo = earned_amount_kobo + $1::bigint,
    updated_at = NOW()
WHERE user_id = $2 AND election_group_id = $3
RETURNING id, user_id, state_id, lga_id, ward_id, election_group_id, party_id, role_type, assigned_by, arrived_at, arrival_video_url, potential_payment_kobo, earned_amount_kobo, created_at, updated_at
`

type UpdateWardSupervisorEarnedAmountKoboParams struct {
	EarnedDeltaKobo int64 `json:"earned_delta_kobo"`
	UserID          int64 `json:"user_id"`
	ElectionGroupID int64 `json:"election_group_id"`
}

func (q *Queries) UpdateWardSupervisorEarnedAmountKobo(ctx context.Context, arg UpdateWardSupervisorEarnedAmountKoboParams) (WardElectionSupervisor, error) {
	row := q.db.QueryRow(ctx, updateWardSupervisorEarnedAmountKobo, arg.EarnedDeltaKobo, arg.UserID, arg.ElectionGroupID)
	var i WardElectionSupervisor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StateID,
		&i.LgaID,
		&i.WardID,
		&i.ElectionGroupID,
		&i.PartyID,
		&i.RoleType,
		&i.AssignedBy,
		&i.ArrivedAt,
		&i.ArrivalVideoUrl,
		&i.PotentialPaymentKobo,
		&i.EarnedAmountKobo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
