// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_wallets.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserWallet = `-- name: CreateUserWallet :one
INSERT INTO user_wallets (user_id, account_reference, account_numbers)
VALUES ($1, $2, $3)
RETURNING id, user_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at
`

type CreateUserWalletParams struct {
	UserID           int64  `json:"user_id"`
	AccountReference string `json:"account_reference"`
	AccountNumbers   []byte `json:"account_numbers"`
}

func (q *Queries) CreateUserWallet(ctx context.Context, arg CreateUserWalletParams) (UserWallet, error) {
	row := q.db.QueryRow(ctx, createUserWallet, arg.UserID, arg.AccountReference, arg.AccountNumbers)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWalletTransaction = `-- name: CreateUserWalletTransaction :one
INSERT INTO user_wallet_transactions (
  wallet_id,
  transaction_reference,
  type,
  amount_kobo,
  balance_after_kobo,
  payer_name,
  payer_account_number,
  payer_bank_code,
  narration,
  raw_payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, wallet_id, transaction_reference, type, amount_kobo, balance_after_kobo, payer_name, payer_account_number, payer_bank_code, narration, raw_payload, created_at
`

type CreateUserWalletTransactionParams struct {
	WalletID             int64       `json:"wallet_id"`
	TransactionReference string      `json:"transaction_reference"`
	Type                 string      `json:"type"`
	AmountKobo           int64       `json:"amount_kobo"`
	BalanceAfterKobo     int64       `json:"balance_after_kobo"`
	PayerName            pgtype.Text `json:"payer_name"`
	PayerAccountNumber   pgtype.Text `json:"payer_account_number"`
	PayerBankCode        pgtype.Text `json:"payer_bank_code"`
	Narration            pgtype.Text `json:"narration"`
	RawPayload           []byte      `json:"raw_payload"`
}

func (q *Queries) CreateUserWalletTransaction(ctx context.Context, arg CreateUserWalletTransactionParams) (UserWalletTransaction, error) {
	row := q.db.QueryRow(ctx, createUserWalletTransaction,
		arg.WalletID,
		arg.TransactionReference,
		arg.Type,
		arg.AmountKobo,
		arg.BalanceAfterKobo,
		arg.PayerName,
		arg.PayerAccountNumber,
		arg.PayerBankCode,
		arg.Narration,
		arg.RawPayload,
	)
	var i UserWalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TransactionReference,
		&i.Type,
		&i.AmountKobo,
		&i.BalanceAfterKobo,
		&i.PayerName,
		&i.PayerAccountNumber,
		&i.PayerBankCode,
		&i.Narration,
		&i.RawPayload,
		&i.CreatedAt,
	)
	return i, err
}

const creditUserWallet = `-- name: CreditUserWallet :one
UPDATE user_wallets
SET balance_kobo = balance_kobo + $1,
    updated_at   = NOW()
WHERE id = $2
RETURNING id, user_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at
`

type CreditUserWalletParams struct {
	BalanceKobo int64 `json:"balance_kobo"`
	ID          int64 `json:"id"`
}

func (q *Queries) CreditUserWallet(ctx context.Context, arg CreditUserWalletParams) (UserWallet, error) {
	row := q.db.QueryRow(ctx, creditUserWallet, arg.BalanceKobo, arg.ID)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const debitUserWallet = `-- name: DebitUserWallet :one
UPDATE user_wallets
SET balance_kobo = balance_kobo - $1,
    updated_at   = NOW()
WHERE id = $2 AND balance_kobo >= $1
RETURNING id, user_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at
`

type DebitUserWalletParams struct {
	BalanceKobo int64 `json:"balance_kobo"`
	ID          int64 `json:"id"`
}

func (q *Queries) DebitUserWallet(ctx context.Context, arg DebitUserWalletParams) (UserWallet, error) {
	row := q.db.QueryRow(ctx, debitUserWallet, arg.BalanceKobo, arg.ID)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWalletByAccountReference = `-- name: GetUserWalletByAccountReference :one
SELECT id, user_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at FROM user_wallets WHERE account_reference = $1
`

func (q *Queries) GetUserWalletByAccountReference(ctx context.Context, accountReference string) (UserWallet, error) {
	row := q.db.QueryRow(ctx, getUserWalletByAccountReference, accountReference)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWalletByID = `-- name: GetUserWalletByID :one
SELECT id, user_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at FROM user_wallets WHERE id = $1
`

func (q *Queries) GetUserWalletByID(ctx context.Context, id int64) (UserWallet, error) {
	row := q.db.QueryRow(ctx, getUserWalletByID, id)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWalletByUserID = `-- name: GetUserWalletByUserID :one
SELECT id, user_id, account_reference, account_numbers, balance_kobo, currency_code, status, created_at, updated_at FROM user_wallets WHERE user_id = $1
`

func (q *Queries) GetUserWalletByUserID(ctx context.Context, userID int64) (UserWallet, error) {
	row := q.db.QueryRow(ctx, getUserWalletByUserID, userID)
	var i UserWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountReference,
		&i.AccountNumbers,
		&i.BalanceKobo,
		&i.CurrencyCode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWalletTransactionByReference = `-- name: GetUserWalletTransactionByReference :one
SELECT id, wallet_id, transaction_reference, type, amount_kobo, balance_after_kobo, payer_name, payer_account_number, payer_bank_code, narration, raw_payload, created_at FROM user_wallet_transactions
WHERE transaction_reference = $1
`

func (q *Queries) GetUserWalletTransactionByReference(ctx context.Context, transactionReference string) (UserWalletTransaction, error) {
	row := q.db.QueryRow(ctx, getUserWalletTransactionByReference, transactionReference)
	var i UserWalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TransactionReference,
		&i.Type,
		&i.AmountKobo,
		&i.BalanceAfterKobo,
		&i.PayerName,
		&i.PayerAccountNumber,
		&i.PayerBankCode,
		&i.Narration,
		&i.RawPayload,
		&i.CreatedAt,
	)
	return i, err
}

const listUserWalletTransactions = `-- name: ListUserWalletTransactions :many
SELECT id, wallet_id, transaction_reference, type, amount_kobo, balance_after_kobo, payer_name, payer_account_number, payer_bank_code, narration, raw_payload, created_at FROM user_wallet_transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserWalletTransactionsParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListUserWalletTransactions(ctx context.Context, arg ListUserWalletTransactionsParams) ([]UserWalletTransaction, error) {
	rows, err := q.db.Query(ctx, listUserWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWalletTransaction
	for rows.Next() {
		var i UserWalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TransactionReference,
			&i.Type,
			&i.AmountKobo,
			&i.BalanceAfterKobo,
			&i.PayerName,
			&i.PayerAccountNumber,
			&i.PayerBankCode,
			&i.Narration,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithoutWallet = `-- name: ListUsersWithoutWallet :many
SELECT u.id, u.fake_id, u.email, u.avatar, u.phone, u.username, u.password_hash, u.last_name, u.first_name, u.middle_name, u.gender, u.date_of_birth, u.voters_card_image, u.current_country, u.current_state, u.current_city, u.current_lga, u.current_ward, u.address, u.state_of_origin, u.is_politician, u.is_verified, u.has_role, u.party_id, u.polling_unit_id, u.referral_code, u.referred_by_id, u.account_status, u.created_at, u.updated_at FROM users u 
LEFT JOIN user_wallets uw ON uw.user_id = u.id
WHERE uw.id IS NULL
ORDER BY u.id ASC
`

type ListUsersWithoutWalletRow struct {
	ID              int64              `json:"id"`
	FakeID          pgtype.Int8        `json:"fake_id"`
	Email           pgtype.Text        `json:"email"`
	Avatar          pgtype.Text        `json:"avatar"`
	Phone           pgtype.Text        `json:"phone"`
	Username        pgtype.Text        `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	LastName        pgtype.Text        `json:"last_name"`
	FirstName       pgtype.Text        `json:"first_name"`
	MiddleName      pgtype.Text        `json:"middle_name"`
	Gender          pgtype.Text        `json:"gender"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	VotersCardImage pgtype.Text        `json:"voters_card_image"`
	CurrentCountry  int16              `json:"current_country"`
	CurrentState    int16              `json:"current_state"`
	CurrentCity     pgtype.Int4        `json:"current_city"`
	CurrentLga      pgtype.Int4        `json:"current_lga"`
	CurrentWard     pgtype.Int4        `json:"current_ward"`
	Address         pgtype.Text        `json:"address"`
	StateOfOrigin   pgtype.Int2        `json:"state_of_origin"`
	IsPolitician    pgtype.Bool        `json:"is_politician"`
	IsVerified      pgtype.Bool        `json:"is_verified"`
	HasRole         pgtype.Bool        `json:"has_role"`
	PartyID         pgtype.Int2        `json:"party_id"`
	PollingUnitID   pgtype.Int4        `json:"polling_unit_id"`
	ReferralCode    pgtype.Text        `json:"referral_code"`
	ReferredByID    pgtype.Int8        `json:"referred_by_id"`
	AccountStatus   pgtype.Text        `json:"account_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsersWithoutWallet(ctx context.Context) ([]ListUsersWithoutWalletRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithoutWallet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithoutWalletRow
	for rows.Next() {
		var i ListUsersWithoutWalletRow
		if err := rows.Scan(
			&i.ID,
			&i.FakeID,
			&i.Email,
			&i.Avatar,
			&i.Phone,
			&i.Username,
			&i.PasswordHash,
			&i.LastName,
			&i.FirstName,
			&i.MiddleName,
			&i.Gender,
			&i.DateOfBirth,
			&i.VotersCardImage,
			&i.CurrentCountry,
			&i.CurrentState,
			&i.CurrentCity,
			&i.CurrentLga,
			&i.CurrentWard,
			&i.Address,
			&i.StateOfOrigin,
			&i.IsPolitician,
			&i.IsVerified,
			&i.HasRole,
			&i.PartyID,
			&i.PollingUnitID,
			&i.ReferralCode,
			&i.ReferredByID,
			&i.AccountStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
