// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminUpdateUser = `-- name: AdminUpdateUser :exec
UPDATE users
SET first_name = $2,
    last_name = $3,
    middle_name = $4,
    username = $5,
    gender = $6,
    avatar = $7,
    avatar_file_id = $8,
    current_country = $9,
    current_state = $10,
    current_city = $11,
    state_of_origin = $12,
    updated_at = NOW()
WHERE id = $1
`

type AdminUpdateUserParams struct {
	ID             int64       `json:"id"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	Username       pgtype.Text `json:"username"`
	Gender         pgtype.Text `json:"gender"`
	Avatar         pgtype.Text `json:"avatar"`
	AvatarFileID   pgtype.Int8 `json:"avatar_file_id"`
	CurrentCountry int16       `json:"current_country"`
	CurrentState   int16       `json:"current_state"`
	CurrentCity    pgtype.Int4 `json:"current_city"`
	StateOfOrigin  pgtype.Int2 `json:"state_of_origin"`
}

func (q *Queries) AdminUpdateUser(ctx context.Context, arg AdminUpdateUserParams) error {
	_, err := q.db.Exec(ctx, adminUpdateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Username,
		arg.Gender,
		arg.Avatar,
		arg.AvatarFileID,
		arg.CurrentCountry,
		arg.CurrentState,
		arg.CurrentCity,
		arg.StateOfOrigin,
	)
	return err
}

const checkReferralCodeExists = `-- name: CheckReferralCodeExists :one
SELECT EXISTS(
    SELECT 1 FROM users
    WHERE referral_code = $1
)
`

func (q *Queries) CheckReferralCodeExists(ctx context.Context, referralCode pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkReferralCodeExists, referralCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAllUserPhoneNumbers = `-- name: CountAllUserPhoneNumbers :one
SELECT COUNT(*) FROM users_phone_numbers
WHERE user_id = $1
`

func (q *Queries) CountAllUserPhoneNumbers(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUserPhoneNumbers, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCandidatePlaceholder = `-- name: CreateCandidatePlaceholder :one
INSERT INTO users (
  email, password_hash, username, last_name, first_name, middle_name,
  gender, date_of_birth, current_country, current_state, current_city, state_of_origin,
  party_id, avatar, avatar_file_id, account_status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, 'placeholder')
RETURNING id
`

type CreateCandidatePlaceholderParams struct {
	Email          pgtype.Text `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	Username       pgtype.Text `json:"username"`
	LastName       pgtype.Text `json:"last_name"`
	FirstName      pgtype.Text `json:"first_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	Gender         pgtype.Text `json:"gender"`
	DateOfBirth    pgtype.Date `json:"date_of_birth"`
	CurrentCountry int16       `json:"current_country"`
	CurrentState   int16       `json:"current_state"`
	CurrentCity    pgtype.Int4 `json:"current_city"`
	StateOfOrigin  pgtype.Int2 `json:"state_of_origin"`
	PartyID        pgtype.Int2 `json:"party_id"`
	Avatar         pgtype.Text `json:"avatar"`
	AvatarFileID   pgtype.Int8 `json:"avatar_file_id"`
}

func (q *Queries) CreateCandidatePlaceholder(ctx context.Context, arg CreateCandidatePlaceholderParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCandidatePlaceholder,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Gender,
		arg.DateOfBirth,
		arg.CurrentCountry,
		arg.CurrentState,
		arg.CurrentCity,
		arg.StateOfOrigin,
		arg.PartyID,
		arg.Avatar,
		arg.AvatarFileID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMoreInfoAboutThisUser = `-- name: CreateMoreInfoAboutThisUser :one
INSERT INTO user_more_infos (
  user_id, occupation_id, educational_status, highest_degree, graduation_year, school_name, religion, marital_status, address
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING user_id
`

type CreateMoreInfoAboutThisUserParams struct {
	UserID            int64       `json:"user_id"`
	OccupationID      pgtype.Int2 `json:"occupation_id"`
	EducationalStatus pgtype.Text `json:"educational_status"`
	HighestDegree     pgtype.Text `json:"highest_degree"`
	GraduationYear    pgtype.Text `json:"graduation_year"`
	SchoolName        pgtype.Text `json:"school_name"`
	Religion          pgtype.Text `json:"religion"`
	MaritalStatus     pgtype.Text `json:"marital_status"`
	Address           pgtype.Text `json:"address"`
}

func (q *Queries) CreateMoreInfoAboutThisUser(ctx context.Context, arg CreateMoreInfoAboutThisUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMoreInfoAboutThisUser,
		arg.UserID,
		arg.OccupationID,
		arg.EducationalStatus,
		arg.HighestDegree,
		arg.GraduationYear,
		arg.SchoolName,
		arg.Religion,
		arg.MaritalStatus,
		arg.Address,
	)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createPhoneNumber = `-- name: CreatePhoneNumber :one
INSERT INTO users_phone_numbers (user_id, phone, phonecode, raw_input, on_whatsapp, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreatePhoneNumberParams struct {
	UserID     int64       `json:"user_id"`
	Phone      string      `json:"phone"`
	Phonecode  string      `json:"phonecode"`
	RawInput   string      `json:"raw_input"`
	OnWhatsapp pgtype.Bool `json:"on_whatsapp"`
	IsDefault  pgtype.Bool `json:"is_default"`
}

func (q *Queries) CreatePhoneNumber(ctx context.Context, arg CreatePhoneNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPhoneNumber,
		arg.UserID,
		arg.Phone,
		arg.Phonecode,
		arg.RawInput,
		arg.OnWhatsapp,
		arg.IsDefault,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, phone, username, password_hash, last_name,
  first_name, middle_name, gender, date_of_birth, current_country,
  current_state, current_city
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type CreateUserParams struct {
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	Username       pgtype.Text `json:"username"`
	PasswordHash   string      `json:"password_hash"`
	LastName       pgtype.Text `json:"last_name"`
	FirstName      pgtype.Text `json:"first_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	Gender         pgtype.Text `json:"gender"`
	DateOfBirth    pgtype.Date `json:"date_of_birth"`
	CurrentCountry int16       `json:"current_country"`
	CurrentState   int16       `json:"current_state"`
	CurrentCity    pgtype.Int4 `json:"current_city"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Phone,
		arg.Username,
		arg.PasswordHash,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Gender,
		arg.DateOfBirth,
		arg.CurrentCountry,
		arg.CurrentState,
		arg.CurrentCity,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserNIN = `-- name: CreateUserNIN :one
INSERT INTO users_nin (user_id, nin)
VALUES ($1, $2)
RETURNING id
`

type CreateUserNINParams struct {
	UserID int64  `json:"user_id"`
	Nin    string `json:"nin"`
}

func (q *Queries) CreateUserNIN(ctx context.Context, arg CreateUserNINParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUserNIN, arg.UserID, arg.Nin)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserVerification = `-- name: CreateUserVerification :one
INSERT INTO user_verifications (user_id, nin_verified, phone_verified, email_verified, voters_card_verified)
VALUES ($1, $2, $3, $4, $5)
RETURNING user_id
`

type CreateUserVerificationParams struct {
	UserID             int64       `json:"user_id"`
	NinVerified        pgtype.Bool `json:"nin_verified"`
	PhoneVerified      pgtype.Bool `json:"phone_verified"`
	EmailVerified      pgtype.Bool `json:"email_verified"`
	VotersCardVerified pgtype.Bool `json:"voters_card_verified"`
}

func (q *Queries) CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUserVerification,
		arg.UserID,
		arg.NinVerified,
		arg.PhoneVerified,
		arg.EmailVerified,
		arg.VotersCardVerified,
	)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET account_status = 'deleted'
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserPhoneNumber = `-- name: DeleteUserPhoneNumber :exec
DELETE FROM users_phone_numbers
WHERE id = $1 AND user_id = $2
`

type DeleteUserPhoneNumberParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteUserPhoneNumber(ctx context.Context, arg DeleteUserPhoneNumberParams) error {
	_, err := q.db.Exec(ctx, deleteUserPhoneNumber, arg.ID, arg.UserID)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getFakeIDByAdditionalPhone = `-- name: GetFakeIDByAdditionalPhone :one
SELECT u.fake_id
FROM users u
JOIN users_phone_numbers upn ON u.id = upn.user_id
WHERE upn.phone = $1 LIMIT 1
`

func (q *Queries) GetFakeIDByAdditionalPhone(ctx context.Context, phone string) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getFakeIDByAdditionalPhone, phone)
	var fake_id pgtype.Int8
	err := row.Scan(&fake_id)
	return fake_id, err
}

const getFakeIDByEmail = `-- name: GetFakeIDByEmail :one
SELECT fake_id FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetFakeIDByEmail(ctx context.Context, email pgtype.Text) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getFakeIDByEmail, email)
	var fake_id pgtype.Int8
	err := row.Scan(&fake_id)
	return fake_id, err
}

const getFakeIDByPhone = `-- name: GetFakeIDByPhone :one
SELECT fake_id FROM users
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetFakeIDByPhone(ctx context.Context, phone pgtype.Text) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getFakeIDByPhone, phone)
	var fake_id pgtype.Int8
	err := row.Scan(&fake_id)
	return fake_id, err
}

const getFakeIDByUserID = `-- name: GetFakeIDByUserID :one
SELECT fake_id FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFakeIDByUserID(ctx context.Context, id int64) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getFakeIDByUserID, id)
	var fake_id pgtype.Int8
	err := row.Scan(&fake_id)
	return fake_id, err
}

const getFakeIDByUsername = `-- name: GetFakeIDByUsername :one
SELECT fake_id FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetFakeIDByUsername(ctx context.Context, username pgtype.Text) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getFakeIDByUsername, username)
	var fake_id pgtype.Int8
	err := row.Scan(&fake_id)
	return fake_id, err
}

const getMoreInfoAboutThisUser = `-- name: GetMoreInfoAboutThisUser :one
SELECT user_id, occupation_id, educational_status, highest_degree, graduation_year, school_name, degree_certificate_url, religion, marital_status, address, created_at, updated_at FROM user_more_infos
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetMoreInfoAboutThisUser(ctx context.Context, userID int64) (UserMoreInfo, error) {
	row := q.db.QueryRow(ctx, getMoreInfoAboutThisUser, userID)
	var i UserMoreInfo
	err := row.Scan(
		&i.UserID,
		&i.OccupationID,
		&i.EducationalStatus,
		&i.HighestDegree,
		&i.GraduationYear,
		&i.SchoolName,
		&i.DegreeCertificateUrl,
		&i.Religion,
		&i.MaritalStatus,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReferrerNameByCode = `-- name: GetReferrerNameByCode :one
SELECT id, first_name, last_name 
FROM users
WHERE referral_code = $1 LIMIT 1
`

type GetReferrerNameByCodeRow struct {
	ID        int64       `json:"id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
}

func (q *Queries) GetReferrerNameByCode(ctx context.Context, referralCode pgtype.Text) (GetReferrerNameByCodeRow, error) {
	row := q.db.QueryRow(ctx, getReferrerNameByCode, referralCode)
	var i GetReferrerNameByCodeRow
	err := row.Scan(&i.ID, &i.FirstName, &i.LastName)
	return i, err
}

const getUserByFakeID = `-- name: GetUserByFakeID :one
SELECT u.id, u.fake_id, u.email, u.avatar, u.avatar_file_id, u.phone, u.username, u.password_hash, u.last_name, u.first_name, u.middle_name, u.gender, u.date_of_birth, u.voters_card_image, u.current_country, u.current_state, u.current_city, u.current_lga, u.current_ward, u.country_of_origin, u.state_of_origin, u.is_politician, u.is_verified, u.has_role, u.party_id, u.polling_unit_id, u.account_status, u.created_at, u.updated_at,
       u.referral_code
FROM users u
WHERE u.fake_id = $1 LIMIT 1
`

type GetUserByFakeIDRow struct {
	ID              int64              `json:"id"`
	FakeID          pgtype.Int8        `json:"fake_id"`
	Email           pgtype.Text        `json:"email"`
	Avatar          pgtype.Text        `json:"avatar"`
	AvatarFileID    pgtype.Int8        `json:"avatar_file_id"`
	Phone           pgtype.Text        `json:"phone"`
	Username        pgtype.Text        `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	LastName        pgtype.Text        `json:"last_name"`
	FirstName       pgtype.Text        `json:"first_name"`
	MiddleName      pgtype.Text        `json:"middle_name"`
	Gender          pgtype.Text        `json:"gender"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	VotersCardImage pgtype.Text        `json:"voters_card_image"`
	CurrentCountry  int16              `json:"current_country"`
	CurrentState    int16              `json:"current_state"`
	CurrentCity     pgtype.Int4        `json:"current_city"`
	CurrentLga      pgtype.Int4        `json:"current_lga"`
	CurrentWard     pgtype.Int4        `json:"current_ward"`
	CountryOfOrigin pgtype.Int2        `json:"country_of_origin"`
	StateOfOrigin   pgtype.Int2        `json:"state_of_origin"`
	IsPolitician    pgtype.Bool        `json:"is_politician"`
	IsVerified      pgtype.Bool        `json:"is_verified"`
	HasRole         pgtype.Bool        `json:"has_role"`
	PartyID         pgtype.Int2        `json:"party_id"`
	PollingUnitID   pgtype.Int4        `json:"polling_unit_id"`
	AccountStatus   pgtype.Text        `json:"account_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReferralCode    pgtype.Text        `json:"referral_code"`
}

func (q *Queries) GetUserByFakeID(ctx context.Context, fakeID pgtype.Int8) (GetUserByFakeIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByFakeID, fakeID)
	var i GetUserByFakeIDRow
	err := row.Scan(
		&i.ID,
		&i.FakeID,
		&i.Email,
		&i.Avatar,
		&i.AvatarFileID,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.VotersCardImage,
		&i.CurrentCountry,
		&i.CurrentState,
		&i.CurrentCity,
		&i.CurrentLga,
		&i.CurrentWard,
		&i.CountryOfOrigin,
		&i.StateOfOrigin,
		&i.IsPolitician,
		&i.IsVerified,
		&i.HasRole,
		&i.PartyID,
		&i.PollingUnitID,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralCode,
	)
	return i, err
}

const getUserIDByNIN = `-- name: GetUserIDByNIN :one
SELECT user_id
FROM users_nin
WHERE nin = $1 LIMIT 1
`

func (q *Queries) GetUserIDByNIN(ctx context.Context, nin string) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIDByNIN, nin)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.fake_id, u.email, u.avatar, u.avatar_file_id, u.phone, u.username, u.password_hash, u.last_name, u.first_name, u.middle_name, u.gender, u.date_of_birth, u.voters_card_image, u.current_country, u.current_state, u.current_city, u.current_lga, u.current_ward, u.address, u.country_of_origin, u.state_of_origin, u.is_politician, u.is_verified, u.has_role, u.party_id, u.polling_unit_id, u.account_status, u.created_at, u.updated_at,
       u.referral_code, u.referred_by_id
FROM users u
WHERE u.id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID              int64              `json:"id"`
	FakeID          pgtype.Int8        `json:"fake_id"`
	Email           pgtype.Text        `json:"email"`
	Avatar          pgtype.Text        `json:"avatar"`
	AvatarFileID    pgtype.Int8        `json:"avatar_file_id"`
	Phone           pgtype.Text        `json:"phone"`
	Username        pgtype.Text        `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	LastName        pgtype.Text        `json:"last_name"`
	FirstName       pgtype.Text        `json:"first_name"`
	MiddleName      pgtype.Text        `json:"middle_name"`
	Gender          pgtype.Text        `json:"gender"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	VotersCardImage pgtype.Text        `json:"voters_card_image"`
	CurrentCountry  int16              `json:"current_country"`
	CurrentState    int16              `json:"current_state"`
	CurrentCity     pgtype.Int4        `json:"current_city"`
	CurrentLga      pgtype.Int4        `json:"current_lga"`
	CurrentWard     pgtype.Int4        `json:"current_ward"`
	Address         pgtype.Text        `json:"address"`
	CountryOfOrigin pgtype.Int2        `json:"country_of_origin"`
	StateOfOrigin   pgtype.Int2        `json:"state_of_origin"`
	IsPolitician    pgtype.Bool        `json:"is_politician"`
	IsVerified      pgtype.Bool        `json:"is_verified"`
	HasRole         pgtype.Bool        `json:"has_role"`
	PartyID         pgtype.Int2        `json:"party_id"`
	PollingUnitID   pgtype.Int4        `json:"polling_unit_id"`
	AccountStatus   pgtype.Text        `json:"account_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ReferralCode    pgtype.Text        `json:"referral_code"`
	ReferredByID    pgtype.Int8        `json:"referred_by_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FakeID,
		&i.Email,
		&i.Avatar,
		&i.AvatarFileID,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.VotersCardImage,
		&i.CurrentCountry,
		&i.CurrentState,
		&i.CurrentCity,
		&i.CurrentLga,
		&i.CurrentWard,
		&i.Address,
		&i.CountryOfOrigin,
		&i.StateOfOrigin,
		&i.IsPolitician,
		&i.IsVerified,
		&i.HasRole,
		&i.PartyID,
		&i.PollingUnitID,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReferralCode,
		&i.ReferredByID,
	)
	return i, err
}

const getUserIdByReferralCode = `-- name: GetUserIdByReferralCode :one
SELECT id FROM users
WHERE referral_code = $1 LIMIT 1
`

func (q *Queries) GetUserIdByReferralCode(ctx context.Context, referralCode pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIdByReferralCode, referralCode)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserNINByUserID = `-- name: GetUserNINByUserID :one
SELECT id, user_id, nin FROM users_nin
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserNINByUserID(ctx context.Context, userID int64) (UsersNin, error) {
	row := q.db.QueryRow(ctx, getUserNINByUserID, userID)
	var i UsersNin
	err := row.Scan(&i.ID, &i.UserID, &i.Nin)
	return i, err
}

const getUserPasswordHashByFakeID = `-- name: GetUserPasswordHashByFakeID :one
SELECT password_hash FROM users
WHERE fake_id = $1 LIMIT 1
`

func (q *Queries) GetUserPasswordHashByFakeID(ctx context.Context, fakeID pgtype.Int8) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHashByFakeID, fakeID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUserPhoneNumbersByUserID = `-- name: GetUserPhoneNumbersByUserID :many
SELECT id, user_id, owner_is_verified, phone, raw_input, phonecode, on_whatsapp, is_default, is_active FROM users_phone_numbers
WHERE user_id = $1
`

func (q *Queries) GetUserPhoneNumbersByUserID(ctx context.Context, userID int64) ([]UsersPhoneNumber, error) {
	rows, err := q.db.Query(ctx, getUserPhoneNumbersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersPhoneNumber
	for rows.Next() {
		var i UsersPhoneNumber
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OwnerIsVerified,
			&i.Phone,
			&i.RawInput,
			&i.Phonecode,
			&i.OnWhatsapp,
			&i.IsDefault,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVerification = `-- name: GetUserVerification :one
SELECT user_id, nin_verified, phone_verified, email_verified, voters_card_verified, email_verification_token, email_last_reminded_at, phone_last_reminded_at, created_at, updated_at FROM user_verifications
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserVerification(ctx context.Context, userID int64) (UserVerification, error) {
	row := q.db.QueryRow(ctx, getUserVerification, userID)
	var i UserVerification
	err := row.Scan(
		&i.UserID,
		&i.NinVerified,
		&i.PhoneVerified,
		&i.EmailVerified,
		&i.VotersCardVerified,
		&i.EmailVerificationToken,
		&i.EmailLastRemindedAt,
		&i.PhoneLastRemindedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.fake_id FROM users u
WHERE 
  ($1::bigint IS NULL OR u.id < $1::bigint)
  AND ($2::smallint IS NULL OR u.party_id = $2::smallint)
  AND ($3::smallint[] IS NULL OR u.party_id = ANY($3::smallint[]))
  AND ($4::smallint[] IS NULL OR (
      u.is_verified = true AND EXISTS (
          SELECT 1 FROM pages_verified pv 
          WHERE pv.page_type = 'user' 
            AND pv.page_id = u.id 
            AND pv.verification_type_id = ANY($4::smallint[])
      )
  ))
  AND ($5::text[] IS NULL OR EXISTS (
      -- Use EXISTS instead of LEFT JOIN to avoid returning duplicate user rows 
      -- if a user somehow has multiple roles (or just to keep the base query simple).
      SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.role_code = ANY($5::text[])
  ))
  AND ($6::text IS NULL OR (
      u.first_name ILIKE '%' || $6::text || '%' OR
      u.last_name ILIKE '%' || $6::text || '%' OR
      u.username ILIKE '%' || $6::text || '%'
  ))
  AND ($7::text[] IS NULL OR u.account_status = ANY($7::text[]))
  AND ($8::smallint[] IS NULL OR u.current_country = ANY($8::smallint[]))
  AND ($9::smallint[] IS NULL OR u.current_state = ANY($9::smallint[]))
ORDER BY u.id DESC
LIMIT $10::int
`

type ListUsersParams struct {
	Cursor              pgtype.Int8 `json:"cursor"`
	PartyID             pgtype.Int2 `json:"party_id"`
	PartyIds            []int16     `json:"party_ids"`
	VerificationTypeIds []int16     `json:"verification_type_ids"`
	RoleCodes           []string    `json:"role_codes"`
	Search              pgtype.Text `json:"search"`
	AccountStatus       []string    `json:"account_status"`
	CountryIds          []int16     `json:"country_ids"`
	StateIds            []int16     `json:"state_ids"`
	LimitNum            int32       `json:"limit_num"`
}

type ListUsersRow struct {
	ID     int64       `json:"id"`
	FakeID pgtype.Int8 `json:"fake_id"`
}

// ListUsers fetches a paginated list of users with optional filtering.
// We use sqlc.narg() (nullable argument) to make filters optional:
// If a parameter like 'cursor' is not provided (null), the 'sqlc.narg('cursor')::bigint IS NULL'
// condition becomes true, effectively skipping that filter.
// This allows us to use a single dynamic query instead of writing multiple separate queries.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Cursor,
		arg.PartyID,
		arg.PartyIds,
		arg.VerificationTypeIds,
		arg.RoleCodes,
		arg.Search,
		arg.AccountStatus,
		arg.CountryIds,
		arg.StateIds,
		arg.LimitNum,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.FakeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedUser = `-- name: SeedUser :one
INSERT INTO users (
  email, avatar, phone, username, password_hash, last_name, first_name, middle_name,
  gender, date_of_birth, current_country, current_state, current_lga, current_city,
  state_of_origin, voters_card_image,
  account_status, party_id, is_politician, is_verified
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id
`

type SeedUserParams struct {
	Email           pgtype.Text `json:"email"`
	Avatar          pgtype.Text `json:"avatar"`
	Phone           pgtype.Text `json:"phone"`
	Username        pgtype.Text `json:"username"`
	PasswordHash    string      `json:"password_hash"`
	LastName        pgtype.Text `json:"last_name"`
	FirstName       pgtype.Text `json:"first_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	Gender          pgtype.Text `json:"gender"`
	DateOfBirth     pgtype.Date `json:"date_of_birth"`
	CurrentCountry  int16       `json:"current_country"`
	CurrentState    int16       `json:"current_state"`
	CurrentLga      pgtype.Int4 `json:"current_lga"`
	CurrentCity     pgtype.Int4 `json:"current_city"`
	StateOfOrigin   pgtype.Int2 `json:"state_of_origin"`
	VotersCardImage pgtype.Text `json:"voters_card_image"`
	AccountStatus   pgtype.Text `json:"account_status"`
	PartyID         pgtype.Int2 `json:"party_id"`
	IsPolitician    pgtype.Bool `json:"is_politician"`
	IsVerified      pgtype.Bool `json:"is_verified"`
}

func (q *Queries) SeedUser(ctx context.Context, arg SeedUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, seedUser,
		arg.Email,
		arg.Avatar,
		arg.Phone,
		arg.Username,
		arg.PasswordHash,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Gender,
		arg.DateOfBirth,
		arg.CurrentCountry,
		arg.CurrentState,
		arg.CurrentLga,
		arg.CurrentCity,
		arg.StateOfOrigin,
		arg.VotersCardImage,
		arg.AccountStatus,
		arg.PartyID,
		arg.IsPolitician,
		arg.IsVerified,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateMoreInfoAboutThisUser = `-- name: UpdateMoreInfoAboutThisUser :exec
INSERT INTO user_more_infos (
  user_id, occupation_id, educational_status, highest_degree, graduation_year, school_name, religion, marital_status, address
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id) DO UPDATE
SET occupation_id = EXCLUDED.occupation_id,
    educational_status = EXCLUDED.educational_status,
    highest_degree = EXCLUDED.highest_degree,
    graduation_year = EXCLUDED.graduation_year,
    school_name = EXCLUDED.school_name,
    religion = EXCLUDED.religion,
    marital_status = EXCLUDED.marital_status,
    address = EXCLUDED.address,
    updated_at = NOW()
`

type UpdateMoreInfoAboutThisUserParams struct {
	UserID            int64       `json:"user_id"`
	OccupationID      pgtype.Int2 `json:"occupation_id"`
	EducationalStatus pgtype.Text `json:"educational_status"`
	HighestDegree     pgtype.Text `json:"highest_degree"`
	GraduationYear    pgtype.Text `json:"graduation_year"`
	SchoolName        pgtype.Text `json:"school_name"`
	Religion          pgtype.Text `json:"religion"`
	MaritalStatus     pgtype.Text `json:"marital_status"`
	Address           pgtype.Text `json:"address"`
}

func (q *Queries) UpdateMoreInfoAboutThisUser(ctx context.Context, arg UpdateMoreInfoAboutThisUserParams) error {
	_, err := q.db.Exec(ctx, updateMoreInfoAboutThisUser,
		arg.UserID,
		arg.OccupationID,
		arg.EducationalStatus,
		arg.HighestDegree,
		arg.GraduationYear,
		arg.SchoolName,
		arg.Religion,
		arg.MaritalStatus,
		arg.Address,
	)
	return err
}

const updateOnboardingProfile = `-- name: UpdateOnboardingProfile :one
UPDATE users
SET username = $2,
    first_name = $3,
    last_name = $4,
    middle_name = $5,
    gender = $6,
    date_of_birth = $7,
    current_country = $8,
    current_state = $9,
    current_city = $10,
    state_of_origin = $11,
    country_of_origin = $12,
    referral_code = $13,
    account_status = 'active',
    updated_at = NOW()
WHERE id = $1
RETURNING id, fake_id, email, phone, username, password_hash, first_name, last_name, middle_name, gender, date_of_birth, avatar, avatar_file_id, voters_card_image, current_country, current_state, current_city, current_lga, current_ward, polling_unit_id, country_of_origin, state_of_origin, has_role, is_verified, is_politician, party_id, account_status, referral_code, created_at, updated_at
`

type UpdateOnboardingProfileParams struct {
	ID              int64       `json:"id"`
	Username        pgtype.Text `json:"username"`
	FirstName       pgtype.Text `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	MiddleName      pgtype.Text `json:"middle_name"`
	Gender          pgtype.Text `json:"gender"`
	DateOfBirth     pgtype.Date `json:"date_of_birth"`
	CurrentCountry  int16       `json:"current_country"`
	CurrentState    int16       `json:"current_state"`
	CurrentCity     pgtype.Int4 `json:"current_city"`
	StateOfOrigin   pgtype.Int2 `json:"state_of_origin"`
	CountryOfOrigin pgtype.Int2 `json:"country_of_origin"`
	ReferralCode    pgtype.Text `json:"referral_code"`
}

func (q *Queries) UpdateOnboardingProfile(ctx context.Context, arg UpdateOnboardingProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateOnboardingProfile,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Gender,
		arg.DateOfBirth,
		arg.CurrentCountry,
		arg.CurrentState,
		arg.CurrentCity,
		arg.StateOfOrigin,
		arg.CountryOfOrigin,
		arg.ReferralCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FakeID,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Gender,
		&i.DateOfBirth,
		&i.Avatar,
		&i.AvatarFileID,
		&i.VotersCardImage,
		&i.CurrentCountry,
		&i.CurrentState,
		&i.CurrentCity,
		&i.CurrentLga,
		&i.CurrentWard,
		&i.PollingUnitID,
		&i.CountryOfOrigin,
		&i.StateOfOrigin,
		&i.HasRole,
		&i.IsVerified,
		&i.IsPolitician,
		&i.PartyID,
		&i.AccountStatus,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :exec
UPDATE users_phone_numbers
SET on_whatsapp = $3,
    is_default = $4
WHERE id = $1 AND user_id = $2
`

type UpdatePhoneNumberParams struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	OnWhatsapp pgtype.Bool `json:"on_whatsapp"`
	IsDefault  pgtype.Bool `json:"is_default"`
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updatePhoneNumber,
		arg.ID,
		arg.UserID,
		arg.OnWhatsapp,
		arg.IsDefault,
	)
	return err
}

const updateUserAgentMoreInfo = `-- name: UpdateUserAgentMoreInfo :exec
INSERT INTO user_more_infos (
  user_id, educational_status, highest_degree, graduation_year, school_name
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET educational_status = COALESCE(EXCLUDED.educational_status, user_more_infos.educational_status),
    highest_degree = COALESCE(EXCLUDED.highest_degree, user_more_infos.highest_degree),
    graduation_year = COALESCE(EXCLUDED.graduation_year, user_more_infos.graduation_year),
    school_name = COALESCE(EXCLUDED.school_name, user_more_infos.school_name),
    updated_at = NOW()
`

type UpdateUserAgentMoreInfoParams struct {
	UserID            int64       `json:"user_id"`
	EducationalStatus pgtype.Text `json:"educational_status"`
	HighestDegree     pgtype.Text `json:"highest_degree"`
	GraduationYear    pgtype.Text `json:"graduation_year"`
	SchoolName        pgtype.Text `json:"school_name"`
}

func (q *Queries) UpdateUserAgentMoreInfo(ctx context.Context, arg UpdateUserAgentMoreInfoParams) error {
	_, err := q.db.Exec(ctx, updateUserAgentMoreInfo,
		arg.UserID,
		arg.EducationalStatus,
		arg.HighestDegree,
		arg.GraduationYear,
		arg.SchoolName,
	)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET avatar = $2,
    avatar_file_id = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID           int64       `json:"id"`
	Avatar       pgtype.Text `json:"avatar"`
	AvatarFileID pgtype.Int8 `json:"avatar_file_id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.Avatar, arg.AvatarFileID)
	return err
}

const updateUserDegreeCertificateUrl = `-- name: UpdateUserDegreeCertificateUrl :exec
INSERT INTO user_more_infos (
  user_id, degree_certificate_url
) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET degree_certificate_url = EXCLUDED.degree_certificate_url,
    updated_at = NOW()
`

type UpdateUserDegreeCertificateUrlParams struct {
	UserID               int64       `json:"user_id"`
	DegreeCertificateUrl pgtype.Text `json:"degree_certificate_url"`
}

func (q *Queries) UpdateUserDegreeCertificateUrl(ctx context.Context, arg UpdateUserDegreeCertificateUrlParams) error {
	_, err := q.db.Exec(ctx, updateUserDegreeCertificateUrl, arg.UserID, arg.DegreeCertificateUrl)
	return err
}

const updateUserFakeID = `-- name: UpdateUserFakeID :exec
UPDATE users
SET fake_id = $2
WHERE id = $1
`

type UpdateUserFakeIDParams struct {
	ID     int64       `json:"id"`
	FakeID pgtype.Int8 `json:"fake_id"`
}

func (q *Queries) UpdateUserFakeID(ctx context.Context, arg UpdateUserFakeIDParams) error {
	_, err := q.db.Exec(ctx, updateUserFakeID, arg.ID, arg.FakeID)
	return err
}

const updateUserHasRole = `-- name: UpdateUserHasRole :exec
UPDATE users
SET has_role = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserHasRoleParams struct {
	ID      int64       `json:"id"`
	HasRole pgtype.Bool `json:"has_role"`
}

func (q *Queries) UpdateUserHasRole(ctx context.Context, arg UpdateUserHasRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserHasRole, arg.ID, arg.HasRole)
	return err
}

const updateUserPasswordByFid = `-- name: UpdateUserPasswordByFid :exec
UPDATE users
SET password_hash = $2
WHERE fake_id = $1
`

type UpdateUserPasswordByFidParams struct {
	FakeID       pgtype.Int8 `json:"fake_id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordByFid(ctx context.Context, arg UpdateUserPasswordByFidParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordByFid, arg.FakeID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET first_name = $2,
    last_name = $3,
    middle_name = $4,
    gender = $5,
    avatar = $6,
    avatar_file_id = $7,
    current_country = $8,
    current_state = $9,
    current_city = $10,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID             int64       `json:"id"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	Gender         pgtype.Text `json:"gender"`
	Avatar         pgtype.Text `json:"avatar"`
	AvatarFileID   pgtype.Int8 `json:"avatar_file_id"`
	CurrentCountry int16       `json:"current_country"`
	CurrentState   int16       `json:"current_state"`
	CurrentCity    pgtype.Int4 `json:"current_city"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Gender,
		arg.Avatar,
		arg.AvatarFileID,
		arg.CurrentCountry,
		arg.CurrentState,
		arg.CurrentCity,
	)
	return err
}

const updateUserReferralCode = `-- name: UpdateUserReferralCode :exec
UPDATE users
SET referral_code = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserReferralCodeParams struct {
	ID           int64       `json:"id"`
	ReferralCode pgtype.Text `json:"referral_code"`
}

func (q *Queries) UpdateUserReferralCode(ctx context.Context, arg UpdateUserReferralCodeParams) error {
	_, err := q.db.Exec(ctx, updateUserReferralCode, arg.ID, arg.ReferralCode)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET account_status = $2
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID            int64       `json:"id"`
	AccountStatus pgtype.Text `json:"account_status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.AccountStatus)
	return err
}

const updateUserVotersCard = `-- name: UpdateUserVotersCard :exec
UPDATE users
SET voters_card_image = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserVotersCardParams struct {
	ID              int64       `json:"id"`
	VotersCardImage pgtype.Text `json:"voters_card_image"`
}

func (q *Queries) UpdateUserVotersCard(ctx context.Context, arg UpdateUserVotersCardParams) error {
	_, err := q.db.Exec(ctx, updateUserVotersCard, arg.ID, arg.VotersCardImage)
	return err
}

const upsertUserPhoneNumber = `-- name: UpsertUserPhoneNumber :one
INSERT INTO users_phone_numbers (user_id, phone, phonecode, raw_input, on_whatsapp, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (phone) DO UPDATE
SET on_whatsapp = EXCLUDED.on_whatsapp,
    is_active = true
RETURNING id
`

type UpsertUserPhoneNumberParams struct {
	UserID     int64       `json:"user_id"`
	Phone      string      `json:"phone"`
	Phonecode  string      `json:"phonecode"`
	RawInput   string      `json:"raw_input"`
	OnWhatsapp pgtype.Bool `json:"on_whatsapp"`
	IsDefault  pgtype.Bool `json:"is_default"`
}

func (q *Queries) UpsertUserPhoneNumber(ctx context.Context, arg UpsertUserPhoneNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertUserPhoneNumber,
		arg.UserID,
		arg.Phone,
		arg.Phonecode,
		arg.RawInput,
		arg.OnWhatsapp,
		arg.IsDefault,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
